package ejb.bean;

import java.math.BigDecimal;

// Generated by com.ibm.jzos.recordgen.cobol.RecordClassGenerator on Mon Feb 10 11:28:59 CET 2020

public class CT10025OCommareaWrapper1 {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 

	/** <pre>
	 01  OUTPUT-CT10025O. </pre> */
	public static final int OUTPUT_CT10025O_len = 672; 

	/** <pre>
	 02  VAL-CUENTA-O. </pre> */
	public static final int VAL_CUENTA_O_len = 672; 
	public static final int VAL_CUENTA_O_offset = factory.getOffset();

	/** <pre>
	   03  RES-MEN-CT1025O. </pre> */
	public static final int RES_MEN_CT1025O_len = 667; 
	public static final int RES_MEN_CT1025O_offset = factory.getOffset();

	/** <pre>
	     04  RES-MEN-CT1002O. </pre> */
	public static final int RES_MEN_CT1002O_len = 667; 
	public static final int RES_MEN_CT1002O_offset = factory.getOffset();

	/** <pre>
	       05  MODCT005. </pre> */
	public static final int MODCT005_len = 144; 
	public static final int MODCT005_offset = factory.getOffset();

	/** <pre>
	         06  NUM-ULT-MOV                   PIC S9(7) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField NUM_ULT_MOV = factory.getPackedDecimalAsIntField(7, true);

	/** <pre>
	         06  COD-ULT-CHECK                 PIC X(4). </pre> */
	protected static final StringField COD_ULT_CHECK = factory.getStringField(4);

	/** <pre>
	         06  IND-INFRUTTIFERO              PIC X(1). </pre> */
	protected static final StringField IND_INFRUTTIFERO = factory.getStringField(1);

	/** <pre>
	         88  NON-INFRUTTIFERO                VALUE '0'. </pre> */
	public static final String NON_INFRUTTIFERO = "0";

	/** <pre>
	         88  INFRUTTIFERO                    VALUE '1'. </pre> */
	public static final String INFRUTTIFERO = "1";

	/** <pre>
	         06  IND-PARTITA-MINIMA            PIC X(1). </pre> */
	protected static final StringField IND_PARTITA_MINIMA = factory.getStringField(1);

	/** <pre>
	         88  PARTITA-NON-MINIMA              VALUE '0'. </pre> */
	public static final String PARTITA_NON_MINIMA = "0";

	/** <pre>
	         88  PARTITA-MINIMA                  VALUE '1'. </pre> */
	public static final String PARTITA_MINIMA = "1";

	/** <pre>
	         06  FEM-ULT-LIQ-H                 PIC X(10). </pre> */
	protected static final StringField FEM_ULT_LIQ_H = factory.getStringField(10);

	/** <pre>
	         06  FEM-PROX-LIQ-H                PIC X(10). </pre> */
	protected static final StringField FEM_PROX_LIQ_H = factory.getStringField(10);

	/** <pre>
	         06  SAL-LIQUIDO                   PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField SAL_LIQUIDO = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  SAL-PENDENTE                  PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField SAL_PENDENTE = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-BENEFONDI                 PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_BENEFONDI = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-PAV-DARE                  PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_PAV_DARE = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-PAV-AVERE                 PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_PAV_AVERE = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-PPR-DARE                  PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_PPR_DARE = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-PPR-AVERE                 PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_PPR_AVERE = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-ASS-ILLIQ                 PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_ASS_ILLIQ = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-SBF-ILLIQ                 PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_SBF_ILLIQ = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-ALTRI-ILLIQ               PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_ALTRI_ILLIQ = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-ASS-INDISP                PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_ASS_INDISP = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-SBF-INDISP                PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_SBF_INDISP = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  TOT-ALTRI-INDISP              PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField TOT_ALTRI_INDISP = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	         06  FEM-ANTER-COND                PIC X(10). </pre> */
	protected static final StringField FEM_ANTER_COND = factory.getStringField(10);

	/** <pre>
	       05  COD-PROD                        PIC X(4). </pre> */
	protected static final StringField COD_PROD = factory.getStringField(4);

	/** <pre>
	       05  COD-SUC-ALTA                    PIC S9(4) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField COD_SUC_ALTA = factory.getPackedDecimalAsIntField(4, true);

	/** <pre>
	       05  COD-MONEDA                      PIC X(3). </pre> */
	protected static final StringField COD_MONEDA = factory.getStringField(3);

	/** <pre>
	       05  IND-EST-CUENTA                  PIC X(1). </pre> */
	protected static final StringField IND_EST_CUENTA = factory.getStringField(1);

	/** <pre>
	         88  PROPUESTA                       VALUE 'P'. </pre> */
	public static final String PROPUESTA = "P";

	/** <pre>
	         88  ACTIVO                          VALUE 'A'. </pre> */
	public static final String ACTIVO = "A";

	/** <pre>
	         88  BAJA                            VALUE 'B'. </pre> */
	public static final String BAJA = "B";

	/** <pre>
	         88  CANCELADO                       VALUE 'C'. </pre> */
	public static final String CANCELADO = "C";

	/** <pre>
	         88  PREAPERTURA                     VALUE 'E'. </pre> */
	public static final String PREAPERTURA = "E";

	/** <pre>
	         88  PRECANCELADO                    VALUE 'F'. </pre> */
	public static final String PRECANCELADO = "F";

	/** <pre>
	         88  RESTAURADO                      VALUE 'R'. </pre> */
	public static final String RESTAURADO = "R";

	/** <pre>
	         88  REHABILITADO                    VALUE 'H'. </pre> */
	public static final String REHABILITADO = "H";

	/** <pre>
	         88  PREANULADA                      VALUE 'G'. </pre> */
	public static final String PREANULADA = "G";

	/** <pre>
	         88  PRELITIGIO                      VALUE 'I'. </pre> */
	public static final String PRELITIGIO = "I";

	/** <pre>
	         88  LITIGIO                         VALUE 'J'. </pre> */
	public static final String LITIGIO = "J";

	/** <pre>
	         88  LITIGIO-CANCELADO               VALUE 'K'. </pre> */
	public static final String LITIGIO_CANCELADO = "K";

	/** <pre>
	         88  FALLIDO                         VALUE 'L'. </pre> */
	public static final String FALLIDO = "L";

	/** <pre>
	       05  IND-SD-LIMITE                   PIC X(1). </pre> */
	protected static final StringField IND_SD_LIMITE = factory.getStringField(1);

	/** <pre>
	         88  NORMAL                          VALUE '0'. </pre> */
	public static final String NORMAL = "0";

	/** <pre>
	         88  EXCEDIDO                        VALUE '1'. </pre> */
	public static final String EXCEDIDO = "1";

	/** <pre>
	         88  EXCEDIDO-MOROSO                 VALUE '2'. </pre> */
	public static final String EXCEDIDO_MOROSO = "2";

	/** <pre>
	         88  ACREEDOR                        VALUE '3'. </pre> */
	public static final String ACREEDOR = "3";

	/** <pre>
	       05  COD-SUC-PROPIE                  PIC S9(4) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField COD_SUC_PROPIE = factory.getPackedDecimalAsIntField(4, true);

	/** <pre>
	       05  FEM-OPERACION                   PIC X(10). </pre> */
	protected static final StringField FEM_OPERACION = factory.getStringField(10);

	/** <pre>
	       05  FEM-VALOR                       PIC X(10). </pre> */
	protected static final StringField FEM_VALOR = factory.getStringField(10);

	/** <pre>
	       05  FEM-CONTABLE                    PIC X(10). </pre> */
	protected static final StringField FEM_CONTABLE = factory.getStringField(10);

	/** <pre>
	       05  FEM-CONTA2                      PIC X(10). </pre> */
	protected static final StringField FEM_CONTA2 = factory.getStringField(10);

	/** <pre>
	       05  FEM-OPERACION2                  PIC X(10). </pre> */
	protected static final StringField FEM_OPERACION2 = factory.getStringField(10);

	/** <pre>
	       05  FEM-VALOR2                      PIC X(10). </pre> */
	protected static final StringField FEM_VALOR2 = factory.getStringField(10);

	/** <pre>
	       05  FEM-ULTIMA-OPE3                 PIC X(10). </pre> */
	protected static final StringField FEM_ULTIMA_OPE3 = factory.getStringField(10);

	/** <pre>
	       05  FEM-MODIFICACION                PIC X(10). </pre> */
	protected static final StringField FEM_MODIFICACION = factory.getStringField(10);

	/** <pre>
	       05  IMP-PROX-RED-LIM                PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField IMP_PROX_RED_LIM = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	       05  POR-REDUCCION                   PIC S9(3)V9(4) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField POR_REDUCCION = factory.getPackedDecimalAsBigDecimalField(7, 4, true);

	/** <pre>
	       05  FEM-FIN                         PIC X(10). </pre> */
	protected static final StringField FEM_FIN = factory.getStringField(10);

	/** <pre>
	       05  FEM-FIN2                        PIC X(10). </pre> */
	protected static final StringField FEM_FIN2 = factory.getStringField(10);

	/** <pre>
	       05  FEM-VENCIMIENTO                 PIC X(10). </pre> */
	protected static final StringField FEM_VENCIMIENTO = factory.getStringField(10);

	/** <pre>
	       05  FEM-OPERACION3                  PIC X(10). </pre> */
	protected static final StringField FEM_OPERACION3 = factory.getStringField(10);

	/** <pre>
	       05  FEM-VALOR3                      PIC X(10). </pre> */
	protected static final StringField FEM_VALOR3 = factory.getStringField(10);

	/** <pre>
	       05  FEM-CONTA5                      PIC X(10). </pre> */
	protected static final StringField FEM_CONTA5 = factory.getStringField(10);

	/** <pre>
	       05  SALCONTABLE                     PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField SALCONTABLE = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	       05  SALRETENIDO                     PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField SALRETENIDO = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	       05  IMP-LIM-CTA                     PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField IMP_LIM_CTA = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	       05  IMP-LIM-CUENACTU                PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField IMP_LIM_CUENACTU = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	       05  IMP-LIM-DISPOCTA                PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField IMP_LIM_DISPOCTA = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	       05  IND-CONDI-PROPU                 PIC X(1). </pre> */
	protected static final StringField IND_CONDI_PROPU = factory.getStringField(1);

	/** <pre>
	         88  ESTANDAR                        VALUE '0'. </pre> */
	public static final String ESTANDAR_In_IND_CONDI_PROPU = "0";

	/** <pre>
	         88  ESPECIAL                        VALUE '1'. </pre> */
	public static final String ESPECIAL = "1";

	/** <pre>
	         88  PARTICULAR                      VALUE '2'. </pre> */
	public static final String PARTICULAR = "2";

	/** <pre>
	       05  IND-VAR-LIQ                     PIC X(1). </pre> */
	protected static final StringField IND_VAR_LIQ = factory.getStringField(1);

	/** <pre>
	         88  NOVARIACIONES                   VALUE '0'. </pre> */
	public static final String NOVARIACIONES_In_IND_VAR_LIQ = "0";

	/** <pre>
	         88  VARIACIONES                     VALUE '1'. </pre> */
	public static final String VARIACIONES_In_IND_VAR_LIQ = "1";

	/** <pre>
	       05  FEM-INICIO                      PIC X(10). </pre> */
	protected static final StringField FEM_INICIO = factory.getStringField(10);

	/** <pre>
	       05  IND-VAR-COMI                    PIC X(1). </pre> */
	protected static final StringField IND_VAR_COMI = factory.getStringField(1);

	/** <pre>
	         88  NOVARIACIONES                   VALUE '0'. </pre> */
	public static final String NOVARIACIONES_In_IND_VAR_COMI = "0";

	/** <pre>
	         88  VARIACIONES                     VALUE '1'. </pre> */
	public static final String VARIACIONES_In_IND_VAR_COMI = "1";

	/** <pre>
	       05  FEM-INICIO2                     PIC X(10). </pre> */
	protected static final StringField FEM_INICIO2 = factory.getStringField(10);

	/** <pre>
	       05  IND-SEGPAQCON                   PIC S9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField IND_SEGPAQCON = factory.getPackedDecimalAsIntField(2, true);

	/** <pre>
	         88  SIN-CONDIC-ESPEC                VALUE 0. </pre> */
	public static final int SIN_CONDIC_ESPEC = 0;

	/** <pre>
	         88  CONDICION-SEGME                 VALUE 1. </pre> */
	public static final int CONDICION_SEGME = 1;

	/** <pre>
	         88  CONDICION-PAQUE                 VALUE 2. </pre> */
	public static final int CONDICION_PAQUE = 2;

	/** <pre>
	         88  CONDICION-CONVE                 VALUE 3. </pre> */
	public static final int CONDICION_CONVE = 3;

	/** <pre>
	         88  CONDICION-AMBIT                 VALUE 4. </pre> */
	public static final int CONDICION_AMBIT = 4;

	/** <pre>
	       05  COD-SEG-MERCADO                 PIC X(4). </pre> */
	protected static final StringField COD_SEG_MERCADO = factory.getStringField(4);

	/** <pre>
	       05  COD-PAQUETE                     PIC X(2). </pre> */
	protected static final StringField COD_PAQUETE = factory.getStringField(2);

	/** <pre>
	       05  COD-CONV-ESPEC                  PIC X(5). </pre> */
	protected static final StringField COD_CONV_ESPEC = factory.getStringField(5);

	/** <pre>
	       05  COD-CENTRO                      PIC X(4). </pre> */
	protected static final StringField COD_CENTRO = factory.getStringField(4);

	/** <pre>
	       05  IND-DESAUTORIZACIONES           PIC X(1). </pre> */
	protected static final StringField IND_DESAUTORIZACIONES = factory.getStringField(1);

	/** <pre>
	         88  NO-DESAUTOR                     VALUE '0'. </pre> */
	public static final String NO_DESAUTOR = "0";

	/** <pre>
	         88  SI-DESAUTOR                     VALUE '1'. </pre> */
	public static final String SI_DESAUTOR = "1";

	/** <pre>
	       05  IND-RETENCIONES                 PIC X(1). </pre> */
	protected static final StringField IND_RETENCIONES = factory.getStringField(1);

	/** <pre>
	         88  NO-RETEN                        VALUE '0'. </pre> */
	public static final String NO_RETEN = "0";

	/** <pre>
	         88  SI-RETEN                        VALUE '1'. </pre> */
	public static final String SI_RETEN = "1";

	/** <pre>
	       05  IND-AVISO                       PIC X(1). </pre> */
	protected static final StringField IND_AVISO = factory.getStringField(1);

	/** <pre>
	         88  SINAVISO                        VALUE '0'. </pre> */
	public static final String SINAVISO = "0";

	/** <pre>
	         88  CONAVISO                        VALUE '1'. </pre> */
	public static final String CONAVISO = "1";

	/** <pre>
	       05  IND-ORDEN-PER                   PIC X(1). </pre> */
	protected static final StringField IND_ORDEN_PER = factory.getStringField(1);

	/** <pre>
	         88  NO-ORDEN-PER                    VALUE '0'. </pre> */
	public static final String NO_ORDEN_PER = "0";

	/** <pre>
	         88  SI-ORDEN-PER                    VALUE '1'. </pre> */
	public static final String SI_ORDEN_PER = "1";

	/** <pre>
	       05  IND-SERVICIOS                   PIC X(1). </pre> */
	protected static final StringField IND_SERVICIOS = factory.getStringField(1);

	/** <pre>
	         88  NO-SERVICIOS                    VALUE '0'. </pre> */
	public static final String NO_SERVICIOS = "0";

	/** <pre>
	         88  SI-SERVICIOS                    VALUE '1'. </pre> */
	public static final String SI_SERVICIOS = "1";

	/** <pre>
	       05  IND-CTAS-ASOC                   PIC X(1). </pre> */
	protected static final StringField IND_CTAS_ASOC = factory.getStringField(1);

	/** <pre>
	         88  NO-CTAS-ASOC                    VALUE '0'. </pre> */
	public static final String NO_CTAS_ASOC = "0";

	/** <pre>
	         88  SI-CTAS-ASOC                    VALUE '1'. </pre> */
	public static final String SI_CTAS_ASOC = "1";

	/** <pre>
	       05  IND-DOMICI                      PIC X(1). </pre> */
	protected static final StringField IND_DOMICI = factory.getStringField(1);

	/** <pre>
	         88  NO-DOMICI                       VALUE '0'. </pre> */
	public static final String NO_DOMICI = "0";

	/** <pre>
	         88  SI-DOMICI                       VALUE '1'. </pre> */
	public static final String SI_DOMICI = "1";

	/** <pre>
	       05  IND-CAP-INTERESES               PIC X(1). </pre> */
	protected static final StringField IND_CAP_INTERESES = factory.getStringField(1);

	/** <pre>
	         88  NO-CAP-INTERESES                VALUE '0'. </pre> */
	public static final String NO_CAP_INTERESES = "0";

	/** <pre>
	         88  SI-CAP-INTERESES                VALUE '1'. </pre> */
	public static final String SI_CAP_INTERESES = "1";

	/** <pre>
	       05  IND-COND-DISP                   PIC X(1). </pre> */
	protected static final StringField IND_COND_DISP = factory.getStringField(1);

	/** <pre>
	         88  NO-COND-DISP                    VALUE '0'. </pre> */
	public static final String NO_COND_DISP = "0";

	/** <pre>
	         88  SI-COND-DISP                    VALUE '1'. </pre> */
	public static final String SI_COND_DISP = "1";

	/** <pre>
	       05  IND-LIB-PEDIDA                  PIC X(1). </pre> */
	protected static final StringField IND_LIB_PEDIDA = factory.getStringField(1);

	/** <pre>
	         88  NO-LIBRETA-PEDIDA               VALUE '0'. </pre> */
	public static final String NO_LIBRETA_PEDIDA = "0";

	/** <pre>
	         88  SI-LIBRETA-PEDIDA               VALUE '1'. </pre> */
	public static final String SI_LIBRETA_PEDIDA = "1";

	/** <pre>
	       05  IND-NIVEL-SEGURIDAD             PIC X(1). </pre> */
	protected static final StringField IND_NIVEL_SEGURIDAD = factory.getStringField(1);

	/** <pre>
	         88  NO-NIVEL-SEGUR                  VALUE '0'. </pre> */
	public static final String NO_NIVEL_SEGUR = "0";

	/** <pre>
	         88  SI-NIVEL-SEGUR                  VALUE '1'. </pre> */
	public static final String SI_NIVEL_SEGUR = "1";

	/** <pre>
	       05  IND-PER-LIQUES                  PIC X(1). </pre> */
	protected static final StringField IND_PER_LIQUES = factory.getStringField(1);

	/** <pre>
	         88  NOHAY                           VALUE '0'. </pre> */
	public static final String NOHAY_In_IND_PER_LIQUES = "0";

	/** <pre>
	         88  ESTANDAR                        VALUE '1'. </pre> */
	public static final String ESTANDAR_In_IND_PER_LIQUES = "1";

	/** <pre>
	         88  NOESTANDAR                      VALUE '2'. </pre> */
	public static final String NOESTANDAR_In_IND_PER_LIQUES = "2";

	/** <pre>
	       05  FEM-INICIO3                     PIC X(10). </pre> */
	protected static final StringField FEM_INICIO3 = factory.getStringField(10);

	/** <pre>
	       05  IND-CARENCIA-LIQ                PIC X(1). </pre> */
	protected static final StringField IND_CARENCIA_LIQ = factory.getStringField(1);

	/** <pre>
	         88  NOHAY                           VALUE '0'. </pre> */
	public static final String NOHAY_In_IND_CARENCIA_LIQ = "0";

	/** <pre>
	         88  ESTANDAR                        VALUE '1'. </pre> */
	public static final String ESTANDAR_In_IND_CARENCIA_LIQ = "1";

	/** <pre>
	         88  NOESTANDAR                      VALUE '2'. </pre> */
	public static final String NOESTANDAR_In_IND_CARENCIA_LIQ = "2";

	/** <pre>
	       05  FEM-INICIO5                     PIC X(10). </pre> */
	protected static final StringField FEM_INICIO5 = factory.getStringField(10);

	/** <pre>
	       05  IND-PER-REDLIMES                PIC X(1). </pre> */
	protected static final StringField IND_PER_REDLIMES = factory.getStringField(1);

	/** <pre>
	         88  NOHAY                           VALUE '0'. </pre> */
	public static final String NOHAY_In_IND_PER_REDLIMES = "0";

	/** <pre>
	         88  ESTANDAR                        VALUE '1'. </pre> */
	public static final String ESTANDAR_In_IND_PER_REDLIMES = "1";

	/** <pre>
	         88  NOESTANDAR                      VALUE '2'. </pre> */
	public static final String NOESTANDAR_In_IND_PER_REDLIMES = "2";

	/** <pre>
	       05  FEM-INICIO4                     PIC X(10). </pre> */
	protected static final StringField FEM_INICIO4 = factory.getStringField(10);

	/** <pre>
	       05  IND-CARENCIA-RED                PIC X(1). </pre> */
	protected static final StringField IND_CARENCIA_RED = factory.getStringField(1);

	/** <pre>
	         88  NOHAY                           VALUE '0'. </pre> */
	public static final String NOHAY_In_IND_CARENCIA_RED = "0";

	/** <pre>
	         88  ESTANDAR                        VALUE '1'. </pre> */
	public static final String ESTANDAR_In_IND_CARENCIA_RED = "1";

	/** <pre>
	         88  NOESTANDAR                      VALUE '2'. </pre> */
	public static final String NOESTANDAR_In_IND_CARENCIA_RED = "2";

	/** <pre>
	       05  FEM-INICIO6                     PIC X(10). </pre> */
	protected static final StringField FEM_INICIO6 = factory.getStringField(10);

	/** <pre>
	       05  IND-PLA-EST                     PIC X(1). </pre> */
	protected static final StringField IND_PLA_EST = factory.getStringField(1);

	/** <pre>
	       05  FEM-INICIO7                     PIC X(10). </pre> */
	protected static final StringField FEM_INICIO7 = factory.getStringField(10);

	/** <pre>
	       05  COD-NISEGU                      PIC X(4). </pre> */
	protected static final StringField COD_NISEGU = factory.getStringField(4);

	/** <pre>
	       05  FEM-ULTIMA-OPE4                 PIC X(10). </pre> */
	protected static final StringField FEM_ULTIMA_OPE4 = factory.getStringField(10);

	/** <pre>
	       05  FEM-ULTIMA-OPE5                 PIC X(10). </pre> */
	protected static final StringField FEM_ULTIMA_OPE5 = factory.getStringField(10);

	/** <pre>
	       05  IMP-DESCUBIERTO                 PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField IMP_DESCUBIERTO = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	       05  IND-MAN-CARLIRENO               PIC X(1). </pre> */
	protected static final StringField IND_MAN_CARLIRENO = factory.getStringField(1);

	/** <pre>
	         88  NO-MTTO-CARENCIA-LIQ-REN        VALUE '0'. </pre> */
	public static final String NO_MTTO_CARENCIA_LIQ_REN = "0";

	/** <pre>
	         88  SI-MTTO-CARENCIA-LIQ-REN        VALUE '1'. </pre> */
	public static final String SI_MTTO_CARENCIA_LIQ_REN = "1";

	/** <pre>
	       05  IND-MAN-CARREBRENO              PIC X(1). </pre> */
	protected static final StringField IND_MAN_CARREBRENO = factory.getStringField(1);

	/** <pre>
	         88  NO-MTTO-CARENCAI-REB-REN        VALUE '0'. </pre> */
	public static final String NO_MTTO_CARENCAI_REB_REN = "0";

	/** <pre>
	         88  SI-MTTO-CARENCAI-REB-REN        VALUE '1'. </pre> */
	public static final String SI_MTTO_CARENCAI_REB_REN = "1";

	/** <pre>
	       05  NUM-RENOV-EFEC                  PIC S9(3) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField NUM_RENOV_EFEC = factory.getPackedDecimalAsIntField(3, true);

	/** <pre>
	       05  IND-NUM-DIA-RES                 PIC X(1). </pre> */
	protected static final StringField IND_NUM_DIA_RES = factory.getStringField(1);

	/** <pre>
	         88  CORTO                           VALUE '0'. </pre> */
	public static final String CORTO = "0";

	/** <pre>
	         88  LARGO                           VALUE '1'. </pre> */
	public static final String LARGO = "1";

	/** <pre>
	       05  COD-SECTOR                      PIC X(6). </pre> */
	protected static final StringField COD_SECTOR = factory.getStringField(6);

	/** <pre>
	       05  COD-GARANTIA                    PIC X(5). </pre> */
	protected static final StringField COD_GARANTIA = factory.getStringField(5);

	/** <pre>
	       05  COD-FINALI                      PIC X(5). </pre> */
	protected static final StringField COD_FINALI = factory.getStringField(5);

	/** <pre>
	       05  IND-COMPUTABLE                  PIC X(1). </pre> */
	protected static final StringField IND_COMPUTABLE = factory.getStringField(1);

	/** <pre>
	         88  COMPUTABLE                      VALUE '1'. </pre> */
	public static final String COMPUTABLE = "1";

	/** <pre>
	         88  NO-COMPUTABLE                   VALUE '0'. </pre> */
	public static final String NO_COMPUTABLE = "0";

	/** <pre>
	       05  COD-TIP-PROP                    PIC X(2). </pre> */
	protected static final StringField COD_TIP_PROP = factory.getStringField(2);

	/** <pre>
	         88  CREACION                        VALUE '01'. </pre> */
	public static final String CREACION = "01";

	/** <pre>
	         88  DESCUBIERTO-EXCEDIDO            VALUE '02'. </pre> */
	public static final String DESCUBIERTO_EXCEDIDO = "02";

	/** <pre>
	         88  APLAZAMIENTO-PAGO               VALUE '03'. </pre> */
	public static final String APLAZAMIENTO_PAGO = "03";

	/** <pre>
	         88  MODIF-FUNCIONAMIENTO            VALUE '04'. </pre> */
	public static final String MODIF_FUNCIONAMIENTO = "04";

	/** <pre>
	         88  MODIF-INTERVINIENTES            VALUE '05'. </pre> */
	public static final String MODIF_INTERVINIENTES = "05";

	/** <pre>
	         88  MODIF-COND-DISPOSICION          VALUE '06'. </pre> */
	public static final String MODIF_COND_DISPOSICION = "06";

	/** <pre>
	         88  CAMBIOS-SITUACION               VALUE '07'. </pre> */
	public static final String CAMBIOS_SITUACION = "07";

	/** <pre>
	         88  RENOVACION                      VALUE '08'. </pre> */
	public static final String RENOVACION = "08";

	/** <pre>
	         88  PROPUESTA-CONJUNTA              VALUE '09'. </pre> */
	public static final String PROPUESTA_CONJUNTA = "09";

	/** <pre>
	         88  PROPUESTA-MODIFICACION-PAN      VALUE '10'. </pre> */
	public static final String PROPUESTA_MODIFICACION_PAN = "10";

	/** <pre>
	       05  FEM-PROPU                       PIC X(10). </pre> */
	protected static final StringField FEM_PROPU = factory.getStringField(10);

	/** <pre>
	       05  FEM-APLICACION                  PIC X(10). </pre> */
	protected static final StringField FEM_APLICACION = factory.getStringField(10);

	/** <pre>
	       05  FEM-APLICACION2                 PIC X(10). </pre> */
	protected static final StringField FEM_APLICACION2 = factory.getStringField(10);

	/** <pre>
	       05  IMPCOMISION                     PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField IMPCOMISION = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	       05  NUM-OPECANNA                    PIC S9(7) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField NUM_OPECANNA = factory.getPackedDecimalAsIntField(7, true);

	/** <pre>
	       05  NUM-OPEABANNA                   PIC S9(7) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField NUM_OPEABANNA = factory.getPackedDecimalAsIntField(7, true);

	/** <pre>
	       05  IMP-OPCAANACT                   PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField IMP_OPCAANACT = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	       05  IMP-OPABANACT                   PIC S9(13)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField IMP_OPABANACT = factory.getPackedDecimalAsBigDecimalField(15, 2, true);

	/** <pre>
	       05  NUM-DIA-DES-ANO                 PIC S9(3) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField NUM_DIA_DES_ANO = factory.getPackedDecimalAsIntField(3, true);

	/** <pre>
	       05  FEM-INICIO9                     PIC X(10). </pre> */
	protected static final StringField FEM_INICIO9 = factory.getStringField(10);

	/** <pre>
	       05  IND-TAS-AJUS-AC                 PIC X(1). </pre> */
	protected static final StringField IND_TAS_AJUS_AC = factory.getStringField(1);

	/** <pre>
	       05  FEM-INICIO10                    PIC X(10). </pre> */
	protected static final StringField FEM_INICIO10 = factory.getStringField(10);

	/** <pre>
	       05  IND-TAS-AJUS-DE                 PIC X(1). </pre> */
	protected static final StringField IND_TAS_AJUS_DE = factory.getStringField(1);

	/** <pre>
	       05  IND-CAR01-EST                   PIC X(1). </pre> */
	protected static final StringField IND_CAR01_EST = factory.getStringField(1);

	/** <pre>
	       05  FEM-CARACT01                    PIC X(10). </pre> */
	protected static final StringField FEM_CARACT01 = factory.getStringField(10);

	/** <pre>
	       05  FEM-CONTA3                      PIC X(10). </pre> */
	protected static final StringField FEM_CONTA3 = factory.getStringField(10);

	/** <pre>
	       05  COD-TIP-INTERES                 PIC X(2). </pre> */
	protected static final StringField COD_TIP_INTERES = factory.getStringField(2);

	/** <pre>
	         88  FIJO                            VALUE '00'. </pre> */
	public static final String FIJO = "00";

	/** <pre>
	         88  VARIABLE                        VALUE '01'. </pre> */
	public static final String VARIABLE = "01";

	/** <pre>
	       05  COD-AN-DOC                      PIC X(4). </pre> */
	protected static final StringField COD_AN_DOC = factory.getStringField(4);

	/** <pre>
	       05  TIMESTAMP-SIGLOM                PIC X(26). </pre> */
	protected static final StringField TIMESTAMP_SIGLOM = factory.getStringField(26);

	/** <pre>
	       05  COD-USU-MODIF                   PIC X(8). </pre> */
	protected static final StringField COD_USU_MODIF = factory.getStringField(8);

	/** <pre>
	       05  COD-DOMINIO                     PIC S9(4) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField COD_DOMINIO = factory.getPackedDecimalAsIntField(4, true);

	/** <pre>
	       05  NUM-NODO                        PIC S9(4) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField NUM_NODO = factory.getPackedDecimalAsIntField(4, true);

	/** <pre>
	       05  IND-MOD-TABLA                   PIC X(1). </pre> */
	protected static final StringField IND_MOD_TABLA = factory.getStringField(1);

	/** <pre>
	   03  COD-MSJE-RETORNO                    PIC X(5). </pre> */
	protected static final StringField COD_MSJE_RETORNO = factory.getStringField(5);

	protected byte[] _byteBuffer;
	// Instance variables used to cache field values
	protected Integer numUltMov;
	protected String codUltCheck;
	protected String indInfruttifero;
	protected String indPartitaMinima;
	protected String femUltLiqH;
	protected String femProxLiqH;
	protected BigDecimal salLiquido;
	protected BigDecimal salPendente;
	protected BigDecimal totBenefondi;
	protected BigDecimal totPavDare;
	protected BigDecimal totPavAvere;
	protected BigDecimal totPprDare;
	protected BigDecimal totPprAvere;
	protected BigDecimal totAssIlliq;
	protected BigDecimal totSbfIlliq;
	protected BigDecimal totAltriIlliq;
	protected BigDecimal totAssIndisp;
	protected BigDecimal totSbfIndisp;
	protected BigDecimal totAltriIndisp;
	protected String femAnterCond;
	protected String codProd;
	protected Integer codSucAlta;
	protected String codMoneda;
	protected String indEstCuenta;
	protected String indSdLimite;
	protected Integer codSucPropie;
	protected String femOperacion;
	protected String femValor;
	protected String femContable;
	protected String femConta2;
	protected String femOperacion2;
	protected String femValor2;
	protected String femUltimaOpe3;
	protected String femModificacion;
	protected BigDecimal impProxRedLim;
	protected BigDecimal porReduccion;
	protected String femFin;
	protected String femFin2;
	protected String femVencimiento;
	protected String femOperacion3;
	protected String femValor3;
	protected String femConta5;
	protected BigDecimal salcontable;
	protected BigDecimal salretenido;
	protected BigDecimal impLimCta;
	protected BigDecimal impLimCuenactu;
	protected BigDecimal impLimDispocta;
	protected String indCondiPropu;
	protected String indVarLiq;
	protected String femInicio;
	protected String indVarComi;
	protected String femInicio2;
	protected Integer indSegpaqcon;
	protected String codSegMercado;
	protected String codPaquete;
	protected String codConvEspec;
	protected String codCentro;
	protected String indDesautorizaciones;
	protected String indRetenciones;
	protected String indAviso;
	protected String indOrdenPer;
	protected String indServicios;
	protected String indCtasAsoc;
	protected String indDomici;
	protected String indCapIntereses;
	protected String indCondDisp;
	protected String indLibPedida;
	protected String indNivelSeguridad;
	protected String indPerLiques;
	protected String femInicio3;
	protected String indCarenciaLiq;
	protected String femInicio5;
	protected String indPerRedlimes;
	protected String femInicio4;
	protected String indCarenciaRed;
	protected String femInicio6;
	protected String indPlaEst;
	protected String femInicio7;
	protected String codNisegu;
	protected String femUltimaOpe4;
	protected String femUltimaOpe5;
	protected BigDecimal impDescubierto;
	protected String indManCarlireno;
	protected String indManCarrebreno;
	protected Integer numRenovEfec;
	protected String indNumDiaRes;
	protected String codSector;
	protected String codGarantia;
	protected String codFinali;
	protected String indComputable;
	protected String codTipProp;
	protected String femPropu;
	protected String femAplicacion;
	protected String femAplicacion2;
	protected BigDecimal impcomision;
	protected Integer numOpecanna;
	protected Integer numOpeabanna;
	protected BigDecimal impOpcaanact;
	protected BigDecimal impOpabanact;
	protected Integer numDiaDesAno;
	protected String femInicio9;
	protected String indTasAjusAc;
	protected String femInicio10;
	protected String indTasAjusDe;
	protected String indCar01Est;
	protected String femCaract01;
	protected String femConta3;
	protected String codTipInteres;
	protected String codAnDoc;
	protected String timestampSiglom;
	protected String codUsuModif;
	protected Integer codDominio;
	protected Integer numNodo;
	protected String indModTabla;
	protected String codMsjeRetorno;


	public CT10025OCommareaWrapper1 (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public CT10025OCommareaWrapper1 () {
		this._byteBuffer = new byte[OUTPUT_CT10025O_len];
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public int getNumUltMov() {
		if (numUltMov == null) {
			numUltMov = new Integer(NUM_ULT_MOV.getInt(_byteBuffer));
		}
		return numUltMov.intValue();
	}

	public void setNumUltMov(int numUltMov) {
		if (NUM_ULT_MOV.equals(this.numUltMov, numUltMov)) {
			return;
		}
		NUM_ULT_MOV.putInt(numUltMov, _byteBuffer);
		this.numUltMov = new Integer(numUltMov);
	}

	public String getCodUltCheck() {
		if (codUltCheck == null) {
			codUltCheck = COD_ULT_CHECK.getString(_byteBuffer);
		}
		return codUltCheck;
	}

	public void setCodUltCheck(String codUltCheck) {
		if (COD_ULT_CHECK.equals(this.codUltCheck, codUltCheck)) {
			return;
		}
		COD_ULT_CHECK.putString(codUltCheck, _byteBuffer);
		this.codUltCheck = codUltCheck;
	}

	public String getIndInfruttifero() {
		if (indInfruttifero == null) {
			indInfruttifero = IND_INFRUTTIFERO.getString(_byteBuffer);
		}
		return indInfruttifero;
	}

	public void setIndInfruttifero(String indInfruttifero) {
		if (IND_INFRUTTIFERO.equals(this.indInfruttifero, indInfruttifero)) {
			return;
		}
		IND_INFRUTTIFERO.putString(indInfruttifero, _byteBuffer);
		this.indInfruttifero = indInfruttifero;
	}

	public boolean isNonInfruttifero() {
		return getIndInfruttifero().equals(NON_INFRUTTIFERO);
	}

	public boolean isInfruttifero() {
		return getIndInfruttifero().equals(INFRUTTIFERO);
	}

	public String getIndPartitaMinima() {
		if (indPartitaMinima == null) {
			indPartitaMinima = IND_PARTITA_MINIMA.getString(_byteBuffer);
		}
		return indPartitaMinima;
	}

	public void setIndPartitaMinima(String indPartitaMinima) {
		if (IND_PARTITA_MINIMA.equals(this.indPartitaMinima, indPartitaMinima)) {
			return;
		}
		IND_PARTITA_MINIMA.putString(indPartitaMinima, _byteBuffer);
		this.indPartitaMinima = indPartitaMinima;
	}

	public boolean isPartitaNonMinima() {
		return getIndPartitaMinima().equals(PARTITA_NON_MINIMA);
	}

	public boolean isPartitaMinima() {
		return getIndPartitaMinima().equals(PARTITA_MINIMA);
	}

	public String getFemUltLiqH() {
		if (femUltLiqH == null) {
			femUltLiqH = FEM_ULT_LIQ_H.getString(_byteBuffer);
		}
		return femUltLiqH;
	}

	public void setFemUltLiqH(String femUltLiqH) {
		if (FEM_ULT_LIQ_H.equals(this.femUltLiqH, femUltLiqH)) {
			return;
		}
		FEM_ULT_LIQ_H.putString(femUltLiqH, _byteBuffer);
		this.femUltLiqH = femUltLiqH;
	}

	public String getFemProxLiqH() {
		if (femProxLiqH == null) {
			femProxLiqH = FEM_PROX_LIQ_H.getString(_byteBuffer);
		}
		return femProxLiqH;
	}

	public void setFemProxLiqH(String femProxLiqH) {
		if (FEM_PROX_LIQ_H.equals(this.femProxLiqH, femProxLiqH)) {
			return;
		}
		FEM_PROX_LIQ_H.putString(femProxLiqH, _byteBuffer);
		this.femProxLiqH = femProxLiqH;
	}

	public BigDecimal getSalLiquido() {
		if (salLiquido == null) {
			salLiquido = SAL_LIQUIDO.getBigDecimal(_byteBuffer);
		}
		return salLiquido;
	}

	public void setSalLiquido(BigDecimal salLiquido) {
		if (SAL_LIQUIDO.equals(this.salLiquido, salLiquido)) {
			return;
		}
		SAL_LIQUIDO.putBigDecimal(salLiquido, _byteBuffer);
		this.salLiquido = salLiquido;
	}

	public BigDecimal getSalPendente() {
		if (salPendente == null) {
			salPendente = SAL_PENDENTE.getBigDecimal(_byteBuffer);
		}
		return salPendente;
	}

	public void setSalPendente(BigDecimal salPendente) {
		if (SAL_PENDENTE.equals(this.salPendente, salPendente)) {
			return;
		}
		SAL_PENDENTE.putBigDecimal(salPendente, _byteBuffer);
		this.salPendente = salPendente;
	}

	public BigDecimal getTotBenefondi() {
		if (totBenefondi == null) {
			totBenefondi = TOT_BENEFONDI.getBigDecimal(_byteBuffer);
		}
		return totBenefondi;
	}

	public void setTotBenefondi(BigDecimal totBenefondi) {
		if (TOT_BENEFONDI.equals(this.totBenefondi, totBenefondi)) {
			return;
		}
		TOT_BENEFONDI.putBigDecimal(totBenefondi, _byteBuffer);
		this.totBenefondi = totBenefondi;
	}

	public BigDecimal getTotPavDare() {
		if (totPavDare == null) {
			totPavDare = TOT_PAV_DARE.getBigDecimal(_byteBuffer);
		}
		return totPavDare;
	}

	public void setTotPavDare(BigDecimal totPavDare) {
		if (TOT_PAV_DARE.equals(this.totPavDare, totPavDare)) {
			return;
		}
		TOT_PAV_DARE.putBigDecimal(totPavDare, _byteBuffer);
		this.totPavDare = totPavDare;
	}

	public BigDecimal getTotPavAvere() {
		if (totPavAvere == null) {
			totPavAvere = TOT_PAV_AVERE.getBigDecimal(_byteBuffer);
		}
		return totPavAvere;
	}

	public void setTotPavAvere(BigDecimal totPavAvere) {
		if (TOT_PAV_AVERE.equals(this.totPavAvere, totPavAvere)) {
			return;
		}
		TOT_PAV_AVERE.putBigDecimal(totPavAvere, _byteBuffer);
		this.totPavAvere = totPavAvere;
	}

	public BigDecimal getTotPprDare() {
		if (totPprDare == null) {
			totPprDare = TOT_PPR_DARE.getBigDecimal(_byteBuffer);
		}
		return totPprDare;
	}

	public void setTotPprDare(BigDecimal totPprDare) {
		if (TOT_PPR_DARE.equals(this.totPprDare, totPprDare)) {
			return;
		}
		TOT_PPR_DARE.putBigDecimal(totPprDare, _byteBuffer);
		this.totPprDare = totPprDare;
	}

	public BigDecimal getTotPprAvere() {
		if (totPprAvere == null) {
			totPprAvere = TOT_PPR_AVERE.getBigDecimal(_byteBuffer);
		}
		return totPprAvere;
	}

	public void setTotPprAvere(BigDecimal totPprAvere) {
		if (TOT_PPR_AVERE.equals(this.totPprAvere, totPprAvere)) {
			return;
		}
		TOT_PPR_AVERE.putBigDecimal(totPprAvere, _byteBuffer);
		this.totPprAvere = totPprAvere;
	}

	public BigDecimal getTotAssIlliq() {
		if (totAssIlliq == null) {
			totAssIlliq = TOT_ASS_ILLIQ.getBigDecimal(_byteBuffer);
		}
		return totAssIlliq;
	}

	public void setTotAssIlliq(BigDecimal totAssIlliq) {
		if (TOT_ASS_ILLIQ.equals(this.totAssIlliq, totAssIlliq)) {
			return;
		}
		TOT_ASS_ILLIQ.putBigDecimal(totAssIlliq, _byteBuffer);
		this.totAssIlliq = totAssIlliq;
	}

	public BigDecimal getTotSbfIlliq() {
		if (totSbfIlliq == null) {
			totSbfIlliq = TOT_SBF_ILLIQ.getBigDecimal(_byteBuffer);
		}
		return totSbfIlliq;
	}

	public void setTotSbfIlliq(BigDecimal totSbfIlliq) {
		if (TOT_SBF_ILLIQ.equals(this.totSbfIlliq, totSbfIlliq)) {
			return;
		}
		TOT_SBF_ILLIQ.putBigDecimal(totSbfIlliq, _byteBuffer);
		this.totSbfIlliq = totSbfIlliq;
	}

	public BigDecimal getTotAltriIlliq() {
		if (totAltriIlliq == null) {
			totAltriIlliq = TOT_ALTRI_ILLIQ.getBigDecimal(_byteBuffer);
		}
		return totAltriIlliq;
	}

	public void setTotAltriIlliq(BigDecimal totAltriIlliq) {
		if (TOT_ALTRI_ILLIQ.equals(this.totAltriIlliq, totAltriIlliq)) {
			return;
		}
		TOT_ALTRI_ILLIQ.putBigDecimal(totAltriIlliq, _byteBuffer);
		this.totAltriIlliq = totAltriIlliq;
	}

	public BigDecimal getTotAssIndisp() {
		if (totAssIndisp == null) {
			totAssIndisp = TOT_ASS_INDISP.getBigDecimal(_byteBuffer);
		}
		return totAssIndisp;
	}

	public void setTotAssIndisp(BigDecimal totAssIndisp) {
		if (TOT_ASS_INDISP.equals(this.totAssIndisp, totAssIndisp)) {
			return;
		}
		TOT_ASS_INDISP.putBigDecimal(totAssIndisp, _byteBuffer);
		this.totAssIndisp = totAssIndisp;
	}

	public BigDecimal getTotSbfIndisp() {
		if (totSbfIndisp == null) {
			totSbfIndisp = TOT_SBF_INDISP.getBigDecimal(_byteBuffer);
		}
		return totSbfIndisp;
	}

	public void setTotSbfIndisp(BigDecimal totSbfIndisp) {
		if (TOT_SBF_INDISP.equals(this.totSbfIndisp, totSbfIndisp)) {
			return;
		}
		TOT_SBF_INDISP.putBigDecimal(totSbfIndisp, _byteBuffer);
		this.totSbfIndisp = totSbfIndisp;
	}

	public BigDecimal getTotAltriIndisp() {
		if (totAltriIndisp == null) {
			totAltriIndisp = TOT_ALTRI_INDISP.getBigDecimal(_byteBuffer);
		}
		return totAltriIndisp;
	}

	public void setTotAltriIndisp(BigDecimal totAltriIndisp) {
		if (TOT_ALTRI_INDISP.equals(this.totAltriIndisp, totAltriIndisp)) {
			return;
		}
		TOT_ALTRI_INDISP.putBigDecimal(totAltriIndisp, _byteBuffer);
		this.totAltriIndisp = totAltriIndisp;
	}

	public String getFemAnterCond() {
		if (femAnterCond == null) {
			femAnterCond = FEM_ANTER_COND.getString(_byteBuffer);
		}
		return femAnterCond;
	}

	public void setFemAnterCond(String femAnterCond) {
		if (FEM_ANTER_COND.equals(this.femAnterCond, femAnterCond)) {
			return;
		}
		FEM_ANTER_COND.putString(femAnterCond, _byteBuffer);
		this.femAnterCond = femAnterCond;
	}

	public String getCodProd() {
		if (codProd == null) {
			codProd = COD_PROD.getString(_byteBuffer);
		}
		return codProd;
	}

	public void setCodProd(String codProd) {
		if (COD_PROD.equals(this.codProd, codProd)) {
			return;
		}
		COD_PROD.putString(codProd, _byteBuffer);
		this.codProd = codProd;
	}

	public int getCodSucAlta() {
		if (codSucAlta == null) {
			codSucAlta = new Integer(COD_SUC_ALTA.getInt(_byteBuffer));
		}
		return codSucAlta.intValue();
	}

	public void setCodSucAlta(int codSucAlta) {
		if (COD_SUC_ALTA.equals(this.codSucAlta, codSucAlta)) {
			return;
		}
		COD_SUC_ALTA.putInt(codSucAlta, _byteBuffer);
		this.codSucAlta = new Integer(codSucAlta);
	}

	public String getCodMoneda() {
		if (codMoneda == null) {
			codMoneda = COD_MONEDA.getString(_byteBuffer);
		}
		return codMoneda;
	}

	public void setCodMoneda(String codMoneda) {
		if (COD_MONEDA.equals(this.codMoneda, codMoneda)) {
			return;
		}
		COD_MONEDA.putString(codMoneda, _byteBuffer);
		this.codMoneda = codMoneda;
	}

	public String getIndEstCuenta() {
		if (indEstCuenta == null) {
			indEstCuenta = IND_EST_CUENTA.getString(_byteBuffer);
		}
		return indEstCuenta;
	}

	public void setIndEstCuenta(String indEstCuenta) {
		if (IND_EST_CUENTA.equals(this.indEstCuenta, indEstCuenta)) {
			return;
		}
		IND_EST_CUENTA.putString(indEstCuenta, _byteBuffer);
		this.indEstCuenta = indEstCuenta;
	}

	public boolean isPropuesta() {
		return getIndEstCuenta().equals(PROPUESTA);
	}

	public boolean isActivo() {
		return getIndEstCuenta().equals(ACTIVO);
	}

	public boolean isBaja() {
		return getIndEstCuenta().equals(BAJA);
	}

	public boolean isCancelado() {
		return getIndEstCuenta().equals(CANCELADO);
	}

	public boolean isPreapertura() {
		return getIndEstCuenta().equals(PREAPERTURA);
	}

	public boolean isPrecancelado() {
		return getIndEstCuenta().equals(PRECANCELADO);
	}

	public boolean isRestaurado() {
		return getIndEstCuenta().equals(RESTAURADO);
	}

	public boolean isRehabilitado() {
		return getIndEstCuenta().equals(REHABILITADO);
	}

	public boolean isPreanulada() {
		return getIndEstCuenta().equals(PREANULADA);
	}

	public boolean isPrelitigio() {
		return getIndEstCuenta().equals(PRELITIGIO);
	}

	public boolean isLitigio() {
		return getIndEstCuenta().equals(LITIGIO);
	}

	public boolean isLitigioCancelado() {
		return getIndEstCuenta().equals(LITIGIO_CANCELADO);
	}

	public boolean isFallido() {
		return getIndEstCuenta().equals(FALLIDO);
	}

	public String getIndSdLimite() {
		if (indSdLimite == null) {
			indSdLimite = IND_SD_LIMITE.getString(_byteBuffer);
		}
		return indSdLimite;
	}

	public void setIndSdLimite(String indSdLimite) {
		if (IND_SD_LIMITE.equals(this.indSdLimite, indSdLimite)) {
			return;
		}
		IND_SD_LIMITE.putString(indSdLimite, _byteBuffer);
		this.indSdLimite = indSdLimite;
	}

	public boolean isNormal() {
		return getIndSdLimite().equals(NORMAL);
	}

	public boolean isExcedido() {
		return getIndSdLimite().equals(EXCEDIDO);
	}

	public boolean isExcedidoMoroso() {
		return getIndSdLimite().equals(EXCEDIDO_MOROSO);
	}

	public boolean isAcreedor() {
		return getIndSdLimite().equals(ACREEDOR);
	}

	public int getCodSucPropie() {
		if (codSucPropie == null) {
			codSucPropie = new Integer(COD_SUC_PROPIE.getInt(_byteBuffer));
		}
		return codSucPropie.intValue();
	}

	public void setCodSucPropie(int codSucPropie) {
		if (COD_SUC_PROPIE.equals(this.codSucPropie, codSucPropie)) {
			return;
		}
		COD_SUC_PROPIE.putInt(codSucPropie, _byteBuffer);
		this.codSucPropie = new Integer(codSucPropie);
	}

	public String getFemOperacion() {
		if (femOperacion == null) {
			femOperacion = FEM_OPERACION.getString(_byteBuffer);
		}
		return femOperacion;
	}

	public void setFemOperacion(String femOperacion) {
		if (FEM_OPERACION.equals(this.femOperacion, femOperacion)) {
			return;
		}
		FEM_OPERACION.putString(femOperacion, _byteBuffer);
		this.femOperacion = femOperacion;
	}

	public String getFemValor() {
		if (femValor == null) {
			femValor = FEM_VALOR.getString(_byteBuffer);
		}
		return femValor;
	}

	public void setFemValor(String femValor) {
		if (FEM_VALOR.equals(this.femValor, femValor)) {
			return;
		}
		FEM_VALOR.putString(femValor, _byteBuffer);
		this.femValor = femValor;
	}

	public String getFemContable() {
		if (femContable == null) {
			femContable = FEM_CONTABLE.getString(_byteBuffer);
		}
		return femContable;
	}

	public void setFemContable(String femContable) {
		if (FEM_CONTABLE.equals(this.femContable, femContable)) {
			return;
		}
		FEM_CONTABLE.putString(femContable, _byteBuffer);
		this.femContable = femContable;
	}

	public String getFemConta2() {
		if (femConta2 == null) {
			femConta2 = FEM_CONTA2.getString(_byteBuffer);
		}
		return femConta2;
	}

	public void setFemConta2(String femConta2) {
		if (FEM_CONTA2.equals(this.femConta2, femConta2)) {
			return;
		}
		FEM_CONTA2.putString(femConta2, _byteBuffer);
		this.femConta2 = femConta2;
	}

	public String getFemOperacion2() {
		if (femOperacion2 == null) {
			femOperacion2 = FEM_OPERACION2.getString(_byteBuffer);
		}
		return femOperacion2;
	}

	public void setFemOperacion2(String femOperacion2) {
		if (FEM_OPERACION2.equals(this.femOperacion2, femOperacion2)) {
			return;
		}
		FEM_OPERACION2.putString(femOperacion2, _byteBuffer);
		this.femOperacion2 = femOperacion2;
	}

	public String getFemValor2() {
		if (femValor2 == null) {
			femValor2 = FEM_VALOR2.getString(_byteBuffer);
		}
		return femValor2;
	}

	public void setFemValor2(String femValor2) {
		if (FEM_VALOR2.equals(this.femValor2, femValor2)) {
			return;
		}
		FEM_VALOR2.putString(femValor2, _byteBuffer);
		this.femValor2 = femValor2;
	}

	public String getFemUltimaOpe3() {
		if (femUltimaOpe3 == null) {
			femUltimaOpe3 = FEM_ULTIMA_OPE3.getString(_byteBuffer);
		}
		return femUltimaOpe3;
	}

	public void setFemUltimaOpe3(String femUltimaOpe3) {
		if (FEM_ULTIMA_OPE3.equals(this.femUltimaOpe3, femUltimaOpe3)) {
			return;
		}
		FEM_ULTIMA_OPE3.putString(femUltimaOpe3, _byteBuffer);
		this.femUltimaOpe3 = femUltimaOpe3;
	}

	public String getFemModificacion() {
		if (femModificacion == null) {
			femModificacion = FEM_MODIFICACION.getString(_byteBuffer);
		}
		return femModificacion;
	}

	public void setFemModificacion(String femModificacion) {
		if (FEM_MODIFICACION.equals(this.femModificacion, femModificacion)) {
			return;
		}
		FEM_MODIFICACION.putString(femModificacion, _byteBuffer);
		this.femModificacion = femModificacion;
	}

	public BigDecimal getImpProxRedLim() {
		if (impProxRedLim == null) {
			impProxRedLim = IMP_PROX_RED_LIM.getBigDecimal(_byteBuffer);
		}
		return impProxRedLim;
	}

	public void setImpProxRedLim(BigDecimal impProxRedLim) {
		if (IMP_PROX_RED_LIM.equals(this.impProxRedLim, impProxRedLim)) {
			return;
		}
		IMP_PROX_RED_LIM.putBigDecimal(impProxRedLim, _byteBuffer);
		this.impProxRedLim = impProxRedLim;
	}

	public BigDecimal getPorReduccion() {
		if (porReduccion == null) {
			porReduccion = POR_REDUCCION.getBigDecimal(_byteBuffer);
		}
		return porReduccion;
	}

	public void setPorReduccion(BigDecimal porReduccion) {
		if (POR_REDUCCION.equals(this.porReduccion, porReduccion)) {
			return;
		}
		POR_REDUCCION.putBigDecimal(porReduccion, _byteBuffer);
		this.porReduccion = porReduccion;
	}

	public String getFemFin() {
		if (femFin == null) {
			femFin = FEM_FIN.getString(_byteBuffer);
		}
		return femFin;
	}

	public void setFemFin(String femFin) {
		if (FEM_FIN.equals(this.femFin, femFin)) {
			return;
		}
		FEM_FIN.putString(femFin, _byteBuffer);
		this.femFin = femFin;
	}

	public String getFemFin2() {
		if (femFin2 == null) {
			femFin2 = FEM_FIN2.getString(_byteBuffer);
		}
		return femFin2;
	}

	public void setFemFin2(String femFin2) {
		if (FEM_FIN2.equals(this.femFin2, femFin2)) {
			return;
		}
		FEM_FIN2.putString(femFin2, _byteBuffer);
		this.femFin2 = femFin2;
	}

	public String getFemVencimiento() {
		if (femVencimiento == null) {
			femVencimiento = FEM_VENCIMIENTO.getString(_byteBuffer);
		}
		return femVencimiento;
	}

	public void setFemVencimiento(String femVencimiento) {
		if (FEM_VENCIMIENTO.equals(this.femVencimiento, femVencimiento)) {
			return;
		}
		FEM_VENCIMIENTO.putString(femVencimiento, _byteBuffer);
		this.femVencimiento = femVencimiento;
	}

	public String getFemOperacion3() {
		if (femOperacion3 == null) {
			femOperacion3 = FEM_OPERACION3.getString(_byteBuffer);
		}
		return femOperacion3;
	}

	public void setFemOperacion3(String femOperacion3) {
		if (FEM_OPERACION3.equals(this.femOperacion3, femOperacion3)) {
			return;
		}
		FEM_OPERACION3.putString(femOperacion3, _byteBuffer);
		this.femOperacion3 = femOperacion3;
	}

	public String getFemValor3() {
		if (femValor3 == null) {
			femValor3 = FEM_VALOR3.getString(_byteBuffer);
		}
		return femValor3;
	}

	public void setFemValor3(String femValor3) {
		if (FEM_VALOR3.equals(this.femValor3, femValor3)) {
			return;
		}
		FEM_VALOR3.putString(femValor3, _byteBuffer);
		this.femValor3 = femValor3;
	}

	public String getFemConta5() {
		if (femConta5 == null) {
			femConta5 = FEM_CONTA5.getString(_byteBuffer);
		}
		return femConta5;
	}

	public void setFemConta5(String femConta5) {
		if (FEM_CONTA5.equals(this.femConta5, femConta5)) {
			return;
		}
		FEM_CONTA5.putString(femConta5, _byteBuffer);
		this.femConta5 = femConta5;
	}

	public BigDecimal getSalcontable() {
		if (salcontable == null) {
			salcontable = SALCONTABLE.getBigDecimal(_byteBuffer);
		}
		return salcontable;
	}

	public void setSalcontable(BigDecimal salcontable) {
		if (SALCONTABLE.equals(this.salcontable, salcontable)) {
			return;
		}
		SALCONTABLE.putBigDecimal(salcontable, _byteBuffer);
		this.salcontable = salcontable;
	}

	public BigDecimal getSalretenido() {
		if (salretenido == null) {
			salretenido = SALRETENIDO.getBigDecimal(_byteBuffer);
		}
		return salretenido;
	}

	public void setSalretenido(BigDecimal salretenido) {
		if (SALRETENIDO.equals(this.salretenido, salretenido)) {
			return;
		}
		SALRETENIDO.putBigDecimal(salretenido, _byteBuffer);
		this.salretenido = salretenido;
	}

	public BigDecimal getImpLimCta() {
		if (impLimCta == null) {
			impLimCta = IMP_LIM_CTA.getBigDecimal(_byteBuffer);
		}
		return impLimCta;
	}

	public void setImpLimCta(BigDecimal impLimCta) {
		if (IMP_LIM_CTA.equals(this.impLimCta, impLimCta)) {
			return;
		}
		IMP_LIM_CTA.putBigDecimal(impLimCta, _byteBuffer);
		this.impLimCta = impLimCta;
	}

	public BigDecimal getImpLimCuenactu() {
		if (impLimCuenactu == null) {
			impLimCuenactu = IMP_LIM_CUENACTU.getBigDecimal(_byteBuffer);
		}
		return impLimCuenactu;
	}

	public void setImpLimCuenactu(BigDecimal impLimCuenactu) {
		if (IMP_LIM_CUENACTU.equals(this.impLimCuenactu, impLimCuenactu)) {
			return;
		}
		IMP_LIM_CUENACTU.putBigDecimal(impLimCuenactu, _byteBuffer);
		this.impLimCuenactu = impLimCuenactu;
	}

	public BigDecimal getImpLimDispocta() {
		if (impLimDispocta == null) {
			impLimDispocta = IMP_LIM_DISPOCTA.getBigDecimal(_byteBuffer);
		}
		return impLimDispocta;
	}

	public void setImpLimDispocta(BigDecimal impLimDispocta) {
		if (IMP_LIM_DISPOCTA.equals(this.impLimDispocta, impLimDispocta)) {
			return;
		}
		IMP_LIM_DISPOCTA.putBigDecimal(impLimDispocta, _byteBuffer);
		this.impLimDispocta = impLimDispocta;
	}

	public String getIndCondiPropu() {
		if (indCondiPropu == null) {
			indCondiPropu = IND_CONDI_PROPU.getString(_byteBuffer);
		}
		return indCondiPropu;
	}

	public void setIndCondiPropu(String indCondiPropu) {
		if (IND_CONDI_PROPU.equals(this.indCondiPropu, indCondiPropu)) {
			return;
		}
		IND_CONDI_PROPU.putString(indCondiPropu, _byteBuffer);
		this.indCondiPropu = indCondiPropu;
	}

	public boolean isEstandar_In_IndCondiPropu() {
		return getIndCondiPropu().equals(ESTANDAR_In_IND_CONDI_PROPU);
	}

	public boolean isEspecial() {
		return getIndCondiPropu().equals(ESPECIAL);
	}

	public boolean isParticular() {
		return getIndCondiPropu().equals(PARTICULAR);
	}

	public String getIndVarLiq() {
		if (indVarLiq == null) {
			indVarLiq = IND_VAR_LIQ.getString(_byteBuffer);
		}
		return indVarLiq;
	}

	public void setIndVarLiq(String indVarLiq) {
		if (IND_VAR_LIQ.equals(this.indVarLiq, indVarLiq)) {
			return;
		}
		IND_VAR_LIQ.putString(indVarLiq, _byteBuffer);
		this.indVarLiq = indVarLiq;
	}

	public boolean isNovariaciones_In_IndVarLiq() {
		return getIndVarLiq().equals(NOVARIACIONES_In_IND_VAR_LIQ);
	}

	public boolean isVariaciones_In_IndVarLiq() {
		return getIndVarLiq().equals(VARIACIONES_In_IND_VAR_LIQ);
	}

	public String getFemInicio() {
		if (femInicio == null) {
			femInicio = FEM_INICIO.getString(_byteBuffer);
		}
		return femInicio;
	}

	public void setFemInicio(String femInicio) {
		if (FEM_INICIO.equals(this.femInicio, femInicio)) {
			return;
		}
		FEM_INICIO.putString(femInicio, _byteBuffer);
		this.femInicio = femInicio;
	}

	public String getIndVarComi() {
		if (indVarComi == null) {
			indVarComi = IND_VAR_COMI.getString(_byteBuffer);
		}
		return indVarComi;
	}

	public void setIndVarComi(String indVarComi) {
		if (IND_VAR_COMI.equals(this.indVarComi, indVarComi)) {
			return;
		}
		IND_VAR_COMI.putString(indVarComi, _byteBuffer);
		this.indVarComi = indVarComi;
	}

	public boolean isNovariaciones_In_IndVarComi() {
		return getIndVarComi().equals(NOVARIACIONES_In_IND_VAR_COMI);
	}

	public boolean isVariaciones_In_IndVarComi() {
		return getIndVarComi().equals(VARIACIONES_In_IND_VAR_COMI);
	}

	public String getFemInicio2() {
		if (femInicio2 == null) {
			femInicio2 = FEM_INICIO2.getString(_byteBuffer);
		}
		return femInicio2;
	}

	public void setFemInicio2(String femInicio2) {
		if (FEM_INICIO2.equals(this.femInicio2, femInicio2)) {
			return;
		}
		FEM_INICIO2.putString(femInicio2, _byteBuffer);
		this.femInicio2 = femInicio2;
	}

	public int getIndSegpaqcon() {
		if (indSegpaqcon == null) {
			indSegpaqcon = new Integer(IND_SEGPAQCON.getInt(_byteBuffer));
		}
		return indSegpaqcon.intValue();
	}

	public void setIndSegpaqcon(int indSegpaqcon) {
		if (IND_SEGPAQCON.equals(this.indSegpaqcon, indSegpaqcon)) {
			return;
		}
		IND_SEGPAQCON.putInt(indSegpaqcon, _byteBuffer);
		this.indSegpaqcon = new Integer(indSegpaqcon);
	}

	public boolean isSinCondicEspec() {
		return getIndSegpaqcon() == SIN_CONDIC_ESPEC;
	}

	public boolean isCondicionSegme() {
		return getIndSegpaqcon() == CONDICION_SEGME;
	}

	public boolean isCondicionPaque() {
		return getIndSegpaqcon() == CONDICION_PAQUE;
	}

	public boolean isCondicionConve() {
		return getIndSegpaqcon() == CONDICION_CONVE;
	}

	public boolean isCondicionAmbit() {
		return getIndSegpaqcon() == CONDICION_AMBIT;
	}

	public String getCodSegMercado() {
		if (codSegMercado == null) {
			codSegMercado = COD_SEG_MERCADO.getString(_byteBuffer);
		}
		return codSegMercado;
	}

	public void setCodSegMercado(String codSegMercado) {
		if (COD_SEG_MERCADO.equals(this.codSegMercado, codSegMercado)) {
			return;
		}
		COD_SEG_MERCADO.putString(codSegMercado, _byteBuffer);
		this.codSegMercado = codSegMercado;
	}

	public String getCodPaquete() {
		if (codPaquete == null) {
			codPaquete = COD_PAQUETE.getString(_byteBuffer);
		}
		return codPaquete;
	}

	public void setCodPaquete(String codPaquete) {
		if (COD_PAQUETE.equals(this.codPaquete, codPaquete)) {
			return;
		}
		COD_PAQUETE.putString(codPaquete, _byteBuffer);
		this.codPaquete = codPaquete;
	}

	public String getCodConvEspec() {
		if (codConvEspec == null) {
			codConvEspec = COD_CONV_ESPEC.getString(_byteBuffer);
		}
		return codConvEspec;
	}

	public void setCodConvEspec(String codConvEspec) {
		if (COD_CONV_ESPEC.equals(this.codConvEspec, codConvEspec)) {
			return;
		}
		COD_CONV_ESPEC.putString(codConvEspec, _byteBuffer);
		this.codConvEspec = codConvEspec;
	}

	public String getCodCentro() {
		if (codCentro == null) {
			codCentro = COD_CENTRO.getString(_byteBuffer);
		}
		return codCentro;
	}

	public void setCodCentro(String codCentro) {
		if (COD_CENTRO.equals(this.codCentro, codCentro)) {
			return;
		}
		COD_CENTRO.putString(codCentro, _byteBuffer);
		this.codCentro = codCentro;
	}

	public String getIndDesautorizaciones() {
		if (indDesautorizaciones == null) {
			indDesautorizaciones = IND_DESAUTORIZACIONES.getString(_byteBuffer);
		}
		return indDesautorizaciones;
	}

	public void setIndDesautorizaciones(String indDesautorizaciones) {
		if (IND_DESAUTORIZACIONES.equals(this.indDesautorizaciones, indDesautorizaciones)) {
			return;
		}
		IND_DESAUTORIZACIONES.putString(indDesautorizaciones, _byteBuffer);
		this.indDesautorizaciones = indDesautorizaciones;
	}

	public boolean isNoDesautor() {
		return getIndDesautorizaciones().equals(NO_DESAUTOR);
	}

	public boolean isSiDesautor() {
		return getIndDesautorizaciones().equals(SI_DESAUTOR);
	}

	public String getIndRetenciones() {
		if (indRetenciones == null) {
			indRetenciones = IND_RETENCIONES.getString(_byteBuffer);
		}
		return indRetenciones;
	}

	public void setIndRetenciones(String indRetenciones) {
		if (IND_RETENCIONES.equals(this.indRetenciones, indRetenciones)) {
			return;
		}
		IND_RETENCIONES.putString(indRetenciones, _byteBuffer);
		this.indRetenciones = indRetenciones;
	}

	public boolean isNoReten() {
		return getIndRetenciones().equals(NO_RETEN);
	}

	public boolean isSiReten() {
		return getIndRetenciones().equals(SI_RETEN);
	}

	public String getIndAviso() {
		if (indAviso == null) {
			indAviso = IND_AVISO.getString(_byteBuffer);
		}
		return indAviso;
	}

	public void setIndAviso(String indAviso) {
		if (IND_AVISO.equals(this.indAviso, indAviso)) {
			return;
		}
		IND_AVISO.putString(indAviso, _byteBuffer);
		this.indAviso = indAviso;
	}

	public boolean isSinaviso() {
		return getIndAviso().equals(SINAVISO);
	}

	public boolean isConaviso() {
		return getIndAviso().equals(CONAVISO);
	}

	public String getIndOrdenPer() {
		if (indOrdenPer == null) {
			indOrdenPer = IND_ORDEN_PER.getString(_byteBuffer);
		}
		return indOrdenPer;
	}

	public void setIndOrdenPer(String indOrdenPer) {
		if (IND_ORDEN_PER.equals(this.indOrdenPer, indOrdenPer)) {
			return;
		}
		IND_ORDEN_PER.putString(indOrdenPer, _byteBuffer);
		this.indOrdenPer = indOrdenPer;
	}

	public boolean isNoOrdenPer() {
		return getIndOrdenPer().equals(NO_ORDEN_PER);
	}

	public boolean isSiOrdenPer() {
		return getIndOrdenPer().equals(SI_ORDEN_PER);
	}

	public String getIndServicios() {
		if (indServicios == null) {
			indServicios = IND_SERVICIOS.getString(_byteBuffer);
		}
		return indServicios;
	}

	public void setIndServicios(String indServicios) {
		if (IND_SERVICIOS.equals(this.indServicios, indServicios)) {
			return;
		}
		IND_SERVICIOS.putString(indServicios, _byteBuffer);
		this.indServicios = indServicios;
	}

	public boolean isNoServicios() {
		return getIndServicios().equals(NO_SERVICIOS);
	}

	public boolean isSiServicios() {
		return getIndServicios().equals(SI_SERVICIOS);
	}

	public String getIndCtasAsoc() {
		if (indCtasAsoc == null) {
			indCtasAsoc = IND_CTAS_ASOC.getString(_byteBuffer);
		}
		return indCtasAsoc;
	}

	public void setIndCtasAsoc(String indCtasAsoc) {
		if (IND_CTAS_ASOC.equals(this.indCtasAsoc, indCtasAsoc)) {
			return;
		}
		IND_CTAS_ASOC.putString(indCtasAsoc, _byteBuffer);
		this.indCtasAsoc = indCtasAsoc;
	}

	public boolean isNoCtasAsoc() {
		return getIndCtasAsoc().equals(NO_CTAS_ASOC);
	}

	public boolean isSiCtasAsoc() {
		return getIndCtasAsoc().equals(SI_CTAS_ASOC);
	}

	public String getIndDomici() {
		if (indDomici == null) {
			indDomici = IND_DOMICI.getString(_byteBuffer);
		}
		return indDomici;
	}

	public void setIndDomici(String indDomici) {
		if (IND_DOMICI.equals(this.indDomici, indDomici)) {
			return;
		}
		IND_DOMICI.putString(indDomici, _byteBuffer);
		this.indDomici = indDomici;
	}

	public boolean isNoDomici() {
		return getIndDomici().equals(NO_DOMICI);
	}

	public boolean isSiDomici() {
		return getIndDomici().equals(SI_DOMICI);
	}

	public String getIndCapIntereses() {
		if (indCapIntereses == null) {
			indCapIntereses = IND_CAP_INTERESES.getString(_byteBuffer);
		}
		return indCapIntereses;
	}

	public void setIndCapIntereses(String indCapIntereses) {
		if (IND_CAP_INTERESES.equals(this.indCapIntereses, indCapIntereses)) {
			return;
		}
		IND_CAP_INTERESES.putString(indCapIntereses, _byteBuffer);
		this.indCapIntereses = indCapIntereses;
	}

	public boolean isNoCapIntereses() {
		return getIndCapIntereses().equals(NO_CAP_INTERESES);
	}

	public boolean isSiCapIntereses() {
		return getIndCapIntereses().equals(SI_CAP_INTERESES);
	}

	public String getIndCondDisp() {
		if (indCondDisp == null) {
			indCondDisp = IND_COND_DISP.getString(_byteBuffer);
		}
		return indCondDisp;
	}

	public void setIndCondDisp(String indCondDisp) {
		if (IND_COND_DISP.equals(this.indCondDisp, indCondDisp)) {
			return;
		}
		IND_COND_DISP.putString(indCondDisp, _byteBuffer);
		this.indCondDisp = indCondDisp;
	}

	public boolean isNoCondDisp() {
		return getIndCondDisp().equals(NO_COND_DISP);
	}

	public boolean isSiCondDisp() {
		return getIndCondDisp().equals(SI_COND_DISP);
	}

	public String getIndLibPedida() {
		if (indLibPedida == null) {
			indLibPedida = IND_LIB_PEDIDA.getString(_byteBuffer);
		}
		return indLibPedida;
	}

	public void setIndLibPedida(String indLibPedida) {
		if (IND_LIB_PEDIDA.equals(this.indLibPedida, indLibPedida)) {
			return;
		}
		IND_LIB_PEDIDA.putString(indLibPedida, _byteBuffer);
		this.indLibPedida = indLibPedida;
	}

	public boolean isNoLibretaPedida() {
		return getIndLibPedida().equals(NO_LIBRETA_PEDIDA);
	}

	public boolean isSiLibretaPedida() {
		return getIndLibPedida().equals(SI_LIBRETA_PEDIDA);
	}

	public String getIndNivelSeguridad() {
		if (indNivelSeguridad == null) {
			indNivelSeguridad = IND_NIVEL_SEGURIDAD.getString(_byteBuffer);
		}
		return indNivelSeguridad;
	}

	public void setIndNivelSeguridad(String indNivelSeguridad) {
		if (IND_NIVEL_SEGURIDAD.equals(this.indNivelSeguridad, indNivelSeguridad)) {
			return;
		}
		IND_NIVEL_SEGURIDAD.putString(indNivelSeguridad, _byteBuffer);
		this.indNivelSeguridad = indNivelSeguridad;
	}

	public boolean isNoNivelSegur() {
		return getIndNivelSeguridad().equals(NO_NIVEL_SEGUR);
	}

	public boolean isSiNivelSegur() {
		return getIndNivelSeguridad().equals(SI_NIVEL_SEGUR);
	}

	public String getIndPerLiques() {
		if (indPerLiques == null) {
			indPerLiques = IND_PER_LIQUES.getString(_byteBuffer);
		}
		return indPerLiques;
	}

	public void setIndPerLiques(String indPerLiques) {
		if (IND_PER_LIQUES.equals(this.indPerLiques, indPerLiques)) {
			return;
		}
		IND_PER_LIQUES.putString(indPerLiques, _byteBuffer);
		this.indPerLiques = indPerLiques;
	}

	public boolean isNohay_In_IndPerLiques() {
		return getIndPerLiques().equals(NOHAY_In_IND_PER_LIQUES);
	}

	public boolean isEstandar_In_IndPerLiques() {
		return getIndPerLiques().equals(ESTANDAR_In_IND_PER_LIQUES);
	}

	public boolean isNoestandar_In_IndPerLiques() {
		return getIndPerLiques().equals(NOESTANDAR_In_IND_PER_LIQUES);
	}

	public String getFemInicio3() {
		if (femInicio3 == null) {
			femInicio3 = FEM_INICIO3.getString(_byteBuffer);
		}
		return femInicio3;
	}

	public void setFemInicio3(String femInicio3) {
		if (FEM_INICIO3.equals(this.femInicio3, femInicio3)) {
			return;
		}
		FEM_INICIO3.putString(femInicio3, _byteBuffer);
		this.femInicio3 = femInicio3;
	}

	public String getIndCarenciaLiq() {
		if (indCarenciaLiq == null) {
			indCarenciaLiq = IND_CARENCIA_LIQ.getString(_byteBuffer);
		}
		return indCarenciaLiq;
	}

	public void setIndCarenciaLiq(String indCarenciaLiq) {
		if (IND_CARENCIA_LIQ.equals(this.indCarenciaLiq, indCarenciaLiq)) {
			return;
		}
		IND_CARENCIA_LIQ.putString(indCarenciaLiq, _byteBuffer);
		this.indCarenciaLiq = indCarenciaLiq;
	}

	public boolean isNohay_In_IndCarenciaLiq() {
		return getIndCarenciaLiq().equals(NOHAY_In_IND_CARENCIA_LIQ);
	}

	public boolean isEstandar_In_IndCarenciaLiq() {
		return getIndCarenciaLiq().equals(ESTANDAR_In_IND_CARENCIA_LIQ);
	}

	public boolean isNoestandar_In_IndCarenciaLiq() {
		return getIndCarenciaLiq().equals(NOESTANDAR_In_IND_CARENCIA_LIQ);
	}

	public String getFemInicio5() {
		if (femInicio5 == null) {
			femInicio5 = FEM_INICIO5.getString(_byteBuffer);
		}
		return femInicio5;
	}

	public void setFemInicio5(String femInicio5) {
		if (FEM_INICIO5.equals(this.femInicio5, femInicio5)) {
			return;
		}
		FEM_INICIO5.putString(femInicio5, _byteBuffer);
		this.femInicio5 = femInicio5;
	}

	public String getIndPerRedlimes() {
		if (indPerRedlimes == null) {
			indPerRedlimes = IND_PER_REDLIMES.getString(_byteBuffer);
		}
		return indPerRedlimes;
	}

	public void setIndPerRedlimes(String indPerRedlimes) {
		if (IND_PER_REDLIMES.equals(this.indPerRedlimes, indPerRedlimes)) {
			return;
		}
		IND_PER_REDLIMES.putString(indPerRedlimes, _byteBuffer);
		this.indPerRedlimes = indPerRedlimes;
	}

	public boolean isNohay_In_IndPerRedlimes() {
		return getIndPerRedlimes().equals(NOHAY_In_IND_PER_REDLIMES);
	}

	public boolean isEstandar_In_IndPerRedlimes() {
		return getIndPerRedlimes().equals(ESTANDAR_In_IND_PER_REDLIMES);
	}

	public boolean isNoestandar_In_IndPerRedlimes() {
		return getIndPerRedlimes().equals(NOESTANDAR_In_IND_PER_REDLIMES);
	}

	public String getFemInicio4() {
		if (femInicio4 == null) {
			femInicio4 = FEM_INICIO4.getString(_byteBuffer);
		}
		return femInicio4;
	}

	public void setFemInicio4(String femInicio4) {
		if (FEM_INICIO4.equals(this.femInicio4, femInicio4)) {
			return;
		}
		FEM_INICIO4.putString(femInicio4, _byteBuffer);
		this.femInicio4 = femInicio4;
	}

	public String getIndCarenciaRed() {
		if (indCarenciaRed == null) {
			indCarenciaRed = IND_CARENCIA_RED.getString(_byteBuffer);
		}
		return indCarenciaRed;
	}

	public void setIndCarenciaRed(String indCarenciaRed) {
		if (IND_CARENCIA_RED.equals(this.indCarenciaRed, indCarenciaRed)) {
			return;
		}
		IND_CARENCIA_RED.putString(indCarenciaRed, _byteBuffer);
		this.indCarenciaRed = indCarenciaRed;
	}

	public boolean isNohay_In_IndCarenciaRed() {
		return getIndCarenciaRed().equals(NOHAY_In_IND_CARENCIA_RED);
	}

	public boolean isEstandar_In_IndCarenciaRed() {
		return getIndCarenciaRed().equals(ESTANDAR_In_IND_CARENCIA_RED);
	}

	public boolean isNoestandar_In_IndCarenciaRed() {
		return getIndCarenciaRed().equals(NOESTANDAR_In_IND_CARENCIA_RED);
	}

	public String getFemInicio6() {
		if (femInicio6 == null) {
			femInicio6 = FEM_INICIO6.getString(_byteBuffer);
		}
		return femInicio6;
	}

	public void setFemInicio6(String femInicio6) {
		if (FEM_INICIO6.equals(this.femInicio6, femInicio6)) {
			return;
		}
		FEM_INICIO6.putString(femInicio6, _byteBuffer);
		this.femInicio6 = femInicio6;
	}

	public String getIndPlaEst() {
		if (indPlaEst == null) {
			indPlaEst = IND_PLA_EST.getString(_byteBuffer);
		}
		return indPlaEst;
	}

	public void setIndPlaEst(String indPlaEst) {
		if (IND_PLA_EST.equals(this.indPlaEst, indPlaEst)) {
			return;
		}
		IND_PLA_EST.putString(indPlaEst, _byteBuffer);
		this.indPlaEst = indPlaEst;
	}

	public String getFemInicio7() {
		if (femInicio7 == null) {
			femInicio7 = FEM_INICIO7.getString(_byteBuffer);
		}
		return femInicio7;
	}

	public void setFemInicio7(String femInicio7) {
		if (FEM_INICIO7.equals(this.femInicio7, femInicio7)) {
			return;
		}
		FEM_INICIO7.putString(femInicio7, _byteBuffer);
		this.femInicio7 = femInicio7;
	}

	public String getCodNisegu() {
		if (codNisegu == null) {
			codNisegu = COD_NISEGU.getString(_byteBuffer);
		}
		return codNisegu;
	}

	public void setCodNisegu(String codNisegu) {
		if (COD_NISEGU.equals(this.codNisegu, codNisegu)) {
			return;
		}
		COD_NISEGU.putString(codNisegu, _byteBuffer);
		this.codNisegu = codNisegu;
	}

	public String getFemUltimaOpe4() {
		if (femUltimaOpe4 == null) {
			femUltimaOpe4 = FEM_ULTIMA_OPE4.getString(_byteBuffer);
		}
		return femUltimaOpe4;
	}

	public void setFemUltimaOpe4(String femUltimaOpe4) {
		if (FEM_ULTIMA_OPE4.equals(this.femUltimaOpe4, femUltimaOpe4)) {
			return;
		}
		FEM_ULTIMA_OPE4.putString(femUltimaOpe4, _byteBuffer);
		this.femUltimaOpe4 = femUltimaOpe4;
	}

	public String getFemUltimaOpe5() {
		if (femUltimaOpe5 == null) {
			femUltimaOpe5 = FEM_ULTIMA_OPE5.getString(_byteBuffer);
		}
		return femUltimaOpe5;
	}

	public void setFemUltimaOpe5(String femUltimaOpe5) {
		if (FEM_ULTIMA_OPE5.equals(this.femUltimaOpe5, femUltimaOpe5)) {
			return;
		}
		FEM_ULTIMA_OPE5.putString(femUltimaOpe5, _byteBuffer);
		this.femUltimaOpe5 = femUltimaOpe5;
	}

	public BigDecimal getImpDescubierto() {
		if (impDescubierto == null) {
			impDescubierto = IMP_DESCUBIERTO.getBigDecimal(_byteBuffer);
		}
		return impDescubierto;
	}

	public void setImpDescubierto(BigDecimal impDescubierto) {
		if (IMP_DESCUBIERTO.equals(this.impDescubierto, impDescubierto)) {
			return;
		}
		IMP_DESCUBIERTO.putBigDecimal(impDescubierto, _byteBuffer);
		this.impDescubierto = impDescubierto;
	}

	public String getIndManCarlireno() {
		if (indManCarlireno == null) {
			indManCarlireno = IND_MAN_CARLIRENO.getString(_byteBuffer);
		}
		return indManCarlireno;
	}

	public void setIndManCarlireno(String indManCarlireno) {
		if (IND_MAN_CARLIRENO.equals(this.indManCarlireno, indManCarlireno)) {
			return;
		}
		IND_MAN_CARLIRENO.putString(indManCarlireno, _byteBuffer);
		this.indManCarlireno = indManCarlireno;
	}

	public boolean isNoMttoCarenciaLiqRen() {
		return getIndManCarlireno().equals(NO_MTTO_CARENCIA_LIQ_REN);
	}

	public boolean isSiMttoCarenciaLiqRen() {
		return getIndManCarlireno().equals(SI_MTTO_CARENCIA_LIQ_REN);
	}

	public String getIndManCarrebreno() {
		if (indManCarrebreno == null) {
			indManCarrebreno = IND_MAN_CARREBRENO.getString(_byteBuffer);
		}
		return indManCarrebreno;
	}

	public void setIndManCarrebreno(String indManCarrebreno) {
		if (IND_MAN_CARREBRENO.equals(this.indManCarrebreno, indManCarrebreno)) {
			return;
		}
		IND_MAN_CARREBRENO.putString(indManCarrebreno, _byteBuffer);
		this.indManCarrebreno = indManCarrebreno;
	}

	public boolean isNoMttoCarencaiRebRen() {
		return getIndManCarrebreno().equals(NO_MTTO_CARENCAI_REB_REN);
	}

	public boolean isSiMttoCarencaiRebRen() {
		return getIndManCarrebreno().equals(SI_MTTO_CARENCAI_REB_REN);
	}

	public int getNumRenovEfec() {
		if (numRenovEfec == null) {
			numRenovEfec = new Integer(NUM_RENOV_EFEC.getInt(_byteBuffer));
		}
		return numRenovEfec.intValue();
	}

	public void setNumRenovEfec(int numRenovEfec) {
		if (NUM_RENOV_EFEC.equals(this.numRenovEfec, numRenovEfec)) {
			return;
		}
		NUM_RENOV_EFEC.putInt(numRenovEfec, _byteBuffer);
		this.numRenovEfec = new Integer(numRenovEfec);
	}

	public String getIndNumDiaRes() {
		if (indNumDiaRes == null) {
			indNumDiaRes = IND_NUM_DIA_RES.getString(_byteBuffer);
		}
		return indNumDiaRes;
	}

	public void setIndNumDiaRes(String indNumDiaRes) {
		if (IND_NUM_DIA_RES.equals(this.indNumDiaRes, indNumDiaRes)) {
			return;
		}
		IND_NUM_DIA_RES.putString(indNumDiaRes, _byteBuffer);
		this.indNumDiaRes = indNumDiaRes;
	}

	public boolean isCorto() {
		return getIndNumDiaRes().equals(CORTO);
	}

	public boolean isLargo() {
		return getIndNumDiaRes().equals(LARGO);
	}

	public String getCodSector() {
		if (codSector == null) {
			codSector = COD_SECTOR.getString(_byteBuffer);
		}
		return codSector;
	}

	public void setCodSector(String codSector) {
		if (COD_SECTOR.equals(this.codSector, codSector)) {
			return;
		}
		COD_SECTOR.putString(codSector, _byteBuffer);
		this.codSector = codSector;
	}

	public String getCodGarantia() {
		if (codGarantia == null) {
			codGarantia = COD_GARANTIA.getString(_byteBuffer);
		}
		return codGarantia;
	}

	public void setCodGarantia(String codGarantia) {
		if (COD_GARANTIA.equals(this.codGarantia, codGarantia)) {
			return;
		}
		COD_GARANTIA.putString(codGarantia, _byteBuffer);
		this.codGarantia = codGarantia;
	}

	public String getCodFinali() {
		if (codFinali == null) {
			codFinali = COD_FINALI.getString(_byteBuffer);
		}
		return codFinali;
	}

	public void setCodFinali(String codFinali) {
		if (COD_FINALI.equals(this.codFinali, codFinali)) {
			return;
		}
		COD_FINALI.putString(codFinali, _byteBuffer);
		this.codFinali = codFinali;
	}

	public String getIndComputable() {
		if (indComputable == null) {
			indComputable = IND_COMPUTABLE.getString(_byteBuffer);
		}
		return indComputable;
	}

	public void setIndComputable(String indComputable) {
		if (IND_COMPUTABLE.equals(this.indComputable, indComputable)) {
			return;
		}
		IND_COMPUTABLE.putString(indComputable, _byteBuffer);
		this.indComputable = indComputable;
	}

	public boolean isComputable() {
		return getIndComputable().equals(COMPUTABLE);
	}

	public boolean isNoComputable() {
		return getIndComputable().equals(NO_COMPUTABLE);
	}

	public String getCodTipProp() {
		if (codTipProp == null) {
			codTipProp = COD_TIP_PROP.getString(_byteBuffer);
		}
		return codTipProp;
	}

	public void setCodTipProp(String codTipProp) {
		if (COD_TIP_PROP.equals(this.codTipProp, codTipProp)) {
			return;
		}
		COD_TIP_PROP.putString(codTipProp, _byteBuffer);
		this.codTipProp = codTipProp;
	}

	public boolean isCreacion() {
		return getCodTipProp().equals(CREACION);
	}

	public boolean isDescubiertoExcedido() {
		return getCodTipProp().equals(DESCUBIERTO_EXCEDIDO);
	}

	public boolean isAplazamientoPago() {
		return getCodTipProp().equals(APLAZAMIENTO_PAGO);
	}

	public boolean isModifFuncionamiento() {
		return getCodTipProp().equals(MODIF_FUNCIONAMIENTO);
	}

	public boolean isModifIntervinientes() {
		return getCodTipProp().equals(MODIF_INTERVINIENTES);
	}

	public boolean isModifCondDisposicion() {
		return getCodTipProp().equals(MODIF_COND_DISPOSICION);
	}

	public boolean isCambiosSituacion() {
		return getCodTipProp().equals(CAMBIOS_SITUACION);
	}

	public boolean isRenovacion() {
		return getCodTipProp().equals(RENOVACION);
	}

	public boolean isPropuestaConjunta() {
		return getCodTipProp().equals(PROPUESTA_CONJUNTA);
	}

	public boolean isPropuestaModificacionPan() {
		return getCodTipProp().equals(PROPUESTA_MODIFICACION_PAN);
	}

	public String getFemPropu() {
		if (femPropu == null) {
			femPropu = FEM_PROPU.getString(_byteBuffer);
		}
		return femPropu;
	}

	public void setFemPropu(String femPropu) {
		if (FEM_PROPU.equals(this.femPropu, femPropu)) {
			return;
		}
		FEM_PROPU.putString(femPropu, _byteBuffer);
		this.femPropu = femPropu;
	}

	public String getFemAplicacion() {
		if (femAplicacion == null) {
			femAplicacion = FEM_APLICACION.getString(_byteBuffer);
		}
		return femAplicacion;
	}

	public void setFemAplicacion(String femAplicacion) {
		if (FEM_APLICACION.equals(this.femAplicacion, femAplicacion)) {
			return;
		}
		FEM_APLICACION.putString(femAplicacion, _byteBuffer);
		this.femAplicacion = femAplicacion;
	}

	public String getFemAplicacion2() {
		if (femAplicacion2 == null) {
			femAplicacion2 = FEM_APLICACION2.getString(_byteBuffer);
		}
		return femAplicacion2;
	}

	public void setFemAplicacion2(String femAplicacion2) {
		if (FEM_APLICACION2.equals(this.femAplicacion2, femAplicacion2)) {
			return;
		}
		FEM_APLICACION2.putString(femAplicacion2, _byteBuffer);
		this.femAplicacion2 = femAplicacion2;
	}

	public BigDecimal getImpcomision() {
		if (impcomision == null) {
			impcomision = IMPCOMISION.getBigDecimal(_byteBuffer);
		}
		return impcomision;
	}

	public void setImpcomision(BigDecimal impcomision) {
		if (IMPCOMISION.equals(this.impcomision, impcomision)) {
			return;
		}
		IMPCOMISION.putBigDecimal(impcomision, _byteBuffer);
		this.impcomision = impcomision;
	}

	public int getNumOpecanna() {
		if (numOpecanna == null) {
			numOpecanna = new Integer(NUM_OPECANNA.getInt(_byteBuffer));
		}
		return numOpecanna.intValue();
	}

	public void setNumOpecanna(int numOpecanna) {
		if (NUM_OPECANNA.equals(this.numOpecanna, numOpecanna)) {
			return;
		}
		NUM_OPECANNA.putInt(numOpecanna, _byteBuffer);
		this.numOpecanna = new Integer(numOpecanna);
	}

	public int getNumOpeabanna() {
		if (numOpeabanna == null) {
			numOpeabanna = new Integer(NUM_OPEABANNA.getInt(_byteBuffer));
		}
		return numOpeabanna.intValue();
	}

	public void setNumOpeabanna(int numOpeabanna) {
		if (NUM_OPEABANNA.equals(this.numOpeabanna, numOpeabanna)) {
			return;
		}
		NUM_OPEABANNA.putInt(numOpeabanna, _byteBuffer);
		this.numOpeabanna = new Integer(numOpeabanna);
	}

	public BigDecimal getImpOpcaanact() {
		if (impOpcaanact == null) {
			impOpcaanact = IMP_OPCAANACT.getBigDecimal(_byteBuffer);
		}
		return impOpcaanact;
	}

	public void setImpOpcaanact(BigDecimal impOpcaanact) {
		if (IMP_OPCAANACT.equals(this.impOpcaanact, impOpcaanact)) {
			return;
		}
		IMP_OPCAANACT.putBigDecimal(impOpcaanact, _byteBuffer);
		this.impOpcaanact = impOpcaanact;
	}

	public BigDecimal getImpOpabanact() {
		if (impOpabanact == null) {
			impOpabanact = IMP_OPABANACT.getBigDecimal(_byteBuffer);
		}
		return impOpabanact;
	}

	public void setImpOpabanact(BigDecimal impOpabanact) {
		if (IMP_OPABANACT.equals(this.impOpabanact, impOpabanact)) {
			return;
		}
		IMP_OPABANACT.putBigDecimal(impOpabanact, _byteBuffer);
		this.impOpabanact = impOpabanact;
	}

	public int getNumDiaDesAno() {
		if (numDiaDesAno == null) {
			numDiaDesAno = new Integer(NUM_DIA_DES_ANO.getInt(_byteBuffer));
		}
		return numDiaDesAno.intValue();
	}

	public void setNumDiaDesAno(int numDiaDesAno) {
		if (NUM_DIA_DES_ANO.equals(this.numDiaDesAno, numDiaDesAno)) {
			return;
		}
		NUM_DIA_DES_ANO.putInt(numDiaDesAno, _byteBuffer);
		this.numDiaDesAno = new Integer(numDiaDesAno);
	}

	public String getFemInicio9() {
		if (femInicio9 == null) {
			femInicio9 = FEM_INICIO9.getString(_byteBuffer);
		}
		return femInicio9;
	}

	public void setFemInicio9(String femInicio9) {
		if (FEM_INICIO9.equals(this.femInicio9, femInicio9)) {
			return;
		}
		FEM_INICIO9.putString(femInicio9, _byteBuffer);
		this.femInicio9 = femInicio9;
	}

	public String getIndTasAjusAc() {
		if (indTasAjusAc == null) {
			indTasAjusAc = IND_TAS_AJUS_AC.getString(_byteBuffer);
		}
		return indTasAjusAc;
	}

	public void setIndTasAjusAc(String indTasAjusAc) {
		if (IND_TAS_AJUS_AC.equals(this.indTasAjusAc, indTasAjusAc)) {
			return;
		}
		IND_TAS_AJUS_AC.putString(indTasAjusAc, _byteBuffer);
		this.indTasAjusAc = indTasAjusAc;
	}

	public String getFemInicio10() {
		if (femInicio10 == null) {
			femInicio10 = FEM_INICIO10.getString(_byteBuffer);
		}
		return femInicio10;
	}

	public void setFemInicio10(String femInicio10) {
		if (FEM_INICIO10.equals(this.femInicio10, femInicio10)) {
			return;
		}
		FEM_INICIO10.putString(femInicio10, _byteBuffer);
		this.femInicio10 = femInicio10;
	}

	public String getIndTasAjusDe() {
		if (indTasAjusDe == null) {
			indTasAjusDe = IND_TAS_AJUS_DE.getString(_byteBuffer);
		}
		return indTasAjusDe;
	}

	public void setIndTasAjusDe(String indTasAjusDe) {
		if (IND_TAS_AJUS_DE.equals(this.indTasAjusDe, indTasAjusDe)) {
			return;
		}
		IND_TAS_AJUS_DE.putString(indTasAjusDe, _byteBuffer);
		this.indTasAjusDe = indTasAjusDe;
	}

	public String getIndCar01Est() {
		if (indCar01Est == null) {
			indCar01Est = IND_CAR01_EST.getString(_byteBuffer);
		}
		return indCar01Est;
	}

	public void setIndCar01Est(String indCar01Est) {
		if (IND_CAR01_EST.equals(this.indCar01Est, indCar01Est)) {
			return;
		}
		IND_CAR01_EST.putString(indCar01Est, _byteBuffer);
		this.indCar01Est = indCar01Est;
	}

	public String getFemCaract01() {
		if (femCaract01 == null) {
			femCaract01 = FEM_CARACT01.getString(_byteBuffer);
		}
		return femCaract01;
	}

	public void setFemCaract01(String femCaract01) {
		if (FEM_CARACT01.equals(this.femCaract01, femCaract01)) {
			return;
		}
		FEM_CARACT01.putString(femCaract01, _byteBuffer);
		this.femCaract01 = femCaract01;
	}

	public String getFemConta3() {
		if (femConta3 == null) {
			femConta3 = FEM_CONTA3.getString(_byteBuffer);
		}
		return femConta3;
	}

	public void setFemConta3(String femConta3) {
		if (FEM_CONTA3.equals(this.femConta3, femConta3)) {
			return;
		}
		FEM_CONTA3.putString(femConta3, _byteBuffer);
		this.femConta3 = femConta3;
	}

	public String getCodTipInteres() {
		if (codTipInteres == null) {
			codTipInteres = COD_TIP_INTERES.getString(_byteBuffer);
		}
		return codTipInteres;
	}

	public void setCodTipInteres(String codTipInteres) {
		if (COD_TIP_INTERES.equals(this.codTipInteres, codTipInteres)) {
			return;
		}
		COD_TIP_INTERES.putString(codTipInteres, _byteBuffer);
		this.codTipInteres = codTipInteres;
	}

	public boolean isFijo() {
		return getCodTipInteres().equals(FIJO);
	}

	public boolean isVariable() {
		return getCodTipInteres().equals(VARIABLE);
	}

	public String getCodAnDoc() {
		if (codAnDoc == null) {
			codAnDoc = COD_AN_DOC.getString(_byteBuffer);
		}
		return codAnDoc;
	}

	public void setCodAnDoc(String codAnDoc) {
		if (COD_AN_DOC.equals(this.codAnDoc, codAnDoc)) {
			return;
		}
		COD_AN_DOC.putString(codAnDoc, _byteBuffer);
		this.codAnDoc = codAnDoc;
	}

	public String getTimestampSiglom() {
		if (timestampSiglom == null) {
			timestampSiglom = TIMESTAMP_SIGLOM.getString(_byteBuffer);
		}
		return timestampSiglom;
	}

	public void setTimestampSiglom(String timestampSiglom) {
		if (TIMESTAMP_SIGLOM.equals(this.timestampSiglom, timestampSiglom)) {
			return;
		}
		TIMESTAMP_SIGLOM.putString(timestampSiglom, _byteBuffer);
		this.timestampSiglom = timestampSiglom;
	}

	public String getCodUsuModif() {
		if (codUsuModif == null) {
			codUsuModif = COD_USU_MODIF.getString(_byteBuffer);
		}
		return codUsuModif;
	}

	public void setCodUsuModif(String codUsuModif) {
		if (COD_USU_MODIF.equals(this.codUsuModif, codUsuModif)) {
			return;
		}
		COD_USU_MODIF.putString(codUsuModif, _byteBuffer);
		this.codUsuModif = codUsuModif;
	}

	public int getCodDominio() {
		if (codDominio == null) {
			codDominio = new Integer(COD_DOMINIO.getInt(_byteBuffer));
		}
		return codDominio.intValue();
	}

	public void setCodDominio(int codDominio) {
		if (COD_DOMINIO.equals(this.codDominio, codDominio)) {
			return;
		}
		COD_DOMINIO.putInt(codDominio, _byteBuffer);
		this.codDominio = new Integer(codDominio);
	}

	public int getNumNodo() {
		if (numNodo == null) {
			numNodo = new Integer(NUM_NODO.getInt(_byteBuffer));
		}
		return numNodo.intValue();
	}

	public void setNumNodo(int numNodo) {
		if (NUM_NODO.equals(this.numNodo, numNodo)) {
			return;
		}
		NUM_NODO.putInt(numNodo, _byteBuffer);
		this.numNodo = new Integer(numNodo);
	}

	public String getIndModTabla() {
		if (indModTabla == null) {
			indModTabla = IND_MOD_TABLA.getString(_byteBuffer);
		}
		return indModTabla;
	}

	public void setIndModTabla(String indModTabla) {
		if (IND_MOD_TABLA.equals(this.indModTabla, indModTabla)) {
			return;
		}
		IND_MOD_TABLA.putString(indModTabla, _byteBuffer);
		this.indModTabla = indModTabla;
	}

	public String getCodMsjeRetorno() {
		if (codMsjeRetorno == null) {
			codMsjeRetorno = COD_MSJE_RETORNO.getString(_byteBuffer);
		}
		return codMsjeRetorno;
	}

	public void setCodMsjeRetorno(String codMsjeRetorno) {
		if (COD_MSJE_RETORNO.equals(this.codMsjeRetorno, codMsjeRetorno)) {
			return;
		}
		COD_MSJE_RETORNO.putString(codMsjeRetorno, _byteBuffer);
		this.codMsjeRetorno = codMsjeRetorno;
	}

}
