package com.sample.ejb.bean;

import com.ibm.jzos.fields.BinaryAsIntField;
import com.ibm.jzos.fields.CobolDatatypeFactory;
import com.ibm.jzos.fields.ExternalDecimalAsIntField;
import com.ibm.jzos.fields.PackedDecimalAsBigDecimalField;
import com.ibm.jzos.fields.PackedDecimalAsIntField;
import com.ibm.jzos.fields.PackedDecimalAsLongField;
import com.ibm.jzos.fields.StringField;
import java.math.BigDecimal;

// Generated by com.ibm.jzos.recordgen.cobol.RecordClassGenerator on Wed Feb 05 14:37:34 CET 2020

public class CT30X015CommareaWrapper1 {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 

	/** <pre>
	 01  CT30X015-01. </pre> */
	public static final int CT30X015_01_len = 702; 

	/** <pre>
	*---TESTATA DI TUTTI I TRACCIATI
	   02  WLXAXMLP-RETURN-CODE            PIC X(2). </pre> */
	protected static final StringField WLXAXMLP_RETURN_CODE = factory.getStringField(2);

	/** <pre>
	   02  WLXAXMLP-REASON-CODE            PIC X(8). </pre> */
	protected static final StringField WLXAXMLP_REASON_CODE = factory.getStringField(8);

	/** <pre>
	   02  WLXAXMLP-DESCRIZIONE            PIC X(128). </pre> */
	protected static final StringField WLXAXMLP_DESCRIZIONE = factory.getStringField(128);

	/** <pre>
	   02  WLXAXMLP-SESSION-HANDLE         PIC X(26). </pre> */
	protected static final StringField WLXAXMLP_SESSION_HANDLE = factory.getStringField(26);

	/** <pre>
	   02  WLXAXMLP-DATI-AMBI-IMM. </pre> */
	public static final int WLXAXMLP_DATI_AMBI_IMM_len = 109; 
	public static final int WLXAXMLP_DATI_AMBI_IMM_offset = factory.getOffset();

	/** <pre>
	     03  WLXAXMLP-SYSID                PIC X(8). </pre> */
	protected static final StringField WLXAXMLP_SYSID = factory.getStringField(8);

	/** <pre>
	     03  WLXAXMLP-TRANSAZIONE          PIC X(8). </pre> */
	protected static final StringField WLXAXMLP_TRANSAZIONE = factory.getStringField(8);

	/** <pre>
	     03  WLXAXMLP-PROGRAMMA            PIC X(8). </pre> */
	protected static final StringField WLXAXMLP_PROGRAMMA = factory.getStringField(8);

	/** <pre>
	     03  WLXAXMLP-PROCEDURA            PIC X(2). </pre> */
	protected static final StringField WLXAXMLP_PROCEDURA = factory.getStringField(2);

	/** <pre>
	     03  WLXAXMLP-CANALE               PIC X(3). </pre> */
	protected static final StringField WLXAXMLP_CANALE = factory.getStringField(3);

	/** <pre>
	     03  WLXAXMLP-DATI-ISTITUTO. </pre> */
	public static final int WLXAXMLP_DATI_ISTITUTO_len = 10; 
	public static final int WLXAXMLP_DATI_ISTITUTO_offset = factory.getOffset();

	/** <pre>
	       04  WLXAXMLP-ISTITUTO           PIC X(5). </pre> */
	protected static final StringField WLXAXMLP_ISTITUTO = factory.getStringField(5);

	/** <pre>
	       04  WLXAXMLP-ABI-ISTITUTO       PIC X(5). </pre> */
	protected static final StringField WLXAXMLP_ABI_ISTITUTO = factory.getStringField(5);

	/** <pre>
	     03  WLXAXMLP-DATI-ENTE. </pre> */
	public static final int WLXAXMLP_DATI_ENTE_len = 13; 
	public static final int WLXAXMLP_DATI_ENTE_offset = factory.getOffset();

	/** <pre>
	       04  WLXAXMLP-ENTE               PIC X(5). </pre> */
	protected static final StringField WLXAXMLP_ENTE = factory.getStringField(5);

	/** <pre>
	       04  WLXAXMLP-TIP-ENTE           PIC X(1). </pre> */
	protected static final StringField WLXAXMLP_TIP_ENTE = factory.getStringField(1);

	/** <pre>
	       04  WLXAXMLP-SUB-ENTE           PIC X(2). </pre> */
	protected static final StringField WLXAXMLP_SUB_ENTE = factory.getStringField(2);

	/** <pre>
	       04  WLXAXMLP-CAB                PIC X(5). </pre> */
	protected static final StringField WLXAXMLP_CAB = factory.getStringField(5);

	/** <pre>
	     03  WLXAXMLP-UFFICIO              PIC X(4). </pre> */
	protected static final StringField WLXAXMLP_UFFICIO = factory.getStringField(4);

	/** <pre>
	     03  WLXAXMLP-SEZIONE              PIC X(2). </pre> */
	protected static final StringField WLXAXMLP_SEZIONE = factory.getStringField(2);

	/** <pre>
	     03  WLXAXMLP-TERM                 PIC X(8). </pre> */
	protected static final StringField WLXAXMLP_TERM = factory.getStringField(8);

	/** <pre>
	     03  WLXAXMLP-OPE                  PIC X(8). </pre> */
	protected static final StringField WLXAXMLP_OPE = factory.getStringField(8);

	/** <pre>
	     03  WLXAXMLP-DAT                  PIC 9(8). </pre> */
	protected static final ExternalDecimalAsIntField WLXAXMLP_DAT = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	     03  WLXAXMLP-ORA                  PIC 9(6). </pre> */
	protected static final ExternalDecimalAsIntField WLXAXMLP_ORA = factory.getExternalDecimalAsIntField(6, false, false, false, false);

	/** <pre>
	     03  WLXAXMLP-ENTE-CONTABILE. </pre> */
	public static final int WLXAXMLP_ENTE_CONTABILE_len = 13; 
	public static final int WLXAXMLP_ENTE_CONTABILE_offset = factory.getOffset();

	/** <pre>
	       04  WLXAXMLP-ENTE-CONT          PIC X(5). </pre> */
	protected static final StringField WLXAXMLP_ENTE_CONT = factory.getStringField(5);

	/** <pre>
	       04  WLXAXMLP-TIP-ENTE-CONT      PIC X(1). </pre> */
	protected static final StringField WLXAXMLP_TIP_ENTE_CONT = factory.getStringField(1);

	/** <pre>
	       04  WLXAXMLP-SUB-ENTE-CONT      PIC X(2). </pre> */
	protected static final StringField WLXAXMLP_SUB_ENTE_CONT = factory.getStringField(2);

	/** <pre>
	       04  WLXAXMLP-CAB-CONT           PIC X(5). </pre> */
	protected static final StringField WLXAXMLP_CAB_CONT = factory.getStringField(5);

	/** <pre>
	     03  WLXAXMLP-DAT-CONTABILE        PIC 9(8). </pre> */
	protected static final ExternalDecimalAsIntField WLXAXMLP_DAT_CONTABILE = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	*---DATI SECNEW CONTEXT
	   02 SECNEW-CONTEXT. </pre> */
	public static final int SECNEW_CONTEXT_len = 22; 
	public static final int SECNEW_CONTEXT_offset = factory.getOffset();

	/** <pre>
	     03 CT30X015-REUS-ATT-I. </pre> */
	public static final int CT30X015_REUS_ATT_I_len = 22; 
	public static final int CT30X015_REUS_ATT_I_offset = factory.getOffset();

	/** <pre>
	      04 CT30X015-DOMINIO-I PIC X(4). </pre> */
	protected static final StringField CT30X015_DOMINIO_I = factory.getStringField(4);

	/** <pre>
	      04 CT30X015-NODO-I PIC X(4). </pre> */
	protected static final StringField CT30X015_NODO_I = factory.getStringField(4);

	/** <pre>
	      04 CT30X015-POSTAZIONE-I PIC S9(9) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField CT30X015_POSTAZIONE_I = factory.getPackedDecimalAsIntField(9, true);

	/** <pre>
	      04 CT30X015-CENTRO-I PIC X(4). </pre> */
	protected static final StringField CT30X015_CENTRO_I = factory.getStringField(4);

	/** <pre>
	      04 CT30X015-NUM-MESSAGGIO-I PIC S9(9) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField CT30X015_NUM_MESSAGGIO_I = factory.getPackedDecimalAsIntField(9, true);

	/** <pre>
	*---DATI INPUT/OUTPUT
	   02 CT30X015-DATA. </pre> */
	public static final int CT30X015_DATA_len = 407; 
	public static final int CT30X015_DATA_offset = factory.getOffset();

	/** <pre>
	     03 CT30X015-ACC-SRV-I PIC X(1). </pre> */
	protected static final StringField CT30X015_ACC_SRV_I = factory.getStringField(1);

	/** <pre>
	     03 CT30X015-COD-DELEGATO-I. </pre> */
	public static final int CT30X015_COD_DELEGATO_I_len = 5; 
	public static final int CT30X015_COD_DELEGATO_I_offset = factory.getOffset();

	/** <pre>
	      04 CT30X015-VALORE-I PIC S9(9) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField CT30X015_VALORE_I = factory.getPackedDecimalAsIntField(9, true);

	/** <pre>
	     03 CT30X015-CC-MOV-OLD-I. </pre> */
	public static final int CT30X015_CC_MOV_OLD_I_len = 10; 
	public static final int CT30X015_CC_MOV_OLD_I_offset = factory.getOffset();

	/** <pre>
	      04 CT30X015-CODSRVSEC-I PIC S9(2) COMP. </pre> */
	protected static final BinaryAsIntField CT30X015_CODSRVSEC_I = factory.getBinaryAsIntField(2, true);

	/** <pre>
	      04 CT30X015-CODFILSEC-I PIC S9(3) COMP. </pre> */
	protected static final BinaryAsIntField CT30X015_CODFILSEC_I = factory.getBinaryAsIntField(3, true);

	/** <pre>
	      04 CT30X015-CODCATSEC-I PIC S9(2) COMP. </pre> */
	protected static final BinaryAsIntField CT30X015_CODCATSEC_I = factory.getBinaryAsIntField(2, true);

	/** <pre>
	      04 CT30X015-NUMPARTSEC-I PIC S9(7) COMP. </pre> */
	protected static final BinaryAsIntField CT30X015_NUMPARTSEC_I = factory.getBinaryAsIntField(7, true);

	/** <pre>
	     03 CT30X015-CC-MOV-NEW-I. </pre> */
	public static final int CT30X015_CC_MOV_NEW_I_len = 7; 
	public static final int CT30X015_CC_MOV_NEW_I_offset = factory.getOffset();

	/** <pre>
	      04 CT30X015-COD-TIP-EXPE-I PIC X(2). </pre> */
	protected static final StringField CT30X015_COD_TIP_EXPE_I = factory.getStringField(2);

	/** <pre>
	      04 CT30X015-NUM-CTA-INT-I PIC S9(8) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField CT30X015_NUM_CTA_INT_I = factory.getPackedDecimalAsIntField(8, true);

	/** <pre>
	     03 CT30X015-MOVIMENTO-I. </pre> */
	public static final int CT30X015_MOVIMENTO_I_len = 224; 
	public static final int CT30X015_MOVIMENTO_I_offset = factory.getOffset();

	/** <pre>
	      04 CT30X015-COD-OPERACION-I PIC X(5). </pre> */
	protected static final StringField CT30X015_COD_OPERACION_I = factory.getStringField(5);

	/** <pre>
	      04 CT30X015-COD-REFER-I PIC X(4). </pre> */
	protected static final StringField CT30X015_COD_REFER_I = factory.getStringField(4);

	/** <pre>
	      04 CT30X015-COD-REFERENCIA-OPE-I PIC X(6). </pre> */
	protected static final StringField CT30X015_COD_REFERENCIA_OPE_I = factory.getStringField(6);

	/** <pre>
	      04 CT30X015-TXT-MOVIMENTO-I PIC X(120). </pre> */
	protected static final StringField CT30X015_TXT_MOVIMENTO_I = factory.getStringField(120);

	/** <pre>
	      04 CT30X015-IND-NATURALEZA-I PIC X(1). </pre> */
	protected static final StringField CT30X015_IND_NATURALEZA_I = factory.getStringField(1);

	/** <pre>
	      04 CT30X015-IND-PAGO-EFEC-I PIC X(1). </pre> */
	protected static final StringField CT30X015_IND_PAGO_EFEC_I = factory.getStringField(1);

	/** <pre>
	      04 CT30X015-FEC-CONTABLE-I PIC X(10). </pre> */
	protected static final StringField CT30X015_FEC_CONTABLE_I = factory.getStringField(10);

	/** <pre>
	      04 CT30X015-FEC-VALOR-I PIC X(10). </pre> */
	protected static final StringField CT30X015_FEC_VALOR_I = factory.getStringField(10);

	/** <pre>
	      04 CT30X015-FEC-DISPONIBILITA-I PIC X(10). </pre> */
	protected static final StringField CT30X015_FEC_DISPONIBILITA_I = factory.getStringField(10);

	/** <pre>
	      04 CT30X015-FEC-OPERACION-I PIC X(10). </pre> */
	protected static final StringField CT30X015_FEC_OPERACION_I = factory.getStringField(10);

	/** <pre>
	      04 CT30X015-COD-PROC-ORIG-I PIC X(4). </pre> */
	protected static final StringField CT30X015_COD_PROC_ORIG_I = factory.getStringField(4);

	/** <pre>
	      04 CT30X015-COD-CANALE-I PIC X(3). </pre> */
	protected static final StringField CT30X015_COD_CANALE_I = factory.getStringField(3);

	/** <pre>
	      04 CT30X015-IMP-MOVIMIENTO-I. </pre> */
	public static final int CT30X015_IMP_MOVIMIENTO_I_len = 9; 
	public static final int CT30X015_IMP_MOVIMIENTO_I_offset = factory.getOffset();

	/** <pre>
	       05 CT30X015-TOTALE-EURO-I PIC S9(15)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField CT30X015_TOTALE_EURO_I = factory.getPackedDecimalAsBigDecimalField(17, 2, true);

	/** <pre>
	      04 CT30X015-IMP-COMMISSIONI-I. </pre> */
	public static final int CT30X015_IMP_COMMISSIONI_I_len = 9; 
	public static final int CT30X015_IMP_COMMISSIONI_I_offset = factory.getOffset();

	/** <pre>
	       05 CT30X015-CM-TOTALE-EURO-I PIC S9(15)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField CT30X015_CM_TOTALE_EURO_I = factory.getPackedDecimalAsBigDecimalField(17, 2, true);

	/** <pre>
	      04 CT30X015-IMP-SPESE-I. </pre> */
	public static final int CT30X015_IMP_SPESE_I_len = 9; 
	public static final int CT30X015_IMP_SPESE_I_offset = factory.getOffset();

	/** <pre>
	       05 CT30X015-SP-TOTALE-EURO-I PIC S9(15)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField CT30X015_SP_TOTALE_EURO_I = factory.getPackedDecimalAsBigDecimalField(17, 2, true);

	/** <pre>
	      04 CT30X015-IMP-SPESE-RECLAM-I. </pre> */
	public static final int CT30X015_IMP_SPESE_RECLAM_I_len = 9; 
	public static final int CT30X015_IMP_SPESE_RECLAM_I_offset = factory.getOffset();

	/** <pre>
	       05 CT30X015-SR-TOTALE-EURO-I PIC S9(15)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField CT30X015_SR_TOTALE_EURO_I = factory.getPackedDecimalAsBigDecimalField(17, 2, true);

	/** <pre>
	      04 CT30X015-COD-PROD-I PIC X(4). </pre> */
	protected static final StringField CT30X015_COD_PROD_I = factory.getStringField(4);

	/** <pre>
	     03 CT30X015-MOVIMENTO-OUT-O. </pre> */
	public static final int CT30X015_MOVIMENTO_OUT_O_len = 160; 
	public static final int CT30X015_MOVIMENTO_OUT_O_offset = factory.getOffset();

	/** <pre>
	      04 CT30X015-NUM-OPERACION-O PIC S9(10) COMP-3. </pre> */
	protected static final PackedDecimalAsLongField CT30X015_NUM_OPERACION_O = factory.getPackedDecimalAsLongField(10, true);

	/** <pre>
	      04 CT30X015-SALCONTABLE-O. </pre> */
	public static final int CT30X015_SALCONTABLE_O_len = 9; 
	public static final int CT30X015_SALCONTABLE_O_offset = factory.getOffset();

	/** <pre>
	       05 CT30X015-SC-TOTALE-EURO-O PIC S9(15)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField CT30X015_SC_TOTALE_EURO_O = factory.getPackedDecimalAsBigDecimalField(17, 2, true);

	/** <pre>
	      04 CT30X015-SALRETENIDO-O. </pre> */
	public static final int CT30X015_SALRETENIDO_O_len = 9; 
	public static final int CT30X015_SALRETENIDO_O_offset = factory.getOffset();

	/** <pre>
	       05 CT30X015-SN-TOTALE-EURO-O PIC S9(15)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField CT30X015_SN_TOTALE_EURO_O = factory.getPackedDecimalAsBigDecimalField(17, 2, true);

	/** <pre>
	      04 CT30X015-NUM-UTL-MOV-O PIC S9(7) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField CT30X015_NUM_UTL_MOV_O = factory.getPackedDecimalAsIntField(7, true);

	/** <pre>
	      04 CT30X015-IMP-DESCUBIERTO-O. </pre> */
	public static final int CT30X015_IMP_DESCUBIERTO_O_len = 9; 
	public static final int CT30X015_IMP_DESCUBIERTO_O_offset = factory.getOffset();

	/** <pre>
	       05 CT30X015-IS-TOTALE-EURO-O PIC S9(15)V9(2) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField CT30X015_IS_TOTALE_EURO_O = factory.getPackedDecimalAsBigDecimalField(17, 2, true);

	/** <pre>
	      04 CT30X015-COD-ERR-O PIC S9(5) COMP-3. </pre> */
	protected static final PackedDecimalAsIntField CT30X015_COD_ERR_O = factory.getPackedDecimalAsIntField(5, true);

	/** <pre>
	      04 CT30X015-DESC-ERRORE-O PIC X(120). </pre> */
	protected static final StringField CT30X015_DESC_ERRORE_O = factory.getStringField(120);

	protected byte[] _byteBuffer;
	// Instance variables used to cache field values
	protected String wlxaxmlpReturnCode;
	protected String wlxaxmlpReasonCode;
	protected String wlxaxmlpDescrizione;
	protected String wlxaxmlpSessionHandle;
	protected String wlxaxmlpSysid;
	protected String wlxaxmlpTransazione;
	protected String wlxaxmlpProgramma;
	protected String wlxaxmlpProcedura;
	protected String wlxaxmlpCanale;
	protected String wlxaxmlpIstituto;
	protected String wlxaxmlpAbiIstituto;
	protected String wlxaxmlpEnte;
	protected String wlxaxmlpTipEnte;
	protected String wlxaxmlpSubEnte;
	protected String wlxaxmlpCab;
	protected String wlxaxmlpUfficio;
	protected String wlxaxmlpSezione;
	protected String wlxaxmlpTerm;
	protected String wlxaxmlpOpe;
	protected Integer wlxaxmlpDat;
	protected Integer wlxaxmlpOra;
	protected String wlxaxmlpEnteCont;
	protected String wlxaxmlpTipEnteCont;
	protected String wlxaxmlpSubEnteCont;
	protected String wlxaxmlpCabCont;
	protected Integer wlxaxmlpDatContabile;
	protected String ct30x015DominioI;
	protected String ct30x015NodoI;
	protected Integer ct30x015PostazioneI;
	protected String ct30x015CentroI;
	protected Integer ct30x015NumMessaggioI;
	protected String ct30x015AccSrvI;
	protected Integer ct30x015ValoreI;
	protected Integer ct30x015CodsrvsecI;
	protected Integer ct30x015CodfilsecI;
	protected Integer ct30x015CodcatsecI;
	protected Integer ct30x015NumpartsecI;
	protected String ct30x015CodTipExpeI;
	protected Integer ct30x015NumCtaIntI;
	protected String ct30x015CodOperacionI;
	protected String ct30x015CodReferI;
	protected String ct30x015CodReferenciaOpeI;
	protected String ct30x015TxtMovimentoI;
	protected String ct30x015IndNaturalezaI;
	protected String ct30x015IndPagoEfecI;
	protected String ct30x015FecContableI;
	protected String ct30x015FecValorI;
	protected String ct30x015FecDisponibilitaI;
	protected String ct30x015FecOperacionI;
	protected String ct30x015CodProcOrigI;
	protected String ct30x015CodCanaleI;
	protected BigDecimal ct30x015TotaleEuroI;
	protected BigDecimal ct30x015CmTotaleEuroI;
	protected BigDecimal ct30x015SpTotaleEuroI;
	protected BigDecimal ct30x015SrTotaleEuroI;
	protected String ct30x015CodProdI;
	protected Long ct30x015NumOperacionO;
	protected BigDecimal ct30x015ScTotaleEuroO;
	protected BigDecimal ct30x015SnTotaleEuroO;
	protected Integer ct30x015NumUtlMovO;
	protected BigDecimal ct30x015IsTotaleEuroO;
	protected Integer ct30x015CodErrO;
	protected String ct30x015DescErroreO;


	public CT30X015CommareaWrapper1 (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public CT30X015CommareaWrapper1 () {
		this._byteBuffer = new byte[CT30X015_01_len];
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public String getWlxaxmlpReturnCode() {
		if (wlxaxmlpReturnCode == null) {
			wlxaxmlpReturnCode = WLXAXMLP_RETURN_CODE.getString(_byteBuffer);
		}
		return wlxaxmlpReturnCode;
	}

	public void setWlxaxmlpReturnCode(String wlxaxmlpReturnCode) {
		if (WLXAXMLP_RETURN_CODE.equals(this.wlxaxmlpReturnCode, wlxaxmlpReturnCode)) {
			return;
		}
		WLXAXMLP_RETURN_CODE.putString(wlxaxmlpReturnCode, _byteBuffer);
		this.wlxaxmlpReturnCode = wlxaxmlpReturnCode;
	}

	public String getWlxaxmlpReasonCode() {
		if (wlxaxmlpReasonCode == null) {
			wlxaxmlpReasonCode = WLXAXMLP_REASON_CODE.getString(_byteBuffer);
		}
		return wlxaxmlpReasonCode;
	}

	public void setWlxaxmlpReasonCode(String wlxaxmlpReasonCode) {
		if (WLXAXMLP_REASON_CODE.equals(this.wlxaxmlpReasonCode, wlxaxmlpReasonCode)) {
			return;
		}
		WLXAXMLP_REASON_CODE.putString(wlxaxmlpReasonCode, _byteBuffer);
		this.wlxaxmlpReasonCode = wlxaxmlpReasonCode;
	}

	public String getWlxaxmlpDescrizione() {
		if (wlxaxmlpDescrizione == null) {
			wlxaxmlpDescrizione = WLXAXMLP_DESCRIZIONE.getString(_byteBuffer);
		}
		return wlxaxmlpDescrizione;
	}

	public void setWlxaxmlpDescrizione(String wlxaxmlpDescrizione) {
		if (WLXAXMLP_DESCRIZIONE.equals(this.wlxaxmlpDescrizione, wlxaxmlpDescrizione)) {
			return;
		}
		WLXAXMLP_DESCRIZIONE.putString(wlxaxmlpDescrizione, _byteBuffer);
		this.wlxaxmlpDescrizione = wlxaxmlpDescrizione;
	}

	public String getWlxaxmlpSessionHandle() {
		if (wlxaxmlpSessionHandle == null) {
			wlxaxmlpSessionHandle = WLXAXMLP_SESSION_HANDLE.getString(_byteBuffer);
		}
		return wlxaxmlpSessionHandle;
	}

	public void setWlxaxmlpSessionHandle(String wlxaxmlpSessionHandle) {
		if (WLXAXMLP_SESSION_HANDLE.equals(this.wlxaxmlpSessionHandle, wlxaxmlpSessionHandle)) {
			return;
		}
		WLXAXMLP_SESSION_HANDLE.putString(wlxaxmlpSessionHandle, _byteBuffer);
		this.wlxaxmlpSessionHandle = wlxaxmlpSessionHandle;
	}

	public String getWlxaxmlpSysid() {
		if (wlxaxmlpSysid == null) {
			wlxaxmlpSysid = WLXAXMLP_SYSID.getString(_byteBuffer);
		}
		return wlxaxmlpSysid;
	}

	public void setWlxaxmlpSysid(String wlxaxmlpSysid) {
		if (WLXAXMLP_SYSID.equals(this.wlxaxmlpSysid, wlxaxmlpSysid)) {
			return;
		}
		WLXAXMLP_SYSID.putString(wlxaxmlpSysid, _byteBuffer);
		this.wlxaxmlpSysid = wlxaxmlpSysid;
	}

	public String getWlxaxmlpTransazione() {
		if (wlxaxmlpTransazione == null) {
			wlxaxmlpTransazione = WLXAXMLP_TRANSAZIONE.getString(_byteBuffer);
		}
		return wlxaxmlpTransazione;
	}

	public void setWlxaxmlpTransazione(String wlxaxmlpTransazione) {
		if (WLXAXMLP_TRANSAZIONE.equals(this.wlxaxmlpTransazione, wlxaxmlpTransazione)) {
			return;
		}
		WLXAXMLP_TRANSAZIONE.putString(wlxaxmlpTransazione, _byteBuffer);
		this.wlxaxmlpTransazione = wlxaxmlpTransazione;
	}

	public String getWlxaxmlpProgramma() {
		if (wlxaxmlpProgramma == null) {
			wlxaxmlpProgramma = WLXAXMLP_PROGRAMMA.getString(_byteBuffer);
		}
		return wlxaxmlpProgramma;
	}

	public void setWlxaxmlpProgramma(String wlxaxmlpProgramma) {
		if (WLXAXMLP_PROGRAMMA.equals(this.wlxaxmlpProgramma, wlxaxmlpProgramma)) {
			return;
		}
		WLXAXMLP_PROGRAMMA.putString(wlxaxmlpProgramma, _byteBuffer);
		this.wlxaxmlpProgramma = wlxaxmlpProgramma;
	}

	public String getWlxaxmlpProcedura() {
		if (wlxaxmlpProcedura == null) {
			wlxaxmlpProcedura = WLXAXMLP_PROCEDURA.getString(_byteBuffer);
		}
		return wlxaxmlpProcedura;
	}

	public void setWlxaxmlpProcedura(String wlxaxmlpProcedura) {
		if (WLXAXMLP_PROCEDURA.equals(this.wlxaxmlpProcedura, wlxaxmlpProcedura)) {
			return;
		}
		WLXAXMLP_PROCEDURA.putString(wlxaxmlpProcedura, _byteBuffer);
		this.wlxaxmlpProcedura = wlxaxmlpProcedura;
	}

	public String getWlxaxmlpCanale() {
		if (wlxaxmlpCanale == null) {
			wlxaxmlpCanale = WLXAXMLP_CANALE.getString(_byteBuffer);
		}
		return wlxaxmlpCanale;
	}

	public void setWlxaxmlpCanale(String wlxaxmlpCanale) {
		if (WLXAXMLP_CANALE.equals(this.wlxaxmlpCanale, wlxaxmlpCanale)) {
			return;
		}
		WLXAXMLP_CANALE.putString(wlxaxmlpCanale, _byteBuffer);
		this.wlxaxmlpCanale = wlxaxmlpCanale;
	}

	public String getWlxaxmlpIstituto() {
		if (wlxaxmlpIstituto == null) {
			wlxaxmlpIstituto = WLXAXMLP_ISTITUTO.getString(_byteBuffer);
		}
		return wlxaxmlpIstituto;
	}

	public void setWlxaxmlpIstituto(String wlxaxmlpIstituto) {
		if (WLXAXMLP_ISTITUTO.equals(this.wlxaxmlpIstituto, wlxaxmlpIstituto)) {
			return;
		}
		WLXAXMLP_ISTITUTO.putString(wlxaxmlpIstituto, _byteBuffer);
		this.wlxaxmlpIstituto = wlxaxmlpIstituto;
	}

	public String getWlxaxmlpAbiIstituto() {
		if (wlxaxmlpAbiIstituto == null) {
			wlxaxmlpAbiIstituto = WLXAXMLP_ABI_ISTITUTO.getString(_byteBuffer);
		}
		return wlxaxmlpAbiIstituto;
	}

	public void setWlxaxmlpAbiIstituto(String wlxaxmlpAbiIstituto) {
		if (WLXAXMLP_ABI_ISTITUTO.equals(this.wlxaxmlpAbiIstituto, wlxaxmlpAbiIstituto)) {
			return;
		}
		WLXAXMLP_ABI_ISTITUTO.putString(wlxaxmlpAbiIstituto, _byteBuffer);
		this.wlxaxmlpAbiIstituto = wlxaxmlpAbiIstituto;
	}

	public String getWlxaxmlpEnte() {
		if (wlxaxmlpEnte == null) {
			wlxaxmlpEnte = WLXAXMLP_ENTE.getString(_byteBuffer);
		}
		return wlxaxmlpEnte;
	}

	public void setWlxaxmlpEnte(String wlxaxmlpEnte) {
		if (WLXAXMLP_ENTE.equals(this.wlxaxmlpEnte, wlxaxmlpEnte)) {
			return;
		}
		WLXAXMLP_ENTE.putString(wlxaxmlpEnte, _byteBuffer);
		this.wlxaxmlpEnte = wlxaxmlpEnte;
	}

	public String getWlxaxmlpTipEnte() {
		if (wlxaxmlpTipEnte == null) {
			wlxaxmlpTipEnte = WLXAXMLP_TIP_ENTE.getString(_byteBuffer);
		}
		return wlxaxmlpTipEnte;
	}

	public void setWlxaxmlpTipEnte(String wlxaxmlpTipEnte) {
		if (WLXAXMLP_TIP_ENTE.equals(this.wlxaxmlpTipEnte, wlxaxmlpTipEnte)) {
			return;
		}
		WLXAXMLP_TIP_ENTE.putString(wlxaxmlpTipEnte, _byteBuffer);
		this.wlxaxmlpTipEnte = wlxaxmlpTipEnte;
	}

	public String getWlxaxmlpSubEnte() {
		if (wlxaxmlpSubEnte == null) {
			wlxaxmlpSubEnte = WLXAXMLP_SUB_ENTE.getString(_byteBuffer);
		}
		return wlxaxmlpSubEnte;
	}

	public void setWlxaxmlpSubEnte(String wlxaxmlpSubEnte) {
		if (WLXAXMLP_SUB_ENTE.equals(this.wlxaxmlpSubEnte, wlxaxmlpSubEnte)) {
			return;
		}
		WLXAXMLP_SUB_ENTE.putString(wlxaxmlpSubEnte, _byteBuffer);
		this.wlxaxmlpSubEnte = wlxaxmlpSubEnte;
	}

	public String getWlxaxmlpCab() {
		if (wlxaxmlpCab == null) {
			wlxaxmlpCab = WLXAXMLP_CAB.getString(_byteBuffer);
		}
		return wlxaxmlpCab;
	}

	public void setWlxaxmlpCab(String wlxaxmlpCab) {
		if (WLXAXMLP_CAB.equals(this.wlxaxmlpCab, wlxaxmlpCab)) {
			return;
		}
		WLXAXMLP_CAB.putString(wlxaxmlpCab, _byteBuffer);
		this.wlxaxmlpCab = wlxaxmlpCab;
	}

	public String getWlxaxmlpUfficio() {
		if (wlxaxmlpUfficio == null) {
			wlxaxmlpUfficio = WLXAXMLP_UFFICIO.getString(_byteBuffer);
		}
		return wlxaxmlpUfficio;
	}

	public void setWlxaxmlpUfficio(String wlxaxmlpUfficio) {
		if (WLXAXMLP_UFFICIO.equals(this.wlxaxmlpUfficio, wlxaxmlpUfficio)) {
			return;
		}
		WLXAXMLP_UFFICIO.putString(wlxaxmlpUfficio, _byteBuffer);
		this.wlxaxmlpUfficio = wlxaxmlpUfficio;
	}

	public String getWlxaxmlpSezione() {
		if (wlxaxmlpSezione == null) {
			wlxaxmlpSezione = WLXAXMLP_SEZIONE.getString(_byteBuffer);
		}
		return wlxaxmlpSezione;
	}

	public void setWlxaxmlpSezione(String wlxaxmlpSezione) {
		if (WLXAXMLP_SEZIONE.equals(this.wlxaxmlpSezione, wlxaxmlpSezione)) {
			return;
		}
		WLXAXMLP_SEZIONE.putString(wlxaxmlpSezione, _byteBuffer);
		this.wlxaxmlpSezione = wlxaxmlpSezione;
	}

	public String getWlxaxmlpTerm() {
		if (wlxaxmlpTerm == null) {
			wlxaxmlpTerm = WLXAXMLP_TERM.getString(_byteBuffer);
		}
		return wlxaxmlpTerm;
	}

	public void setWlxaxmlpTerm(String wlxaxmlpTerm) {
		if (WLXAXMLP_TERM.equals(this.wlxaxmlpTerm, wlxaxmlpTerm)) {
			return;
		}
		WLXAXMLP_TERM.putString(wlxaxmlpTerm, _byteBuffer);
		this.wlxaxmlpTerm = wlxaxmlpTerm;
	}

	public String getWlxaxmlpOpe() {
		if (wlxaxmlpOpe == null) {
			wlxaxmlpOpe = WLXAXMLP_OPE.getString(_byteBuffer);
		}
		return wlxaxmlpOpe;
	}

	public void setWlxaxmlpOpe(String wlxaxmlpOpe) {
		if (WLXAXMLP_OPE.equals(this.wlxaxmlpOpe, wlxaxmlpOpe)) {
			return;
		}
		WLXAXMLP_OPE.putString(wlxaxmlpOpe, _byteBuffer);
		this.wlxaxmlpOpe = wlxaxmlpOpe;
	}

	public int getWlxaxmlpDat() {
		if (wlxaxmlpDat == null) {
			wlxaxmlpDat = new Integer(WLXAXMLP_DAT.getInt(_byteBuffer));
		}
		return wlxaxmlpDat.intValue();
	}

	public void setWlxaxmlpDat(int wlxaxmlpDat) {
		if (WLXAXMLP_DAT.equals(this.wlxaxmlpDat, wlxaxmlpDat)) {
			return;
		}
		WLXAXMLP_DAT.putInt(wlxaxmlpDat, _byteBuffer);
		this.wlxaxmlpDat = new Integer(wlxaxmlpDat);
	}

	public int getWlxaxmlpOra() {
		if (wlxaxmlpOra == null) {
			wlxaxmlpOra = new Integer(WLXAXMLP_ORA.getInt(_byteBuffer));
		}
		return wlxaxmlpOra.intValue();
	}

	public void setWlxaxmlpOra(int wlxaxmlpOra) {
		if (WLXAXMLP_ORA.equals(this.wlxaxmlpOra, wlxaxmlpOra)) {
			return;
		}
		WLXAXMLP_ORA.putInt(wlxaxmlpOra, _byteBuffer);
		this.wlxaxmlpOra = new Integer(wlxaxmlpOra);
	}

	public String getWlxaxmlpEnteCont() {
		if (wlxaxmlpEnteCont == null) {
			wlxaxmlpEnteCont = WLXAXMLP_ENTE_CONT.getString(_byteBuffer);
		}
		return wlxaxmlpEnteCont;
	}

	public void setWlxaxmlpEnteCont(String wlxaxmlpEnteCont) {
		if (WLXAXMLP_ENTE_CONT.equals(this.wlxaxmlpEnteCont, wlxaxmlpEnteCont)) {
			return;
		}
		WLXAXMLP_ENTE_CONT.putString(wlxaxmlpEnteCont, _byteBuffer);
		this.wlxaxmlpEnteCont = wlxaxmlpEnteCont;
	}

	public String getWlxaxmlpTipEnteCont() {
		if (wlxaxmlpTipEnteCont == null) {
			wlxaxmlpTipEnteCont = WLXAXMLP_TIP_ENTE_CONT.getString(_byteBuffer);
		}
		return wlxaxmlpTipEnteCont;
	}

	public void setWlxaxmlpTipEnteCont(String wlxaxmlpTipEnteCont) {
		if (WLXAXMLP_TIP_ENTE_CONT.equals(this.wlxaxmlpTipEnteCont, wlxaxmlpTipEnteCont)) {
			return;
		}
		WLXAXMLP_TIP_ENTE_CONT.putString(wlxaxmlpTipEnteCont, _byteBuffer);
		this.wlxaxmlpTipEnteCont = wlxaxmlpTipEnteCont;
	}

	public String getWlxaxmlpSubEnteCont() {
		if (wlxaxmlpSubEnteCont == null) {
			wlxaxmlpSubEnteCont = WLXAXMLP_SUB_ENTE_CONT.getString(_byteBuffer);
		}
		return wlxaxmlpSubEnteCont;
	}

	public void setWlxaxmlpSubEnteCont(String wlxaxmlpSubEnteCont) {
		if (WLXAXMLP_SUB_ENTE_CONT.equals(this.wlxaxmlpSubEnteCont, wlxaxmlpSubEnteCont)) {
			return;
		}
		WLXAXMLP_SUB_ENTE_CONT.putString(wlxaxmlpSubEnteCont, _byteBuffer);
		this.wlxaxmlpSubEnteCont = wlxaxmlpSubEnteCont;
	}

	public String getWlxaxmlpCabCont() {
		if (wlxaxmlpCabCont == null) {
			wlxaxmlpCabCont = WLXAXMLP_CAB_CONT.getString(_byteBuffer);
		}
		return wlxaxmlpCabCont;
	}

	public void setWlxaxmlpCabCont(String wlxaxmlpCabCont) {
		if (WLXAXMLP_CAB_CONT.equals(this.wlxaxmlpCabCont, wlxaxmlpCabCont)) {
			return;
		}
		WLXAXMLP_CAB_CONT.putString(wlxaxmlpCabCont, _byteBuffer);
		this.wlxaxmlpCabCont = wlxaxmlpCabCont;
	}

	public int getWlxaxmlpDatContabile() {
		if (wlxaxmlpDatContabile == null) {
			wlxaxmlpDatContabile = new Integer(WLXAXMLP_DAT_CONTABILE.getInt(_byteBuffer));
		}
		return wlxaxmlpDatContabile.intValue();
	}

	public void setWlxaxmlpDatContabile(int wlxaxmlpDatContabile) {
		if (WLXAXMLP_DAT_CONTABILE.equals(this.wlxaxmlpDatContabile, wlxaxmlpDatContabile)) {
			return;
		}
		WLXAXMLP_DAT_CONTABILE.putInt(wlxaxmlpDatContabile, _byteBuffer);
		this.wlxaxmlpDatContabile = new Integer(wlxaxmlpDatContabile);
	}

	public String getCt30x015DominioI() {
		if (ct30x015DominioI == null) {
			ct30x015DominioI = CT30X015_DOMINIO_I.getString(_byteBuffer);
		}
		return ct30x015DominioI;
	}

	public void setCt30x015DominioI(String ct30x015DominioI) {
		if (CT30X015_DOMINIO_I.equals(this.ct30x015DominioI, ct30x015DominioI)) {
			return;
		}
		CT30X015_DOMINIO_I.putString(ct30x015DominioI, _byteBuffer);
		this.ct30x015DominioI = ct30x015DominioI;
	}

	public String getCt30x015NodoI() {
		if (ct30x015NodoI == null) {
			ct30x015NodoI = CT30X015_NODO_I.getString(_byteBuffer);
		}
		return ct30x015NodoI;
	}

	public void setCt30x015NodoI(String ct30x015NodoI) {
		if (CT30X015_NODO_I.equals(this.ct30x015NodoI, ct30x015NodoI)) {
			return;
		}
		CT30X015_NODO_I.putString(ct30x015NodoI, _byteBuffer);
		this.ct30x015NodoI = ct30x015NodoI;
	}

	public int getCt30x015PostazioneI() {
		if (ct30x015PostazioneI == null) {
			ct30x015PostazioneI = new Integer(CT30X015_POSTAZIONE_I.getInt(_byteBuffer));
		}
		return ct30x015PostazioneI.intValue();
	}

	public void setCt30x015PostazioneI(int ct30x015PostazioneI) {
		if (CT30X015_POSTAZIONE_I.equals(this.ct30x015PostazioneI, ct30x015PostazioneI)) {
			return;
		}
		CT30X015_POSTAZIONE_I.putInt(ct30x015PostazioneI, _byteBuffer);
		this.ct30x015PostazioneI = new Integer(ct30x015PostazioneI);
	}

	public String getCt30x015CentroI() {
		if (ct30x015CentroI == null) {
			ct30x015CentroI = CT30X015_CENTRO_I.getString(_byteBuffer);
		}
		return ct30x015CentroI;
	}

	public void setCt30x015CentroI(String ct30x015CentroI) {
		if (CT30X015_CENTRO_I.equals(this.ct30x015CentroI, ct30x015CentroI)) {
			return;
		}
		CT30X015_CENTRO_I.putString(ct30x015CentroI, _byteBuffer);
		this.ct30x015CentroI = ct30x015CentroI;
	}

	public int getCt30x015NumMessaggioI() {
		if (ct30x015NumMessaggioI == null) {
			ct30x015NumMessaggioI = new Integer(CT30X015_NUM_MESSAGGIO_I.getInt(_byteBuffer));
		}
		return ct30x015NumMessaggioI.intValue();
	}

	public void setCt30x015NumMessaggioI(int ct30x015NumMessaggioI) {
		if (CT30X015_NUM_MESSAGGIO_I.equals(this.ct30x015NumMessaggioI, ct30x015NumMessaggioI)) {
			return;
		}
		CT30X015_NUM_MESSAGGIO_I.putInt(ct30x015NumMessaggioI, _byteBuffer);
		this.ct30x015NumMessaggioI = new Integer(ct30x015NumMessaggioI);
	}

	public String getCt30x015AccSrvI() {
		if (ct30x015AccSrvI == null) {
			ct30x015AccSrvI = CT30X015_ACC_SRV_I.getString(_byteBuffer);
		}
		return ct30x015AccSrvI;
	}

	public void setCt30x015AccSrvI(String ct30x015AccSrvI) {
		if (CT30X015_ACC_SRV_I.equals(this.ct30x015AccSrvI, ct30x015AccSrvI)) {
			return;
		}
		CT30X015_ACC_SRV_I.putString(ct30x015AccSrvI, _byteBuffer);
		this.ct30x015AccSrvI = ct30x015AccSrvI;
	}

	public int getCt30x015ValoreI() {
		if (ct30x015ValoreI == null) {
			ct30x015ValoreI = new Integer(CT30X015_VALORE_I.getInt(_byteBuffer));
		}
		return ct30x015ValoreI.intValue();
	}

	public void setCt30x015ValoreI(int ct30x015ValoreI) {
		if (CT30X015_VALORE_I.equals(this.ct30x015ValoreI, ct30x015ValoreI)) {
			return;
		}
		CT30X015_VALORE_I.putInt(ct30x015ValoreI, _byteBuffer);
		this.ct30x015ValoreI = new Integer(ct30x015ValoreI);
	}

	public int getCt30x015CodsrvsecI() {
		if (ct30x015CodsrvsecI == null) {
			ct30x015CodsrvsecI = new Integer(CT30X015_CODSRVSEC_I.getInt(_byteBuffer));
		}
		return ct30x015CodsrvsecI.intValue();
	}

	public void setCt30x015CodsrvsecI(int ct30x015CodsrvsecI) {
		if (CT30X015_CODSRVSEC_I.equals(this.ct30x015CodsrvsecI, ct30x015CodsrvsecI)) {
			return;
		}
		CT30X015_CODSRVSEC_I.putInt(ct30x015CodsrvsecI, _byteBuffer);
		this.ct30x015CodsrvsecI = new Integer(ct30x015CodsrvsecI);
	}

	public int getCt30x015CodfilsecI() {
		if (ct30x015CodfilsecI == null) {
			ct30x015CodfilsecI = new Integer(CT30X015_CODFILSEC_I.getInt(_byteBuffer));
		}
		return ct30x015CodfilsecI.intValue();
	}

	public void setCt30x015CodfilsecI(int ct30x015CodfilsecI) {
		if (CT30X015_CODFILSEC_I.equals(this.ct30x015CodfilsecI, ct30x015CodfilsecI)) {
			return;
		}
		CT30X015_CODFILSEC_I.putInt(ct30x015CodfilsecI, _byteBuffer);
		this.ct30x015CodfilsecI = new Integer(ct30x015CodfilsecI);
	}

	public int getCt30x015CodcatsecI() {
		if (ct30x015CodcatsecI == null) {
			ct30x015CodcatsecI = new Integer(CT30X015_CODCATSEC_I.getInt(_byteBuffer));
		}
		return ct30x015CodcatsecI.intValue();
	}

	public void setCt30x015CodcatsecI(int ct30x015CodcatsecI) {
		if (CT30X015_CODCATSEC_I.equals(this.ct30x015CodcatsecI, ct30x015CodcatsecI)) {
			return;
		}
		CT30X015_CODCATSEC_I.putInt(ct30x015CodcatsecI, _byteBuffer);
		this.ct30x015CodcatsecI = new Integer(ct30x015CodcatsecI);
	}

	public int getCt30x015NumpartsecI() {
		if (ct30x015NumpartsecI == null) {
			ct30x015NumpartsecI = new Integer(CT30X015_NUMPARTSEC_I.getInt(_byteBuffer));
		}
		return ct30x015NumpartsecI.intValue();
	}

	public void setCt30x015NumpartsecI(int ct30x015NumpartsecI) {
		if (CT30X015_NUMPARTSEC_I.equals(this.ct30x015NumpartsecI, ct30x015NumpartsecI)) {
			return;
		}
		CT30X015_NUMPARTSEC_I.putInt(ct30x015NumpartsecI, _byteBuffer);
		this.ct30x015NumpartsecI = new Integer(ct30x015NumpartsecI);
	}

	public String getCt30x015CodTipExpeI() {
		if (ct30x015CodTipExpeI == null) {
			ct30x015CodTipExpeI = CT30X015_COD_TIP_EXPE_I.getString(_byteBuffer);
		}
		return ct30x015CodTipExpeI;
	}

	public void setCt30x015CodTipExpeI(String ct30x015CodTipExpeI) {
		if (CT30X015_COD_TIP_EXPE_I.equals(this.ct30x015CodTipExpeI, ct30x015CodTipExpeI)) {
			return;
		}
		CT30X015_COD_TIP_EXPE_I.putString(ct30x015CodTipExpeI, _byteBuffer);
		this.ct30x015CodTipExpeI = ct30x015CodTipExpeI;
	}

	public int getCt30x015NumCtaIntI() {
		if (ct30x015NumCtaIntI == null) {
			ct30x015NumCtaIntI = new Integer(CT30X015_NUM_CTA_INT_I.getInt(_byteBuffer));
		}
		return ct30x015NumCtaIntI.intValue();
	}

	public void setCt30x015NumCtaIntI(int ct30x015NumCtaIntI) {
		if (CT30X015_NUM_CTA_INT_I.equals(this.ct30x015NumCtaIntI, ct30x015NumCtaIntI)) {
			return;
		}
		CT30X015_NUM_CTA_INT_I.putInt(ct30x015NumCtaIntI, _byteBuffer);
		this.ct30x015NumCtaIntI = new Integer(ct30x015NumCtaIntI);
	}

	public String getCt30x015CodOperacionI() {
		if (ct30x015CodOperacionI == null) {
			ct30x015CodOperacionI = CT30X015_COD_OPERACION_I.getString(_byteBuffer);
		}
		return ct30x015CodOperacionI;
	}

	public void setCt30x015CodOperacionI(String ct30x015CodOperacionI) {
		if (CT30X015_COD_OPERACION_I.equals(this.ct30x015CodOperacionI, ct30x015CodOperacionI)) {
			return;
		}
		CT30X015_COD_OPERACION_I.putString(ct30x015CodOperacionI, _byteBuffer);
		this.ct30x015CodOperacionI = ct30x015CodOperacionI;
	}

	public String getCt30x015CodReferI() {
		if (ct30x015CodReferI == null) {
			ct30x015CodReferI = CT30X015_COD_REFER_I.getString(_byteBuffer);
		}
		return ct30x015CodReferI;
	}

	public void setCt30x015CodReferI(String ct30x015CodReferI) {
		if (CT30X015_COD_REFER_I.equals(this.ct30x015CodReferI, ct30x015CodReferI)) {
			return;
		}
		CT30X015_COD_REFER_I.putString(ct30x015CodReferI, _byteBuffer);
		this.ct30x015CodReferI = ct30x015CodReferI;
	}

	public String getCt30x015CodReferenciaOpeI() {
		if (ct30x015CodReferenciaOpeI == null) {
			ct30x015CodReferenciaOpeI = CT30X015_COD_REFERENCIA_OPE_I.getString(_byteBuffer);
		}
		return ct30x015CodReferenciaOpeI;
	}

	public void setCt30x015CodReferenciaOpeI(String ct30x015CodReferenciaOpeI) {
		if (CT30X015_COD_REFERENCIA_OPE_I.equals(this.ct30x015CodReferenciaOpeI, ct30x015CodReferenciaOpeI)) {
			return;
		}
		CT30X015_COD_REFERENCIA_OPE_I.putString(ct30x015CodReferenciaOpeI, _byteBuffer);
		this.ct30x015CodReferenciaOpeI = ct30x015CodReferenciaOpeI;
	}

	public String getCt30x015TxtMovimentoI() {
		if (ct30x015TxtMovimentoI == null) {
			ct30x015TxtMovimentoI = CT30X015_TXT_MOVIMENTO_I.getString(_byteBuffer);
		}
		return ct30x015TxtMovimentoI;
	}

	public void setCt30x015TxtMovimentoI(String ct30x015TxtMovimentoI) {
		if (CT30X015_TXT_MOVIMENTO_I.equals(this.ct30x015TxtMovimentoI, ct30x015TxtMovimentoI)) {
			return;
		}
		CT30X015_TXT_MOVIMENTO_I.putString(ct30x015TxtMovimentoI, _byteBuffer);
		this.ct30x015TxtMovimentoI = ct30x015TxtMovimentoI;
	}

	public String getCt30x015IndNaturalezaI() {
		if (ct30x015IndNaturalezaI == null) {
			ct30x015IndNaturalezaI = CT30X015_IND_NATURALEZA_I.getString(_byteBuffer);
		}
		return ct30x015IndNaturalezaI;
	}

	public void setCt30x015IndNaturalezaI(String ct30x015IndNaturalezaI) {
		if (CT30X015_IND_NATURALEZA_I.equals(this.ct30x015IndNaturalezaI, ct30x015IndNaturalezaI)) {
			return;
		}
		CT30X015_IND_NATURALEZA_I.putString(ct30x015IndNaturalezaI, _byteBuffer);
		this.ct30x015IndNaturalezaI = ct30x015IndNaturalezaI;
	}

	public String getCt30x015IndPagoEfecI() {
		if (ct30x015IndPagoEfecI == null) {
			ct30x015IndPagoEfecI = CT30X015_IND_PAGO_EFEC_I.getString(_byteBuffer);
		}
		return ct30x015IndPagoEfecI;
	}

	public void setCt30x015IndPagoEfecI(String ct30x015IndPagoEfecI) {
		if (CT30X015_IND_PAGO_EFEC_I.equals(this.ct30x015IndPagoEfecI, ct30x015IndPagoEfecI)) {
			return;
		}
		CT30X015_IND_PAGO_EFEC_I.putString(ct30x015IndPagoEfecI, _byteBuffer);
		this.ct30x015IndPagoEfecI = ct30x015IndPagoEfecI;
	}

	public String getCt30x015FecContableI() {
		if (ct30x015FecContableI == null) {
			ct30x015FecContableI = CT30X015_FEC_CONTABLE_I.getString(_byteBuffer);
		}
		return ct30x015FecContableI;
	}

	public void setCt30x015FecContableI(String ct30x015FecContableI) {
		if (CT30X015_FEC_CONTABLE_I.equals(this.ct30x015FecContableI, ct30x015FecContableI)) {
			return;
		}
		CT30X015_FEC_CONTABLE_I.putString(ct30x015FecContableI, _byteBuffer);
		this.ct30x015FecContableI = ct30x015FecContableI;
	}

	public String getCt30x015FecValorI() {
		if (ct30x015FecValorI == null) {
			ct30x015FecValorI = CT30X015_FEC_VALOR_I.getString(_byteBuffer);
		}
		return ct30x015FecValorI;
	}

	public void setCt30x015FecValorI(String ct30x015FecValorI) {
		if (CT30X015_FEC_VALOR_I.equals(this.ct30x015FecValorI, ct30x015FecValorI)) {
			return;
		}
		CT30X015_FEC_VALOR_I.putString(ct30x015FecValorI, _byteBuffer);
		this.ct30x015FecValorI = ct30x015FecValorI;
	}

	public String getCt30x015FecDisponibilitaI() {
		if (ct30x015FecDisponibilitaI == null) {
			ct30x015FecDisponibilitaI = CT30X015_FEC_DISPONIBILITA_I.getString(_byteBuffer);
		}
		return ct30x015FecDisponibilitaI;
	}

	public void setCt30x015FecDisponibilitaI(String ct30x015FecDisponibilitaI) {
		if (CT30X015_FEC_DISPONIBILITA_I.equals(this.ct30x015FecDisponibilitaI, ct30x015FecDisponibilitaI)) {
			return;
		}
		CT30X015_FEC_DISPONIBILITA_I.putString(ct30x015FecDisponibilitaI, _byteBuffer);
		this.ct30x015FecDisponibilitaI = ct30x015FecDisponibilitaI;
	}

	public String getCt30x015FecOperacionI() {
		if (ct30x015FecOperacionI == null) {
			ct30x015FecOperacionI = CT30X015_FEC_OPERACION_I.getString(_byteBuffer);
		}
		return ct30x015FecOperacionI;
	}

	public void setCt30x015FecOperacionI(String ct30x015FecOperacionI) {
		if (CT30X015_FEC_OPERACION_I.equals(this.ct30x015FecOperacionI, ct30x015FecOperacionI)) {
			return;
		}
		CT30X015_FEC_OPERACION_I.putString(ct30x015FecOperacionI, _byteBuffer);
		this.ct30x015FecOperacionI = ct30x015FecOperacionI;
	}

	public String getCt30x015CodProcOrigI() {
		if (ct30x015CodProcOrigI == null) {
			ct30x015CodProcOrigI = CT30X015_COD_PROC_ORIG_I.getString(_byteBuffer);
		}
		return ct30x015CodProcOrigI;
	}

	public void setCt30x015CodProcOrigI(String ct30x015CodProcOrigI) {
		if (CT30X015_COD_PROC_ORIG_I.equals(this.ct30x015CodProcOrigI, ct30x015CodProcOrigI)) {
			return;
		}
		CT30X015_COD_PROC_ORIG_I.putString(ct30x015CodProcOrigI, _byteBuffer);
		this.ct30x015CodProcOrigI = ct30x015CodProcOrigI;
	}

	public String getCt30x015CodCanaleI() {
		if (ct30x015CodCanaleI == null) {
			ct30x015CodCanaleI = CT30X015_COD_CANALE_I.getString(_byteBuffer);
		}
		return ct30x015CodCanaleI;
	}

	public void setCt30x015CodCanaleI(String ct30x015CodCanaleI) {
		if (CT30X015_COD_CANALE_I.equals(this.ct30x015CodCanaleI, ct30x015CodCanaleI)) {
			return;
		}
		CT30X015_COD_CANALE_I.putString(ct30x015CodCanaleI, _byteBuffer);
		this.ct30x015CodCanaleI = ct30x015CodCanaleI;
	}

	public BigDecimal getCt30x015TotaleEuroI() {
		if (ct30x015TotaleEuroI == null) {
			ct30x015TotaleEuroI = CT30X015_TOTALE_EURO_I.getBigDecimal(_byteBuffer);
		}
		return ct30x015TotaleEuroI;
	}

	public void setCt30x015TotaleEuroI(BigDecimal ct30x015TotaleEuroI) {
		if (CT30X015_TOTALE_EURO_I.equals(this.ct30x015TotaleEuroI, ct30x015TotaleEuroI)) {
			return;
		}
		CT30X015_TOTALE_EURO_I.putBigDecimal(ct30x015TotaleEuroI, _byteBuffer);
		this.ct30x015TotaleEuroI = ct30x015TotaleEuroI;
	}

	public BigDecimal getCt30x015CmTotaleEuroI() {
		if (ct30x015CmTotaleEuroI == null) {
			ct30x015CmTotaleEuroI = CT30X015_CM_TOTALE_EURO_I.getBigDecimal(_byteBuffer);
		}
		return ct30x015CmTotaleEuroI;
	}

	public void setCt30x015CmTotaleEuroI(BigDecimal ct30x015CmTotaleEuroI) {
		if (CT30X015_CM_TOTALE_EURO_I.equals(this.ct30x015CmTotaleEuroI, ct30x015CmTotaleEuroI)) {
			return;
		}
		CT30X015_CM_TOTALE_EURO_I.putBigDecimal(ct30x015CmTotaleEuroI, _byteBuffer);
		this.ct30x015CmTotaleEuroI = ct30x015CmTotaleEuroI;
	}

	public BigDecimal getCt30x015SpTotaleEuroI() {
		if (ct30x015SpTotaleEuroI == null) {
			ct30x015SpTotaleEuroI = CT30X015_SP_TOTALE_EURO_I.getBigDecimal(_byteBuffer);
		}
		return ct30x015SpTotaleEuroI;
	}

	public void setCt30x015SpTotaleEuroI(BigDecimal ct30x015SpTotaleEuroI) {
		if (CT30X015_SP_TOTALE_EURO_I.equals(this.ct30x015SpTotaleEuroI, ct30x015SpTotaleEuroI)) {
			return;
		}
		CT30X015_SP_TOTALE_EURO_I.putBigDecimal(ct30x015SpTotaleEuroI, _byteBuffer);
		this.ct30x015SpTotaleEuroI = ct30x015SpTotaleEuroI;
	}

	public BigDecimal getCt30x015SrTotaleEuroI() {
		if (ct30x015SrTotaleEuroI == null) {
			ct30x015SrTotaleEuroI = CT30X015_SR_TOTALE_EURO_I.getBigDecimal(_byteBuffer);
		}
		return ct30x015SrTotaleEuroI;
	}

	public void setCt30x015SrTotaleEuroI(BigDecimal ct30x015SrTotaleEuroI) {
		if (CT30X015_SR_TOTALE_EURO_I.equals(this.ct30x015SrTotaleEuroI, ct30x015SrTotaleEuroI)) {
			return;
		}
		CT30X015_SR_TOTALE_EURO_I.putBigDecimal(ct30x015SrTotaleEuroI, _byteBuffer);
		this.ct30x015SrTotaleEuroI = ct30x015SrTotaleEuroI;
	}

	public String getCt30x015CodProdI() {
		if (ct30x015CodProdI == null) {
			ct30x015CodProdI = CT30X015_COD_PROD_I.getString(_byteBuffer);
		}
		return ct30x015CodProdI;
	}

	public void setCt30x015CodProdI(String ct30x015CodProdI) {
		if (CT30X015_COD_PROD_I.equals(this.ct30x015CodProdI, ct30x015CodProdI)) {
			return;
		}
		CT30X015_COD_PROD_I.putString(ct30x015CodProdI, _byteBuffer);
		this.ct30x015CodProdI = ct30x015CodProdI;
	}

	public long getCt30x015NumOperacionO() {
		if (ct30x015NumOperacionO == null) {
			ct30x015NumOperacionO = new Long(CT30X015_NUM_OPERACION_O.getLong(_byteBuffer));
		}
		return ct30x015NumOperacionO.longValue();
	}

	public void setCt30x015NumOperacionO(long ct30x015NumOperacionO) {
		if (CT30X015_NUM_OPERACION_O.equals(this.ct30x015NumOperacionO, ct30x015NumOperacionO)) {
			return;
		}
		CT30X015_NUM_OPERACION_O.putLong(ct30x015NumOperacionO, _byteBuffer);
		this.ct30x015NumOperacionO = new Long(ct30x015NumOperacionO);
	}

	public BigDecimal getCt30x015ScTotaleEuroO() {
		if (ct30x015ScTotaleEuroO == null) {
			ct30x015ScTotaleEuroO = CT30X015_SC_TOTALE_EURO_O.getBigDecimal(_byteBuffer);
		}
		return ct30x015ScTotaleEuroO;
	}

	public void setCt30x015ScTotaleEuroO(BigDecimal ct30x015ScTotaleEuroO) {
		if (CT30X015_SC_TOTALE_EURO_O.equals(this.ct30x015ScTotaleEuroO, ct30x015ScTotaleEuroO)) {
			return;
		}
		CT30X015_SC_TOTALE_EURO_O.putBigDecimal(ct30x015ScTotaleEuroO, _byteBuffer);
		this.ct30x015ScTotaleEuroO = ct30x015ScTotaleEuroO;
	}

	public BigDecimal getCt30x015SnTotaleEuroO() {
		if (ct30x015SnTotaleEuroO == null) {
			ct30x015SnTotaleEuroO = CT30X015_SN_TOTALE_EURO_O.getBigDecimal(_byteBuffer);
		}
		return ct30x015SnTotaleEuroO;
	}

	public void setCt30x015SnTotaleEuroO(BigDecimal ct30x015SnTotaleEuroO) {
		if (CT30X015_SN_TOTALE_EURO_O.equals(this.ct30x015SnTotaleEuroO, ct30x015SnTotaleEuroO)) {
			return;
		}
		CT30X015_SN_TOTALE_EURO_O.putBigDecimal(ct30x015SnTotaleEuroO, _byteBuffer);
		this.ct30x015SnTotaleEuroO = ct30x015SnTotaleEuroO;
	}

	public int getCt30x015NumUtlMovO() {
		if (ct30x015NumUtlMovO == null) {
			ct30x015NumUtlMovO = new Integer(CT30X015_NUM_UTL_MOV_O.getInt(_byteBuffer));
		}
		return ct30x015NumUtlMovO.intValue();
	}

	public void setCt30x015NumUtlMovO(int ct30x015NumUtlMovO) {
		if (CT30X015_NUM_UTL_MOV_O.equals(this.ct30x015NumUtlMovO, ct30x015NumUtlMovO)) {
			return;
		}
		CT30X015_NUM_UTL_MOV_O.putInt(ct30x015NumUtlMovO, _byteBuffer);
		this.ct30x015NumUtlMovO = new Integer(ct30x015NumUtlMovO);
	}

	public BigDecimal getCt30x015IsTotaleEuroO() {
		if (ct30x015IsTotaleEuroO == null) {
			ct30x015IsTotaleEuroO = CT30X015_IS_TOTALE_EURO_O.getBigDecimal(_byteBuffer);
		}
		return ct30x015IsTotaleEuroO;
	}

	public void setCt30x015IsTotaleEuroO(BigDecimal ct30x015IsTotaleEuroO) {
		if (CT30X015_IS_TOTALE_EURO_O.equals(this.ct30x015IsTotaleEuroO, ct30x015IsTotaleEuroO)) {
			return;
		}
		CT30X015_IS_TOTALE_EURO_O.putBigDecimal(ct30x015IsTotaleEuroO, _byteBuffer);
		this.ct30x015IsTotaleEuroO = ct30x015IsTotaleEuroO;
	}

	public int getCt30x015CodErrO() {
		if (ct30x015CodErrO == null) {
			ct30x015CodErrO = new Integer(CT30X015_COD_ERR_O.getInt(_byteBuffer));
		}
		return ct30x015CodErrO.intValue();
	}

	public void setCt30x015CodErrO(int ct30x015CodErrO) {
		if (CT30X015_COD_ERR_O.equals(this.ct30x015CodErrO, ct30x015CodErrO)) {
			return;
		}
		CT30X015_COD_ERR_O.putInt(ct30x015CodErrO, _byteBuffer);
		this.ct30x015CodErrO = new Integer(ct30x015CodErrO);
	}

	public String getCt30x015DescErroreO() {
		if (ct30x015DescErroreO == null) {
			ct30x015DescErroreO = CT30X015_DESC_ERRORE_O.getString(_byteBuffer);
		}
		return ct30x015DescErroreO;
	}

	public void setCt30x015DescErroreO(String ct30x015DescErroreO) {
		if (CT30X015_DESC_ERRORE_O.equals(this.ct30x015DescErroreO, ct30x015DescErroreO)) {
			return;
		}
		CT30X015_DESC_ERRORE_O.putString(ct30x015DescErroreO, _byteBuffer);
		this.ct30x015DescErroreO = ct30x015DescErroreO;
	}

}
