package com.sample.ejb.bean;

import com.ibm.jzos.fields.CobolDatatypeFactory;
import com.ibm.jzos.fields.ExternalDecimalAsIntField;
import com.ibm.jzos.fields.PackedDecimalAsBigDecimalField;
import com.ibm.jzos.fields.PackedDecimalAsIntField;
import com.ibm.jzos.fields.PackedDecimalAsLongField;
import com.ibm.jzos.fields.StringField;
import java.math.BigDecimal;

// Generated by com.ibm.jzos.recordgen.cobol.RecordClassGenerator on Wed Feb 05 14:42:04 CET 2020

public class WOXABC40CommareaWrapper1 {

  /**
   * <pre>
   * 01  WOXABC40-01. </pre>
   */
  public static final int WOXABC40_01_len = 636;
  /**
   * <pre>
   * 02  WLXAXMLP-DATI-AMBI-IMM. </pre>
   */
  public static final int WLXAXMLP_DATI_AMBI_IMM_len = 109;
  /**
   * <pre>
   * 03  WLXAXMLP-DATI-ISTITUTO. </pre>
   */
  public static final int WLXAXMLP_DATI_ISTITUTO_len = 10;
  /**
   * <pre>
   * 03  WLXAXMLP-DATI-ENTE. </pre>
   */
  public static final int WLXAXMLP_DATI_ENTE_len = 13;
  /**
   * <pre>
   * 03  WLXAXMLP-ENTE-CONTABILE. </pre>
   */
  public static final int WLXAXMLP_ENTE_CONTABILE_len = 13;
  /**
   * <pre>
   * DATI SEC NEW
   * 02 WOXABC40-SEC-NEW-I. </pre>
   */
  public static final int WOXABC40_SEC_NEW_I_len = 7;
  /**
   * <pre>
   * 02 WOXABC40-SEC-OLD-I. </pre>
   */
  public static final int WOXABC40_SEC_OLD_I_len = 21;
  /**
   * <pre>
   * 02 WOXABC40-ISTITUTO-I. </pre>
   */
  public static final int WOXABC40_ISTITUTO_I_len = 5;
  /**
   * <pre>
   * 02 WOXABC40-DIVISA-O. </pre>
   */
  public static final int WOXABC40_DIVISA_O_len = 3;
  /**
   * <pre>
   * 02 WOXABC40-DATI-ANAG-O. </pre>
   */
  public static final int WOXABC40_DATI_ANAG_O_len = 165;
  /**
   * <pre>
   * 03 WOXABC40-NDG-O. </pre>
   */
  public static final int WOXABC40_NDG_O_len = 5;
  /**
   * <pre>
   * 02 WOXABC40-DATA-ORA-O. </pre>
   */
  public static final int WOXABC40_DATA_ORA_O_len = 14;
  /**
   * <pre>
   * 02 WOXABC40-DATI-SALDO-O. </pre>
   */
  public static final int WOXABC40_DATI_SALDO_O_len = 130;
  protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
  /**
   * <pre>
   * ---TESTATA DI TUTTI I TRACCIATI
   * 02  WLXAXMLP-RETURN-CODE            PIC X(2). </pre>
   */
  protected static final StringField WLXAXMLP_RETURN_CODE = factory.getStringField(2);
  /**
   * <pre>
   * 02  WLXAXMLP-REASON-CODE            PIC X(8). </pre>
   */
  protected static final StringField WLXAXMLP_REASON_CODE = factory.getStringField(8);
  /**
   * <pre>
   * 02  WLXAXMLP-DESCRIZIONE            PIC X(128). </pre>
   */
  protected static final StringField WLXAXMLP_DESCRIZIONE = factory.getStringField(128);
  /**
   * <pre>
   * 02  WLXAXMLP-SESSION-HANDLE         PIC X(26). </pre>
   */
  protected static final StringField WLXAXMLP_SESSION_HANDLE = factory.getStringField(26);
  public static final int WLXAXMLP_DATI_AMBI_IMM_offset = factory.getOffset();
  /**
   * <pre>
   * 03  WLXAXMLP-SYSID                 PIC X(8). </pre>
   */
  protected static final StringField WLXAXMLP_SYSID = factory.getStringField(8);
  /**
   * <pre>
   * 03  WLXAXMLP-TRANSAZIONE           PIC X(8). </pre>
   */
  protected static final StringField WLXAXMLP_TRANSAZIONE = factory.getStringField(8);
  /**
   * <pre>
   * 03  WLXAXMLP-PROGRAMMA             PIC X(8). </pre>
   */
  protected static final StringField WLXAXMLP_PROGRAMMA = factory.getStringField(8);
  /**
   * <pre>
   * 03  WLXAXMLP-PROCEDURA             PIC X(2). </pre>
   */
  protected static final StringField WLXAXMLP_PROCEDURA = factory.getStringField(2);
  /**
   * <pre>
   * 03  WLXAXMLP-CANALE                PIC X(3). </pre>
   */
  protected static final StringField WLXAXMLP_CANALE = factory.getStringField(3);
  public static final int WLXAXMLP_DATI_ISTITUTO_offset = factory.getOffset();
  /**
   * <pre>
   * 04  WLXAXMLP-ISTITUTO           PIC X(5). </pre>
   */
  protected static final StringField WLXAXMLP_ISTITUTO = factory.getStringField(5);
  /**
   * <pre>
   * 04  WLXAXMLP-ABI-ISTITUTO       PIC X(5). </pre>
   */
  protected static final StringField WLXAXMLP_ABI_ISTITUTO = factory.getStringField(5);
  public static final int WLXAXMLP_DATI_ENTE_offset = factory.getOffset();
  /**
   * <pre>
   * 04  WLXAXMLP-ENTE               PIC X(5). </pre>
   */
  protected static final StringField WLXAXMLP_ENTE = factory.getStringField(5);
  /**
   * <pre>
   * 04  WLXAXMLP-TIP-ENTE           PIC X(1). </pre>
   */
  protected static final StringField WLXAXMLP_TIP_ENTE = factory.getStringField(1);
  /**
   * <pre>
   * 04  WLXAXMLP-SUB-ENTE           PIC X(2). </pre>
   */
  protected static final StringField WLXAXMLP_SUB_ENTE = factory.getStringField(2);
  /**
   * <pre>
   * 04  WLXAXMLP-CAB                PIC X(5). </pre>
   */
  protected static final StringField WLXAXMLP_CAB = factory.getStringField(5);
  /**
   * <pre>
   * 03  WLXAXMLP-UFFICIO              PIC X(4). </pre>
   */
  protected static final StringField WLXAXMLP_UFFICIO = factory.getStringField(4);
  /**
   * <pre>
   * 03  WLXAXMLP-SEZIONE              PIC X(2). </pre>
   */
  protected static final StringField WLXAXMLP_SEZIONE = factory.getStringField(2);
  /**
   * <pre>
   * 03  WLXAXMLP-TERM                 PIC X(8). </pre>
   */
  protected static final StringField WLXAXMLP_TERM = factory.getStringField(8);
  /**
   * <pre>
   * 03  WLXAXMLP-OPE                  PIC X(8). </pre>
   */
  protected static final StringField WLXAXMLP_OPE = factory.getStringField(8);
  /**
   * <pre>
   * 03  WLXAXMLP-DAT                  PIC 9(8). </pre>
   */
  protected static final ExternalDecimalAsIntField WLXAXMLP_DAT = factory
      .getExternalDecimalAsIntField(8, false, false, false, false);
  /**
   * <pre>
   * 03  WLXAXMLP-ORA                  PIC 9(6). </pre>
   */
  protected static final ExternalDecimalAsIntField WLXAXMLP_ORA = factory
      .getExternalDecimalAsIntField(6, false, false, false, false);
  public static final int WLXAXMLP_ENTE_CONTABILE_offset = factory.getOffset();
  /**
   * <pre>
   * 04  WLXAXMLP-ENTE-CONT          PIC X(5). </pre>
   */
  protected static final StringField WLXAXMLP_ENTE_CONT = factory.getStringField(5);
  /**
   * <pre>
   * 04  WLXAXMLP-TIP-ENTE-CONT      PIC X(1). </pre>
   */
  protected static final StringField WLXAXMLP_TIP_ENTE_CONT = factory.getStringField(1);
  /**
   * <pre>
   * 04  WLXAXMLP-SUB-ENTE-CONT      PIC X(2). </pre>
   */
  protected static final StringField WLXAXMLP_SUB_ENTE_CONT = factory.getStringField(2);
  /**
   * <pre>
   * 04  WLXAXMLP-CAB-CONT           PIC X(5). </pre>
   */
  protected static final StringField WLXAXMLP_CAB_CONT = factory.getStringField(5);
  /**
   * <pre>
   * 03  WLXAXMLP-DAT-CONTABILE        PIC 9(8). </pre>
   */
  protected static final ExternalDecimalAsIntField WLXAXMLP_DAT_CONTABILE = factory
      .getExternalDecimalAsIntField(8, false, false, false, false);
  public static final int WOXABC40_SEC_NEW_I_offset = factory.getOffset();
  /**
   * <pre>
   * 03 WOXABC40-COD-TIP-EXPE-I PIC X(2). </pre>
   */
  protected static final StringField WOXABC40_COD_TIP_EXPE_I = factory.getStringField(2);
  /**
   * <pre>
   * 03 WOXABC40-NUM-CTA-INT-I PIC S9(8) COMP-3. </pre>
   */
  protected static final PackedDecimalAsIntField WOXABC40_NUM_CTA_INT_I = factory
      .getPackedDecimalAsIntField(8, true);
  public static final int WOXABC40_SEC_OLD_I_offset = factory.getOffset();
  /**
   * <pre>
   * 03 WOXABC40-SRV-SEC-OLD-I PIC X(3). </pre>
   */
  protected static final StringField WOXABC40_SRV_SEC_OLD_I = factory.getStringField(3);
  /**
   * <pre>
   * 03 WOXABC40-FIL-SEC-OLD-I PIC X(5). </pre>
   */
  protected static final StringField WOXABC40_FIL_SEC_OLD_I = factory.getStringField(5);
  /**
   * <pre>
   * 03 WOXABC40-CAT-SEC-OLD-I PIC X(4). </pre>
   */
  protected static final StringField WOXABC40_CAT_SEC_OLD_I = factory.getStringField(4);
  /**
   * <pre>
   * 03 WOXABC40-NUM-ACCORDO-I PIC S9(16) COMP-3. </pre>
   */
  protected static final PackedDecimalAsLongField WOXABC40_NUM_ACCORDO_I = factory
      .getPackedDecimalAsLongField(16, true);
  public static final int WOXABC40_ISTITUTO_I_offset = factory.getOffset();
  /**
   * <pre>
   * 03 WOXABC40-CODICE-I PIC X(5). </pre>
   */
  protected static final StringField WOXABC40_CODICE_I = factory.getStringField(5);
  public static final int WOXABC40_DIVISA_O_offset = factory.getOffset();
  /**
   * <pre>
   * 03 WOXABC40-DV-CODICE-O PIC X(3). </pre>
   */
  protected static final StringField WOXABC40_DV_CODICE_O = factory.getStringField(3);
  public static final int WOXABC40_DATI_ANAG_O_offset = factory.getOffset();
  /**
   * <pre>
   * 03 WOXABC40-INTESTAZIONE-O PIC X(160). </pre>
   */
  protected static final StringField WOXABC40_INTESTAZIONE_O = factory.getStringField(160);
  public static final int WOXABC40_NDG_O_offset = factory.getOffset();
  /**
   * <pre>
   * 04 WOXABC40-VALORE-O PIC S9(9) COMP-3. </pre>
   */
  protected static final PackedDecimalAsIntField WOXABC40_VALORE_O = factory
      .getPackedDecimalAsIntField(9, true);
  public static final int WOXABC40_DATA_ORA_O_offset = factory.getOffset();

  /**
   * <pre>
   * 03 WOXABC40-DATA-O PIC 9(8). </pre>
   */
  protected static final ExternalDecimalAsIntField WOXABC40_DATA_O = factory
      .getExternalDecimalAsIntField(8, false, false, false, false);

  /**
   * <pre>
   * 03 WOXABC40-ORA-O PIC 9(6). </pre>
   */
  protected static final ExternalDecimalAsIntField WOXABC40_ORA_O = factory
      .getExternalDecimalAsIntField(6, false, false, false, false);
  public static final int WOXABC40_DATI_SALDO_O_offset = factory.getOffset();
  /**
   * <pre>
   * 03 WOXABC40-SAL-CONT-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_SAL_CONT_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-SAL-LIQUIDO-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_SAL_LIQUIDO_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-SAL-DISP-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_SAL_DISP_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-SAL-PART-INDI-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_SAL_PART_INDI_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-DISPONIBILITA-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_DISPONIBILITA_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-PART-IND-ASS-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_PART_IND_ASS_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-PART-IND-ALT-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_PART_IND_ALT_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-PART-AVV-DARE-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_PART_AVV_DARE_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-PART-AVV-AVERE-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_PART_AVV_AVERE_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-FIDO-CASSA-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_FIDO_CASSA_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-FIDO-ASS-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_FIDO_ASS_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-FIDO-SBF-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_FIDO_SBF_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 03 WOXABC40-FIDO-PROMISCUO-O PIC S9(15)V9(3) COMP-3. </pre>
   */
  protected static final PackedDecimalAsBigDecimalField WOXABC40_FIDO_PROMISCUO_O = factory
      .getPackedDecimalAsBigDecimalField(18, 3, true);
  /**
   * <pre>
   * 02 WOXABC40-DATA-APER-O PIC 9(8). </pre>
   */
  protected static final ExternalDecimalAsIntField WOXABC40_DATA_APER_O = factory
      .getExternalDecimalAsIntField(8, false, false, false, false);
  /**
   * <pre>
   * 02 WOXABC40-DATA-EST-O PIC 9(8). </pre>
   */
  protected static final ExternalDecimalAsIntField WOXABC40_DATA_EST_O = factory
      .getExternalDecimalAsIntField(8, false, false, false, false);
  /**
   * <pre>
   * 02 WOXABC40-STATO-CON-O PIC X(2). </pre>
   */
  protected static final StringField WOXABC40_STATO_CON_O = factory.getStringField(2);

  static {
    factory.setStringTrimDefault(false);
  }

  protected byte[] _byteBuffer;
  // Instance variables used to cache field values
  protected String wlxaxmlpReturnCode;
  protected String wlxaxmlpReasonCode;
  protected String wlxaxmlpDescrizione;
  protected String wlxaxmlpSessionHandle;
  protected String wlxaxmlpSysid;
  protected String wlxaxmlpTransazione;
  protected String wlxaxmlpProgramma;
  protected String wlxaxmlpProcedura;
  protected String wlxaxmlpCanale;
  protected String wlxaxmlpIstituto;
  protected String wlxaxmlpAbiIstituto;
  protected String wlxaxmlpEnte;
  protected String wlxaxmlpTipEnte;
  protected String wlxaxmlpSubEnte;
  protected String wlxaxmlpCab;
  protected String wlxaxmlpUfficio;
  protected String wlxaxmlpSezione;
  protected String wlxaxmlpTerm;
  protected String wlxaxmlpOpe;
  protected Integer wlxaxmlpDat;
  protected Integer wlxaxmlpOra;
  protected String wlxaxmlpEnteCont;
  protected String wlxaxmlpTipEnteCont;
  protected String wlxaxmlpSubEnteCont;
  protected String wlxaxmlpCabCont;
  protected Integer wlxaxmlpDatContabile;
  protected String woxabc40CodTipExpeI;
  protected Integer woxabc40NumCtaIntI;
  protected String woxabc40SrvSecOldI;
  protected String woxabc40FilSecOldI;
  protected String woxabc40CatSecOldI;
  protected Long woxabc40NumAccordoI;
  protected String woxabc40CodiceI;
  protected String woxabc40DvCodiceO;
  protected String woxabc40IntestazioneO;
  protected Integer woxabc40ValoreO;
  protected Integer woxabc40DataO;
  protected Integer woxabc40OraO;
  protected BigDecimal woxabc40SalContO;
  protected BigDecimal woxabc40SalLiquidoO;
  protected BigDecimal woxabc40SalDispO;
  protected BigDecimal woxabc40SalPartIndiO;
  protected BigDecimal woxabc40DisponibilitaO;
  protected BigDecimal woxabc40PartIndAssO;
  protected BigDecimal woxabc40PartIndAltO;
  protected BigDecimal woxabc40PartAvvDareO;
  protected BigDecimal woxabc40PartAvvAvereO;
  protected BigDecimal woxabc40FidoCassaO;
  protected BigDecimal woxabc40FidoAssO;
  protected BigDecimal woxabc40FidoSbfO;
  protected BigDecimal woxabc40FidoPromiscuoO;
  protected Integer woxabc40DataAperO;
  protected Integer woxabc40DataEstO;
  protected String woxabc40StatoConO;


  public WOXABC40CommareaWrapper1(byte[] buffer) {
    this._byteBuffer = buffer;
  }

  public WOXABC40CommareaWrapper1() {
    this._byteBuffer = new byte[WOXABC40_01_len];
  }

  public byte[] getByteBuffer() {
    return _byteBuffer;
  }


  public String getWlxaxmlpReturnCode() {
    if (wlxaxmlpReturnCode == null) {
      wlxaxmlpReturnCode = WLXAXMLP_RETURN_CODE.getString(_byteBuffer);
    }
    return wlxaxmlpReturnCode;
  }

  public void setWlxaxmlpReturnCode(String wlxaxmlpReturnCode) {
    if (WLXAXMLP_RETURN_CODE.equals(this.wlxaxmlpReturnCode, wlxaxmlpReturnCode)) {
      return;
    }
    WLXAXMLP_RETURN_CODE.putString(wlxaxmlpReturnCode, _byteBuffer);
    this.wlxaxmlpReturnCode = wlxaxmlpReturnCode;
  }

  public String getWlxaxmlpReasonCode() {
    if (wlxaxmlpReasonCode == null) {
      wlxaxmlpReasonCode = WLXAXMLP_REASON_CODE.getString(_byteBuffer);
    }
    return wlxaxmlpReasonCode;
  }

  public void setWlxaxmlpReasonCode(String wlxaxmlpReasonCode) {
    if (WLXAXMLP_REASON_CODE.equals(this.wlxaxmlpReasonCode, wlxaxmlpReasonCode)) {
      return;
    }
    WLXAXMLP_REASON_CODE.putString(wlxaxmlpReasonCode, _byteBuffer);
    this.wlxaxmlpReasonCode = wlxaxmlpReasonCode;
  }

  public String getWlxaxmlpDescrizione() {
    if (wlxaxmlpDescrizione == null) {
      wlxaxmlpDescrizione = WLXAXMLP_DESCRIZIONE.getString(_byteBuffer);
    }
    return wlxaxmlpDescrizione;
  }

  public void setWlxaxmlpDescrizione(String wlxaxmlpDescrizione) {
    if (WLXAXMLP_DESCRIZIONE.equals(this.wlxaxmlpDescrizione, wlxaxmlpDescrizione)) {
      return;
    }
    WLXAXMLP_DESCRIZIONE.putString(wlxaxmlpDescrizione, _byteBuffer);
    this.wlxaxmlpDescrizione = wlxaxmlpDescrizione;
  }

  public String getWlxaxmlpSessionHandle() {
    if (wlxaxmlpSessionHandle == null) {
      wlxaxmlpSessionHandle = WLXAXMLP_SESSION_HANDLE.getString(_byteBuffer);
    }
    return wlxaxmlpSessionHandle;
  }

  public void setWlxaxmlpSessionHandle(String wlxaxmlpSessionHandle) {
    if (WLXAXMLP_SESSION_HANDLE.equals(this.wlxaxmlpSessionHandle, wlxaxmlpSessionHandle)) {
      return;
    }
    WLXAXMLP_SESSION_HANDLE.putString(wlxaxmlpSessionHandle, _byteBuffer);
    this.wlxaxmlpSessionHandle = wlxaxmlpSessionHandle;
  }

  public String getWlxaxmlpSysid() {
    if (wlxaxmlpSysid == null) {
      wlxaxmlpSysid = WLXAXMLP_SYSID.getString(_byteBuffer);
    }
    return wlxaxmlpSysid;
  }

  public void setWlxaxmlpSysid(String wlxaxmlpSysid) {
    if (WLXAXMLP_SYSID.equals(this.wlxaxmlpSysid, wlxaxmlpSysid)) {
      return;
    }
    WLXAXMLP_SYSID.putString(wlxaxmlpSysid, _byteBuffer);
    this.wlxaxmlpSysid = wlxaxmlpSysid;
  }

  public String getWlxaxmlpTransazione() {
    if (wlxaxmlpTransazione == null) {
      wlxaxmlpTransazione = WLXAXMLP_TRANSAZIONE.getString(_byteBuffer);
    }
    return wlxaxmlpTransazione;
  }

  public void setWlxaxmlpTransazione(String wlxaxmlpTransazione) {
    if (WLXAXMLP_TRANSAZIONE.equals(this.wlxaxmlpTransazione, wlxaxmlpTransazione)) {
      return;
    }
    WLXAXMLP_TRANSAZIONE.putString(wlxaxmlpTransazione, _byteBuffer);
    this.wlxaxmlpTransazione = wlxaxmlpTransazione;
  }

  public String getWlxaxmlpProgramma() {
    if (wlxaxmlpProgramma == null) {
      wlxaxmlpProgramma = WLXAXMLP_PROGRAMMA.getString(_byteBuffer);
    }
    return wlxaxmlpProgramma;
  }

  public void setWlxaxmlpProgramma(String wlxaxmlpProgramma) {
    if (WLXAXMLP_PROGRAMMA.equals(this.wlxaxmlpProgramma, wlxaxmlpProgramma)) {
      return;
    }
    WLXAXMLP_PROGRAMMA.putString(wlxaxmlpProgramma, _byteBuffer);
    this.wlxaxmlpProgramma = wlxaxmlpProgramma;
  }

  public String getWlxaxmlpProcedura() {
    if (wlxaxmlpProcedura == null) {
      wlxaxmlpProcedura = WLXAXMLP_PROCEDURA.getString(_byteBuffer);
    }
    return wlxaxmlpProcedura;
  }

  public void setWlxaxmlpProcedura(String wlxaxmlpProcedura) {
    if (WLXAXMLP_PROCEDURA.equals(this.wlxaxmlpProcedura, wlxaxmlpProcedura)) {
      return;
    }
    WLXAXMLP_PROCEDURA.putString(wlxaxmlpProcedura, _byteBuffer);
    this.wlxaxmlpProcedura = wlxaxmlpProcedura;
  }

  public String getWlxaxmlpCanale() {
    if (wlxaxmlpCanale == null) {
      wlxaxmlpCanale = WLXAXMLP_CANALE.getString(_byteBuffer);
    }
    return wlxaxmlpCanale;
  }

  public void setWlxaxmlpCanale(String wlxaxmlpCanale) {
    if (WLXAXMLP_CANALE.equals(this.wlxaxmlpCanale, wlxaxmlpCanale)) {
      return;
    }
    WLXAXMLP_CANALE.putString(wlxaxmlpCanale, _byteBuffer);
    this.wlxaxmlpCanale = wlxaxmlpCanale;
  }

  public String getWlxaxmlpIstituto() {
    if (wlxaxmlpIstituto == null) {
      wlxaxmlpIstituto = WLXAXMLP_ISTITUTO.getString(_byteBuffer);
    }
    return wlxaxmlpIstituto;
  }

  public void setWlxaxmlpIstituto(String wlxaxmlpIstituto) {
    if (WLXAXMLP_ISTITUTO.equals(this.wlxaxmlpIstituto, wlxaxmlpIstituto)) {
      return;
    }
    WLXAXMLP_ISTITUTO.putString(wlxaxmlpIstituto, _byteBuffer);
    this.wlxaxmlpIstituto = wlxaxmlpIstituto;
  }

  public String getWlxaxmlpAbiIstituto() {
    if (wlxaxmlpAbiIstituto == null) {
      wlxaxmlpAbiIstituto = WLXAXMLP_ABI_ISTITUTO.getString(_byteBuffer);
    }
    return wlxaxmlpAbiIstituto;
  }

  public void setWlxaxmlpAbiIstituto(String wlxaxmlpAbiIstituto) {
    if (WLXAXMLP_ABI_ISTITUTO.equals(this.wlxaxmlpAbiIstituto, wlxaxmlpAbiIstituto)) {
      return;
    }
    WLXAXMLP_ABI_ISTITUTO.putString(wlxaxmlpAbiIstituto, _byteBuffer);
    this.wlxaxmlpAbiIstituto = wlxaxmlpAbiIstituto;
  }

  public String getWlxaxmlpEnte() {
    if (wlxaxmlpEnte == null) {
      wlxaxmlpEnte = WLXAXMLP_ENTE.getString(_byteBuffer);
    }
    return wlxaxmlpEnte;
  }

  public void setWlxaxmlpEnte(String wlxaxmlpEnte) {
    if (WLXAXMLP_ENTE.equals(this.wlxaxmlpEnte, wlxaxmlpEnte)) {
      return;
    }
    WLXAXMLP_ENTE.putString(wlxaxmlpEnte, _byteBuffer);
    this.wlxaxmlpEnte = wlxaxmlpEnte;
  }

  public String getWlxaxmlpTipEnte() {
    if (wlxaxmlpTipEnte == null) {
      wlxaxmlpTipEnte = WLXAXMLP_TIP_ENTE.getString(_byteBuffer);
    }
    return wlxaxmlpTipEnte;
  }

  public void setWlxaxmlpTipEnte(String wlxaxmlpTipEnte) {
    if (WLXAXMLP_TIP_ENTE.equals(this.wlxaxmlpTipEnte, wlxaxmlpTipEnte)) {
      return;
    }
    WLXAXMLP_TIP_ENTE.putString(wlxaxmlpTipEnte, _byteBuffer);
    this.wlxaxmlpTipEnte = wlxaxmlpTipEnte;
  }

  public String getWlxaxmlpSubEnte() {
    if (wlxaxmlpSubEnte == null) {
      wlxaxmlpSubEnte = WLXAXMLP_SUB_ENTE.getString(_byteBuffer);
    }
    return wlxaxmlpSubEnte;
  }

  public void setWlxaxmlpSubEnte(String wlxaxmlpSubEnte) {
    if (WLXAXMLP_SUB_ENTE.equals(this.wlxaxmlpSubEnte, wlxaxmlpSubEnte)) {
      return;
    }
    WLXAXMLP_SUB_ENTE.putString(wlxaxmlpSubEnte, _byteBuffer);
    this.wlxaxmlpSubEnte = wlxaxmlpSubEnte;
  }

  public String getWlxaxmlpCab() {
    if (wlxaxmlpCab == null) {
      wlxaxmlpCab = WLXAXMLP_CAB.getString(_byteBuffer);
    }
    return wlxaxmlpCab;
  }

  public void setWlxaxmlpCab(String wlxaxmlpCab) {
    if (WLXAXMLP_CAB.equals(this.wlxaxmlpCab, wlxaxmlpCab)) {
      return;
    }
    WLXAXMLP_CAB.putString(wlxaxmlpCab, _byteBuffer);
    this.wlxaxmlpCab = wlxaxmlpCab;
  }

  public String getWlxaxmlpUfficio() {
    if (wlxaxmlpUfficio == null) {
      wlxaxmlpUfficio = WLXAXMLP_UFFICIO.getString(_byteBuffer);
    }
    return wlxaxmlpUfficio;
  }

  public void setWlxaxmlpUfficio(String wlxaxmlpUfficio) {
    if (WLXAXMLP_UFFICIO.equals(this.wlxaxmlpUfficio, wlxaxmlpUfficio)) {
      return;
    }
    WLXAXMLP_UFFICIO.putString(wlxaxmlpUfficio, _byteBuffer);
    this.wlxaxmlpUfficio = wlxaxmlpUfficio;
  }

  public String getWlxaxmlpSezione() {
    if (wlxaxmlpSezione == null) {
      wlxaxmlpSezione = WLXAXMLP_SEZIONE.getString(_byteBuffer);
    }
    return wlxaxmlpSezione;
  }

  public void setWlxaxmlpSezione(String wlxaxmlpSezione) {
    if (WLXAXMLP_SEZIONE.equals(this.wlxaxmlpSezione, wlxaxmlpSezione)) {
      return;
    }
    WLXAXMLP_SEZIONE.putString(wlxaxmlpSezione, _byteBuffer);
    this.wlxaxmlpSezione = wlxaxmlpSezione;
  }

  public String getWlxaxmlpTerm() {
    if (wlxaxmlpTerm == null) {
      wlxaxmlpTerm = WLXAXMLP_TERM.getString(_byteBuffer);
    }
    return wlxaxmlpTerm;
  }

  public void setWlxaxmlpTerm(String wlxaxmlpTerm) {
    if (WLXAXMLP_TERM.equals(this.wlxaxmlpTerm, wlxaxmlpTerm)) {
      return;
    }
    WLXAXMLP_TERM.putString(wlxaxmlpTerm, _byteBuffer);
    this.wlxaxmlpTerm = wlxaxmlpTerm;
  }

  public String getWlxaxmlpOpe() {
    if (wlxaxmlpOpe == null) {
      wlxaxmlpOpe = WLXAXMLP_OPE.getString(_byteBuffer);
    }
    return wlxaxmlpOpe;
  }

  public void setWlxaxmlpOpe(String wlxaxmlpOpe) {
    if (WLXAXMLP_OPE.equals(this.wlxaxmlpOpe, wlxaxmlpOpe)) {
      return;
    }
    WLXAXMLP_OPE.putString(wlxaxmlpOpe, _byteBuffer);
    this.wlxaxmlpOpe = wlxaxmlpOpe;
  }

  public int getWlxaxmlpDat() {
    if (wlxaxmlpDat == null) {
      wlxaxmlpDat = new Integer(WLXAXMLP_DAT.getInt(_byteBuffer));
    }
    return wlxaxmlpDat.intValue();
  }

  public void setWlxaxmlpDat(int wlxaxmlpDat) {
    if (WLXAXMLP_DAT.equals(this.wlxaxmlpDat, wlxaxmlpDat)) {
      return;
    }
    WLXAXMLP_DAT.putInt(wlxaxmlpDat, _byteBuffer);
    this.wlxaxmlpDat = new Integer(wlxaxmlpDat);
  }

  public int getWlxaxmlpOra() {
    if (wlxaxmlpOra == null) {
      wlxaxmlpOra = new Integer(WLXAXMLP_ORA.getInt(_byteBuffer));
    }
    return wlxaxmlpOra.intValue();
  }

  public void setWlxaxmlpOra(int wlxaxmlpOra) {
    if (WLXAXMLP_ORA.equals(this.wlxaxmlpOra, wlxaxmlpOra)) {
      return;
    }
    WLXAXMLP_ORA.putInt(wlxaxmlpOra, _byteBuffer);
    this.wlxaxmlpOra = new Integer(wlxaxmlpOra);
  }

  public String getWlxaxmlpEnteCont() {
    if (wlxaxmlpEnteCont == null) {
      wlxaxmlpEnteCont = WLXAXMLP_ENTE_CONT.getString(_byteBuffer);
    }
    return wlxaxmlpEnteCont;
  }

  public void setWlxaxmlpEnteCont(String wlxaxmlpEnteCont) {
    if (WLXAXMLP_ENTE_CONT.equals(this.wlxaxmlpEnteCont, wlxaxmlpEnteCont)) {
      return;
    }
    WLXAXMLP_ENTE_CONT.putString(wlxaxmlpEnteCont, _byteBuffer);
    this.wlxaxmlpEnteCont = wlxaxmlpEnteCont;
  }

  public String getWlxaxmlpTipEnteCont() {
    if (wlxaxmlpTipEnteCont == null) {
      wlxaxmlpTipEnteCont = WLXAXMLP_TIP_ENTE_CONT.getString(_byteBuffer);
    }
    return wlxaxmlpTipEnteCont;
  }

  public void setWlxaxmlpTipEnteCont(String wlxaxmlpTipEnteCont) {
    if (WLXAXMLP_TIP_ENTE_CONT.equals(this.wlxaxmlpTipEnteCont, wlxaxmlpTipEnteCont)) {
      return;
    }
    WLXAXMLP_TIP_ENTE_CONT.putString(wlxaxmlpTipEnteCont, _byteBuffer);
    this.wlxaxmlpTipEnteCont = wlxaxmlpTipEnteCont;
  }

  public String getWlxaxmlpSubEnteCont() {
    if (wlxaxmlpSubEnteCont == null) {
      wlxaxmlpSubEnteCont = WLXAXMLP_SUB_ENTE_CONT.getString(_byteBuffer);
    }
    return wlxaxmlpSubEnteCont;
  }

  public void setWlxaxmlpSubEnteCont(String wlxaxmlpSubEnteCont) {
    if (WLXAXMLP_SUB_ENTE_CONT.equals(this.wlxaxmlpSubEnteCont, wlxaxmlpSubEnteCont)) {
      return;
    }
    WLXAXMLP_SUB_ENTE_CONT.putString(wlxaxmlpSubEnteCont, _byteBuffer);
    this.wlxaxmlpSubEnteCont = wlxaxmlpSubEnteCont;
  }

  public String getWlxaxmlpCabCont() {
    if (wlxaxmlpCabCont == null) {
      wlxaxmlpCabCont = WLXAXMLP_CAB_CONT.getString(_byteBuffer);
    }
    return wlxaxmlpCabCont;
  }

  public void setWlxaxmlpCabCont(String wlxaxmlpCabCont) {
    if (WLXAXMLP_CAB_CONT.equals(this.wlxaxmlpCabCont, wlxaxmlpCabCont)) {
      return;
    }
    WLXAXMLP_CAB_CONT.putString(wlxaxmlpCabCont, _byteBuffer);
    this.wlxaxmlpCabCont = wlxaxmlpCabCont;
  }

  public int getWlxaxmlpDatContabile() {
    if (wlxaxmlpDatContabile == null) {
      wlxaxmlpDatContabile = new Integer(WLXAXMLP_DAT_CONTABILE.getInt(_byteBuffer));
    }
    return wlxaxmlpDatContabile.intValue();
  }

  public void setWlxaxmlpDatContabile(int wlxaxmlpDatContabile) {
    if (WLXAXMLP_DAT_CONTABILE.equals(this.wlxaxmlpDatContabile, wlxaxmlpDatContabile)) {
      return;
    }
    WLXAXMLP_DAT_CONTABILE.putInt(wlxaxmlpDatContabile, _byteBuffer);
    this.wlxaxmlpDatContabile = new Integer(wlxaxmlpDatContabile);
  }

  public String getWoxabc40CodTipExpeI() {
    if (woxabc40CodTipExpeI == null) {
      woxabc40CodTipExpeI = WOXABC40_COD_TIP_EXPE_I.getString(_byteBuffer);
    }
    return woxabc40CodTipExpeI;
  }

  public void setWoxabc40CodTipExpeI(String woxabc40CodTipExpeI) {
    if (WOXABC40_COD_TIP_EXPE_I.equals(this.woxabc40CodTipExpeI, woxabc40CodTipExpeI)) {
      return;
    }
    WOXABC40_COD_TIP_EXPE_I.putString(woxabc40CodTipExpeI, _byteBuffer);
    this.woxabc40CodTipExpeI = woxabc40CodTipExpeI;
  }

  public int getWoxabc40NumCtaIntI() {
    if (woxabc40NumCtaIntI == null) {
      woxabc40NumCtaIntI = new Integer(WOXABC40_NUM_CTA_INT_I.getInt(_byteBuffer));
    }
    return woxabc40NumCtaIntI.intValue();
  }

  public void setWoxabc40NumCtaIntI(int woxabc40NumCtaIntI) {
    if (WOXABC40_NUM_CTA_INT_I.equals(this.woxabc40NumCtaIntI, woxabc40NumCtaIntI)) {
      return;
    }
    WOXABC40_NUM_CTA_INT_I.putInt(woxabc40NumCtaIntI, _byteBuffer);
    this.woxabc40NumCtaIntI = new Integer(woxabc40NumCtaIntI);
  }

  public String getWoxabc40SrvSecOldI() {
    if (woxabc40SrvSecOldI == null) {
      woxabc40SrvSecOldI = WOXABC40_SRV_SEC_OLD_I.getString(_byteBuffer);
    }
    return woxabc40SrvSecOldI;
  }

  public void setWoxabc40SrvSecOldI(String woxabc40SrvSecOldI) {
    if (WOXABC40_SRV_SEC_OLD_I.equals(this.woxabc40SrvSecOldI, woxabc40SrvSecOldI)) {
      return;
    }
    WOXABC40_SRV_SEC_OLD_I.putString(woxabc40SrvSecOldI, _byteBuffer);
    this.woxabc40SrvSecOldI = woxabc40SrvSecOldI;
  }

  public String getWoxabc40FilSecOldI() {
    if (woxabc40FilSecOldI == null) {
      woxabc40FilSecOldI = WOXABC40_FIL_SEC_OLD_I.getString(_byteBuffer);
    }
    return woxabc40FilSecOldI;
  }

  public void setWoxabc40FilSecOldI(String woxabc40FilSecOldI) {
    if (WOXABC40_FIL_SEC_OLD_I.equals(this.woxabc40FilSecOldI, woxabc40FilSecOldI)) {
      return;
    }
    WOXABC40_FIL_SEC_OLD_I.putString(woxabc40FilSecOldI, _byteBuffer);
    this.woxabc40FilSecOldI = woxabc40FilSecOldI;
  }

  public String getWoxabc40CatSecOldI() {
    if (woxabc40CatSecOldI == null) {
      woxabc40CatSecOldI = WOXABC40_CAT_SEC_OLD_I.getString(_byteBuffer);
    }
    return woxabc40CatSecOldI;
  }

  public void setWoxabc40CatSecOldI(String woxabc40CatSecOldI) {
    if (WOXABC40_CAT_SEC_OLD_I.equals(this.woxabc40CatSecOldI, woxabc40CatSecOldI)) {
      return;
    }
    WOXABC40_CAT_SEC_OLD_I.putString(woxabc40CatSecOldI, _byteBuffer);
    this.woxabc40CatSecOldI = woxabc40CatSecOldI;
  }

  public long getWoxabc40NumAccordoI() {
    if (woxabc40NumAccordoI == null) {
      woxabc40NumAccordoI = new Long(WOXABC40_NUM_ACCORDO_I.getLong(_byteBuffer));
    }
    return woxabc40NumAccordoI.longValue();
  }

  public void setWoxabc40NumAccordoI(long woxabc40NumAccordoI) {
    if (WOXABC40_NUM_ACCORDO_I.equals(this.woxabc40NumAccordoI, woxabc40NumAccordoI)) {
      return;
    }
    WOXABC40_NUM_ACCORDO_I.putLong(woxabc40NumAccordoI, _byteBuffer);
    this.woxabc40NumAccordoI = new Long(woxabc40NumAccordoI);
  }

  public String getWoxabc40CodiceI() {
    if (woxabc40CodiceI == null) {
      woxabc40CodiceI = WOXABC40_CODICE_I.getString(_byteBuffer);
    }
    return woxabc40CodiceI;
  }

  public void setWoxabc40CodiceI(String woxabc40CodiceI) {
    if (WOXABC40_CODICE_I.equals(this.woxabc40CodiceI, woxabc40CodiceI)) {
      return;
    }
    WOXABC40_CODICE_I.putString(woxabc40CodiceI, _byteBuffer);
    this.woxabc40CodiceI = woxabc40CodiceI;
  }

  public String getWoxabc40DvCodiceO() {
    if (woxabc40DvCodiceO == null) {
      woxabc40DvCodiceO = WOXABC40_DV_CODICE_O.getString(_byteBuffer);
    }
    return woxabc40DvCodiceO;
  }

  public void setWoxabc40DvCodiceO(String woxabc40DvCodiceO) {
    if (WOXABC40_DV_CODICE_O.equals(this.woxabc40DvCodiceO, woxabc40DvCodiceO)) {
      return;
    }
    WOXABC40_DV_CODICE_O.putString(woxabc40DvCodiceO, _byteBuffer);
    this.woxabc40DvCodiceO = woxabc40DvCodiceO;
  }

  public String getWoxabc40IntestazioneO() {
    if (woxabc40IntestazioneO == null) {
      woxabc40IntestazioneO = WOXABC40_INTESTAZIONE_O.getString(_byteBuffer);
    }
    return woxabc40IntestazioneO;
  }

  public void setWoxabc40IntestazioneO(String woxabc40IntestazioneO) {
    if (WOXABC40_INTESTAZIONE_O.equals(this.woxabc40IntestazioneO, woxabc40IntestazioneO)) {
      return;
    }
    WOXABC40_INTESTAZIONE_O.putString(woxabc40IntestazioneO, _byteBuffer);
    this.woxabc40IntestazioneO = woxabc40IntestazioneO;
  }

  public int getWoxabc40ValoreO() {
    if (woxabc40ValoreO == null) {
      woxabc40ValoreO = new Integer(WOXABC40_VALORE_O.getInt(_byteBuffer));
    }
    return woxabc40ValoreO.intValue();
  }

  public void setWoxabc40ValoreO(int woxabc40ValoreO) {
    if (WOXABC40_VALORE_O.equals(this.woxabc40ValoreO, woxabc40ValoreO)) {
      return;
    }
    WOXABC40_VALORE_O.putInt(woxabc40ValoreO, _byteBuffer);
    this.woxabc40ValoreO = new Integer(woxabc40ValoreO);
  }

  public int getWoxabc40DataO() {
    if (woxabc40DataO == null) {
      woxabc40DataO = new Integer(WOXABC40_DATA_O.getInt(_byteBuffer));
    }
    return woxabc40DataO.intValue();
  }

  public void setWoxabc40DataO(int woxabc40DataO) {
    if (WOXABC40_DATA_O.equals(this.woxabc40DataO, woxabc40DataO)) {
      return;
    }
    WOXABC40_DATA_O.putInt(woxabc40DataO, _byteBuffer);
    this.woxabc40DataO = new Integer(woxabc40DataO);
  }

  public int getWoxabc40OraO() {
    if (woxabc40OraO == null) {
      woxabc40OraO = new Integer(WOXABC40_ORA_O.getInt(_byteBuffer));
    }
    return woxabc40OraO.intValue();
  }

  public void setWoxabc40OraO(int woxabc40OraO) {
    if (WOXABC40_ORA_O.equals(this.woxabc40OraO, woxabc40OraO)) {
      return;
    }
    WOXABC40_ORA_O.putInt(woxabc40OraO, _byteBuffer);
    this.woxabc40OraO = new Integer(woxabc40OraO);
  }

  public BigDecimal getWoxabc40SalContO() {
    if (woxabc40SalContO == null) {
      woxabc40SalContO = WOXABC40_SAL_CONT_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40SalContO;
  }

  public void setWoxabc40SalContO(BigDecimal woxabc40SalContO) {
    if (WOXABC40_SAL_CONT_O.equals(this.woxabc40SalContO, woxabc40SalContO)) {
      return;
    }
    WOXABC40_SAL_CONT_O.putBigDecimal(woxabc40SalContO, _byteBuffer);
    this.woxabc40SalContO = woxabc40SalContO;
  }

  public BigDecimal getWoxabc40SalLiquidoO() {
    if (woxabc40SalLiquidoO == null) {
      woxabc40SalLiquidoO = WOXABC40_SAL_LIQUIDO_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40SalLiquidoO;
  }

  public void setWoxabc40SalLiquidoO(BigDecimal woxabc40SalLiquidoO) {
    if (WOXABC40_SAL_LIQUIDO_O.equals(this.woxabc40SalLiquidoO, woxabc40SalLiquidoO)) {
      return;
    }
    WOXABC40_SAL_LIQUIDO_O.putBigDecimal(woxabc40SalLiquidoO, _byteBuffer);
    this.woxabc40SalLiquidoO = woxabc40SalLiquidoO;
  }

  public BigDecimal getWoxabc40SalDispO() {
    if (woxabc40SalDispO == null) {
      woxabc40SalDispO = WOXABC40_SAL_DISP_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40SalDispO;
  }

  public void setWoxabc40SalDispO(BigDecimal woxabc40SalDispO) {
    if (WOXABC40_SAL_DISP_O.equals(this.woxabc40SalDispO, woxabc40SalDispO)) {
      return;
    }
    WOXABC40_SAL_DISP_O.putBigDecimal(woxabc40SalDispO, _byteBuffer);
    this.woxabc40SalDispO = woxabc40SalDispO;
  }

  public BigDecimal getWoxabc40SalPartIndiO() {
    if (woxabc40SalPartIndiO == null) {
      woxabc40SalPartIndiO = WOXABC40_SAL_PART_INDI_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40SalPartIndiO;
  }

  public void setWoxabc40SalPartIndiO(BigDecimal woxabc40SalPartIndiO) {
    if (WOXABC40_SAL_PART_INDI_O.equals(this.woxabc40SalPartIndiO, woxabc40SalPartIndiO)) {
      return;
    }
    WOXABC40_SAL_PART_INDI_O.putBigDecimal(woxabc40SalPartIndiO, _byteBuffer);
    this.woxabc40SalPartIndiO = woxabc40SalPartIndiO;
  }

  public BigDecimal getWoxabc40DisponibilitaO() {
    if (woxabc40DisponibilitaO == null) {
      woxabc40DisponibilitaO = WOXABC40_DISPONIBILITA_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40DisponibilitaO;
  }

  public void setWoxabc40DisponibilitaO(BigDecimal woxabc40DisponibilitaO) {
    if (WOXABC40_DISPONIBILITA_O.equals(this.woxabc40DisponibilitaO, woxabc40DisponibilitaO)) {
      return;
    }
    WOXABC40_DISPONIBILITA_O.putBigDecimal(woxabc40DisponibilitaO, _byteBuffer);
    this.woxabc40DisponibilitaO = woxabc40DisponibilitaO;
  }

  public BigDecimal getWoxabc40PartIndAssO() {
    if (woxabc40PartIndAssO == null) {
      woxabc40PartIndAssO = WOXABC40_PART_IND_ASS_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40PartIndAssO;
  }

  public void setWoxabc40PartIndAssO(BigDecimal woxabc40PartIndAssO) {
    if (WOXABC40_PART_IND_ASS_O.equals(this.woxabc40PartIndAssO, woxabc40PartIndAssO)) {
      return;
    }
    WOXABC40_PART_IND_ASS_O.putBigDecimal(woxabc40PartIndAssO, _byteBuffer);
    this.woxabc40PartIndAssO = woxabc40PartIndAssO;
  }

  public BigDecimal getWoxabc40PartIndAltO() {
    if (woxabc40PartIndAltO == null) {
      woxabc40PartIndAltO = WOXABC40_PART_IND_ALT_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40PartIndAltO;
  }

  public void setWoxabc40PartIndAltO(BigDecimal woxabc40PartIndAltO) {
    if (WOXABC40_PART_IND_ALT_O.equals(this.woxabc40PartIndAltO, woxabc40PartIndAltO)) {
      return;
    }
    WOXABC40_PART_IND_ALT_O.putBigDecimal(woxabc40PartIndAltO, _byteBuffer);
    this.woxabc40PartIndAltO = woxabc40PartIndAltO;
  }

  public BigDecimal getWoxabc40PartAvvDareO() {
    if (woxabc40PartAvvDareO == null) {
      woxabc40PartAvvDareO = WOXABC40_PART_AVV_DARE_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40PartAvvDareO;
  }

  public void setWoxabc40PartAvvDareO(BigDecimal woxabc40PartAvvDareO) {
    if (WOXABC40_PART_AVV_DARE_O.equals(this.woxabc40PartAvvDareO, woxabc40PartAvvDareO)) {
      return;
    }
    WOXABC40_PART_AVV_DARE_O.putBigDecimal(woxabc40PartAvvDareO, _byteBuffer);
    this.woxabc40PartAvvDareO = woxabc40PartAvvDareO;
  }

  public BigDecimal getWoxabc40PartAvvAvereO() {
    if (woxabc40PartAvvAvereO == null) {
      woxabc40PartAvvAvereO = WOXABC40_PART_AVV_AVERE_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40PartAvvAvereO;
  }

  public void setWoxabc40PartAvvAvereO(BigDecimal woxabc40PartAvvAvereO) {
    if (WOXABC40_PART_AVV_AVERE_O.equals(this.woxabc40PartAvvAvereO, woxabc40PartAvvAvereO)) {
      return;
    }
    WOXABC40_PART_AVV_AVERE_O.putBigDecimal(woxabc40PartAvvAvereO, _byteBuffer);
    this.woxabc40PartAvvAvereO = woxabc40PartAvvAvereO;
  }

  public BigDecimal getWoxabc40FidoCassaO() {
    if (woxabc40FidoCassaO == null) {
      woxabc40FidoCassaO = WOXABC40_FIDO_CASSA_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40FidoCassaO;
  }

  public void setWoxabc40FidoCassaO(BigDecimal woxabc40FidoCassaO) {
    if (WOXABC40_FIDO_CASSA_O.equals(this.woxabc40FidoCassaO, woxabc40FidoCassaO)) {
      return;
    }
    WOXABC40_FIDO_CASSA_O.putBigDecimal(woxabc40FidoCassaO, _byteBuffer);
    this.woxabc40FidoCassaO = woxabc40FidoCassaO;
  }

  public BigDecimal getWoxabc40FidoAssO() {
    if (woxabc40FidoAssO == null) {
      woxabc40FidoAssO = WOXABC40_FIDO_ASS_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40FidoAssO;
  }

  public void setWoxabc40FidoAssO(BigDecimal woxabc40FidoAssO) {
    if (WOXABC40_FIDO_ASS_O.equals(this.woxabc40FidoAssO, woxabc40FidoAssO)) {
      return;
    }
    WOXABC40_FIDO_ASS_O.putBigDecimal(woxabc40FidoAssO, _byteBuffer);
    this.woxabc40FidoAssO = woxabc40FidoAssO;
  }

  public BigDecimal getWoxabc40FidoSbfO() {
    if (woxabc40FidoSbfO == null) {
      woxabc40FidoSbfO = WOXABC40_FIDO_SBF_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40FidoSbfO;
  }

  public void setWoxabc40FidoSbfO(BigDecimal woxabc40FidoSbfO) {
    if (WOXABC40_FIDO_SBF_O.equals(this.woxabc40FidoSbfO, woxabc40FidoSbfO)) {
      return;
    }
    WOXABC40_FIDO_SBF_O.putBigDecimal(woxabc40FidoSbfO, _byteBuffer);
    this.woxabc40FidoSbfO = woxabc40FidoSbfO;
  }

  public BigDecimal getWoxabc40FidoPromiscuoO() {
    if (woxabc40FidoPromiscuoO == null) {
      woxabc40FidoPromiscuoO = WOXABC40_FIDO_PROMISCUO_O.getBigDecimal(_byteBuffer);
    }
    return woxabc40FidoPromiscuoO;
  }

  public void setWoxabc40FidoPromiscuoO(BigDecimal woxabc40FidoPromiscuoO) {
    if (WOXABC40_FIDO_PROMISCUO_O.equals(this.woxabc40FidoPromiscuoO, woxabc40FidoPromiscuoO)) {
      return;
    }
    WOXABC40_FIDO_PROMISCUO_O.putBigDecimal(woxabc40FidoPromiscuoO, _byteBuffer);
    this.woxabc40FidoPromiscuoO = woxabc40FidoPromiscuoO;
  }

  public int getWoxabc40DataAperO() {
    if (woxabc40DataAperO == null) {
      woxabc40DataAperO = new Integer(WOXABC40_DATA_APER_O.getInt(_byteBuffer));
    }
    return woxabc40DataAperO.intValue();
  }

  public void setWoxabc40DataAperO(int woxabc40DataAperO) {
    if (WOXABC40_DATA_APER_O.equals(this.woxabc40DataAperO, woxabc40DataAperO)) {
      return;
    }
    WOXABC40_DATA_APER_O.putInt(woxabc40DataAperO, _byteBuffer);
    this.woxabc40DataAperO = new Integer(woxabc40DataAperO);
  }

  public int getWoxabc40DataEstO() {
    if (woxabc40DataEstO == null) {
      woxabc40DataEstO = new Integer(WOXABC40_DATA_EST_O.getInt(_byteBuffer));
    }
    return woxabc40DataEstO.intValue();
  }

  public void setWoxabc40DataEstO(int woxabc40DataEstO) {
    if (WOXABC40_DATA_EST_O.equals(this.woxabc40DataEstO, woxabc40DataEstO)) {
      return;
    }
    WOXABC40_DATA_EST_O.putInt(woxabc40DataEstO, _byteBuffer);
    this.woxabc40DataEstO = new Integer(woxabc40DataEstO);
  }

  public String getWoxabc40StatoConO() {
    if (woxabc40StatoConO == null) {
      woxabc40StatoConO = WOXABC40_STATO_CON_O.getString(_byteBuffer);
    }
    return woxabc40StatoConO;
  }

  public void setWoxabc40StatoConO(String woxabc40StatoConO) {
    if (WOXABC40_STATO_CON_O.equals(this.woxabc40StatoConO, woxabc40StatoConO)) {
      return;
    }
    WOXABC40_STATO_CON_O.putString(woxabc40StatoConO, _byteBuffer);
    this.woxabc40StatoConO = woxabc40StatoConO;
  }

}
